"""Render a TideReading into the SnowRaven tide block (web/Pi twin of
frontend/src/lib/tideFormatter.ts). Body and SnowRaven attribution are kept
separate so the combined copy can emit one attribution at the bottom."""

from services.tide import TideReading

SR_LINK = '<a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
NOAA_CREDIT = "Tide data from NOAA CO-OPS"
TIDE_ATTRIBUTION = f"{NOAA_CREDIT} · via {SR_LINK}"
COMBINED_ATTRIBUTION = f"Weather and tide generated by {SR_LINK}"


def _ft(v: float) -> str:
    return f"{round(v * 10) / 10:.1f}"


def format_tide_body(r: TideReading) -> str:
    lvl = f"{_ft(r.level_min)} ft" if r.level_min == r.level_max else f"{_ft(r.level_min)} – {_ft(r.level_max)} ft"
    trend = "Rising" if r.trend == "rising" else "Falling"
    trend_line = f"Tide: {trend} (turned during your checklist)" if r.turned_during else f"Tide: {trend}"
    lines = [
        "🌊",
        "Observed" if r.source == "observed" else "Predicted",
        f"Water level: {lvl}",
        trend_line,
    ]
    if r.prev_hl:
        lines.append(f"Previous {r.prev_hl.kind}: {_ft(r.prev_hl.v)} ft at {r.prev_hl.time_local}")
    if r.next_hl:
        lines.append(f"Next {r.next_hl.kind}: {_ft(r.next_hl.v)} ft at {r.next_hl.time_local}")
    lines.append(f"Station: {r.station['name']} ({r.station['id']}), {r.distance_mi:.1f} mi away")
    lines.append("Relative to MLLW")
    lines.append(NOAA_CREDIT)
    return "\n".join(lines)


def format_tide(r: TideReading) -> str:
    body = format_tide_body(r)
    return body[: -len(NOAA_CREDIT)] + TIDE_ATTRIBUTION if body.endswith(NOAA_CREDIT) else body
