import math
from datetime import datetime
from zoneinfo import ZoneInfo
from timezonefinder import TimezoneFinder

_tf = TimezoneFinder()

BEAUFORT = [
    (1, "Calm"),
    (3, "Mostly calm"),
    (7, "Light breeze"),
    (12, "Gentle breeze"),
    (18, "Moderate breeze"),
    (24, "Fresh breeze"),
    (31, "Strong breeze"),
    (38, "Near gale"),
    (math.inf, "Gale"),
]

_BEAUFORT_ORDER = {label: i for i, (_, label) in enumerate(BEAUFORT)}

CARDINALS = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]

ATTRIBUTION = 'Weather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'


def wind_description(mph: float) -> str:
    for threshold, label in BEAUFORT:
        if mph <= threshold:
            return label
    return "Gale"


def cardinal(degrees: float) -> str:
    return CARDINALS[round(degrees / 45) % 8]


def condition_emoji(owm_id: int) -> str:
    if 200 <= owm_id <= 232:
        return "⛈️"
    if 300 <= owm_id <= 321:
        return "🌦️"
    if 500 <= owm_id <= 531:
        return "🌧️"
    if 600 <= owm_id <= 622:
        return "❄️"
    if 700 <= owm_id <= 781:
        return "🌫️"
    if owm_id == 800:
        return "☀️"
    if owm_id == 801:
        return "🌤️"
    if owm_id == 802:
        return "⛅"
    if owm_id == 803:
        return "🌥️"
    if owm_id == 804:
        return "☁️"
    return "🌡️"


# Moon phase — a port of lunarphase-js@2.0.3 (pinned from the npm dist), with one
# deliberate deviation: the Julian Day is computed in PURE UTC (the library bakes
# in the runtime's local tz offset). Both runtimes (this file and
# frontend/src/lib/weatherFormatter.ts) MUST use this same deterministic form so
# the TS and Python blocks stay byte-identical.
LUNAR_MONTH = 29.53058770576

# Bin upper bounds (age <) at odd multiples of LUNAR_MONTH / 16; ages at or
# past the last bound wrap back to New.
MOON_PHASE_BOUNDS = [
    1.84566173161,   # New
    5.53698519483,   # Waxing Crescent
    9.22830865805,   # First Quarter
    12.91963212127,  # Waxing Gibbous
    16.61095558449,  # Full
    20.30227904771,  # Waning Gibbous
    23.99360251093,  # Last Quarter
    27.68492597415,  # Waning Crescent
]

# Indexed by phase: New, Waxing Crescent, First Quarter, Waxing Gibbous, Full,
# Waning Gibbous, Last Quarter, Waning Crescent. The Southern Hemisphere sees
# the moon mirrored, so its set swaps the waxing/waning emoji.
MOON_NORTH = ["🌑", "🌒", "🌓", "🌔", "🌕", "🌖", "🌗", "🌘"]
MOON_SOUTH = ["🌑", "🌘", "🌗", "🌖", "🌕", "🌔", "🌓", "🌒"]


def moon_phase_emoji(unix_ts: int, lat: float) -> str:
    jd = (unix_ts * 1000) / 86400000 + 2440587.5
    frac = (jd - 2451550.1) / LUNAR_MONTH
    frac = frac - math.floor(frac)
    if frac < 0:
        frac += 1
    age = frac * LUNAR_MONTH
    emojis = MOON_SOUTH if lat < 0 else MOON_NORTH
    for bound, emoji in zip(MOON_PHASE_BOUNDS, emojis):
        if age < bound:
            return emoji
    return emojis[0]


def _is_night_hour(item: dict) -> bool:
    # A sampled hour is night when its dt falls outside the sunrise–sunset window.
    return item["dt"] < item["sunrise"] or item["dt"] > item["sunset"]


def format_range(values: list[float], unit: str = "") -> str:
    rounded = [round(v) for v in values]
    lo, hi = min(rounded), max(rounded)
    if lo == hi:
        return f"{lo}{unit}"
    return f"{lo} - {hi}{unit}"


def get_timezone(lat: float, lng: float) -> ZoneInfo:
    tz_name = _tf.timezone_at(lat=lat, lng=lng) or "UTC"
    return ZoneInfo(tz_name)


def format_local_time(unix_ts: int, tz: ZoneInfo) -> str:
    dt = datetime.fromtimestamp(unix_ts, tz=tz)
    hour = dt.strftime("%I").lstrip("0") or "12"
    return f"{hour}:{dt.strftime('%M%p').lower()}"


def format_weather(hourly_responses: list[dict], tz: ZoneInfo, lat: float) -> str:
    first = hourly_responses[0]["data"][0]

    temps = [r["data"][0]["temp"] for r in hourly_responses]
    humids = [r["data"][0]["humidity"] for r in hourly_responses]
    dews = [r["data"][0]["dew_point"] for r in hourly_responses]
    wind_speeds = [r["data"][0]["wind_speed"] for r in hourly_responses]

    wind_descs = sorted(
        dict.fromkeys(wind_description(w) for w in wind_speeds),
        key=lambda d: _BEAUFORT_ORDER.get(d, 999),
    )
    wind_str = " - ".join(wind_descs)

    owm_id = first["weather"][0]["id"]
    condition = first["weather"][0]["description"].capitalize()
    emoji = condition_emoji(owm_id)
    wind_dirs = list(dict.fromkeys(cardinal(r["data"][0]["wind_deg"]) for r in hourly_responses))
    wind_dir = " - ".join(wind_dirs)
    clouds_list = [r["data"][0]["clouds"] for r in hourly_responses]

    sunrise = format_local_time(first["sunrise"], tz)
    sunset = format_local_time(first["sunset"], tz)

    # Night checklist (any sampled hour outside its sunrise–sunset window): append
    # the moon-phase emoji — computed from the checklist START hour, matching
    # raincrow — to the condition emoji, UNSPACED. Unspaced is load-bearing: the
    # comment stripper (commentBlocks.ts) anchors a block on its last emoji RUN; a
    # space would split the run and leak the condition emoji on strip.
    moon = (
        moon_phase_emoji(first["dt"], lat)
        if any(_is_night_hour(r["data"][0]) for r in hourly_responses)
        else ""
    )

    return (
        f"{emoji}{moon}\n"
        f"{condition}\n"
        f"Temperature: {format_range(temps, '°F')}\n"
        f"Wind: {wind_str}\n"
        f"Wind Direction: {wind_dir}\n"
        f"Cloud Cover: {format_range(clouds_list, '%')}\n"
        f"Humidity: {format_range(humids, '%')}\n"
        f"Dew point: {format_range(dews, '°F')}\n"
        f"Sunrise: {sunrise}\n"
        f"Sunset: {sunset}\n"
        f"{ATTRIBUTION}"
    )
