import math
from datetime import datetime
from zoneinfo import ZoneInfo
from timezonefinder import TimezoneFinder

_tf = TimezoneFinder()

BEAUFORT = [
    (1, "Calm"),
    (3, "Mostly calm"),
    (7, "Light breeze"),
    (12, "Gentle breeze"),
    (18, "Moderate breeze"),
    (24, "Fresh breeze"),
    (31, "Strong breeze"),
    (38, "Near gale"),
    (math.inf, "Gale"),
]

_BEAUFORT_ORDER = {label: i for i, (_, label) in enumerate(BEAUFORT)}

CARDINALS = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]

ATTRIBUTION = 'Weather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'


def is_finite_figure(v) -> bool:
    """THE ONE PREDICATE FOR "IS THIS PROVIDER FIGURE USABLE" ON THIS RUNTIME.

    Byte-twin of `isFiniteFigure` in frontend/src/lib/weatherFormatter.ts; every
    refusal below and in services/forecast.py is expressed through it, so the
    two transports cannot drift on what a malformed figure IS
    (.claude/rules/security.md, "a twinned builder pair agrees on what a
    malformed figure is").

    The `bool` exclusion is the member a reader is likely to think redundant,
    and it is MEASURED rather than reasoned: `isinstance(True, int)` is True in
    Python, so `round(True)` is 1, and `Math.round(true)` is 1 on the other
    side -- a boolean `temp` rendered "Temperature: 1°F" on BOTH runtimes. That
    is an AGREEING wrong number, which no amount of cross-transport parity
    checking could ever have caught, and it was 9 of the 50 measured hour
    shapes: the only 9 this side accepted. `v == v` excludes NaN; the `inf`
    test excludes both infinities.

    `services.plan_weather._finite` is an alias of this, not a second copy.
    """
    return (
        isinstance(v, (int, float))
        and not isinstance(v, bool)
        and v == v
        and abs(v) != math.inf
    )


# The nine figures every single-moment weather surface reads out of ONE provider
# hour: the six the summary prints, plus the three clock fields
# `format_local_time` and the night test dereference. This tuple IS the
# contract -- `assert_hour_figures` iterates it, so a tenth consumed field is
# added here rather than checked ad hoc. Twin of HOUR_FIGURES in the TS half.
HOUR_FIGURES = (
    "dt", "temp", "humidity", "dew_point", "wind_speed", "wind_deg", "clouds",
    "sunrise", "sunset",
)


def assert_hour_figures(hour) -> None:
    """Refuse a malformed provider hour's NINE FIGURES. Twin of
    `assertHourFigures`.

    THIS IS THE HALF EVERY SAMPLED HOUR OF A MULTI-HOUR BODY CONTRIBUTES, which
    is why it is separable from the condition half below. `format_weather`
    aggregates six of these over every response it is handed (the Temperature,
    Wind, Wind Direction, Cloud Cover, Humidity and Dew-point lines), and -- the
    non-obvious three -- it reads `dt`, `sunrise` and `sunset` from every
    response too, because `_is_night_hour` runs over all of them to decide
    whether the block carries a moon emoji. A reader who sees only
    `first["sunrise"]` a few lines below would conclude the clock fields were
    first-only; they are not, and that is the reason this whole tuple is checked
    per response rather than split further.
    """
    if not isinstance(hour, dict):
        raise TypeError("malformed provider hour: not an object")
    for field in HOUR_FIGURES:
        if not is_finite_figure(hour.get(field)):
            raise TypeError(f"malformed provider hour: {field} is not a finite number")


def assert_hour_condition(hour) -> None:
    """Refuse a malformed provider hour's CONDITION. Twin of
    `assertHourCondition`.

    THIS IS THE HALF ONLY THE FIRST SAMPLED HOUR CONTRIBUTES. `weather[0]["id"]`
    and `weather[0]["description"]` become the emoji and the condition line, and
    `format_weather` reads both from `first` alone -- a three-hour checklist's
    later hours never reach them.

    VALIDATE WHAT IS DEREFERENCED is already this function's rule one level
    down: `weather[1]` is deliberately unchecked because nothing reads it, and
    both runtimes ignore it identically. Applying the same rule one level UP is
    what keeps a provider hiccup on hour 2 of 3 from refusing a copy block whose
    every printed field is fine -- see decision 11 in
    pipeline/weather-at-malformed-parity/decisions.md for the measurement, and
    `test_weather_at_malformed_parity.py`'s multi-hour rows for the guard.
    """
    if not isinstance(hour, dict):
        raise TypeError("malformed provider hour: not an object")
    lst = hour.get("weather")
    if not isinstance(lst, list) or not lst:
        raise TypeError("malformed provider hour: weather is not a non-empty list")
    condition = lst[0]
    if not isinstance(condition, dict):
        raise TypeError("malformed provider hour: weather[0] is not an object")
    if not is_finite_figure(condition.get("id")):
        raise TypeError("malformed provider hour: weather[0].id is not a finite number")
    if not isinstance(condition.get("description"), str):
        raise TypeError("malformed provider hour: weather[0].description is not a string")


def assert_hour_reading(hour) -> None:
    """The WHOLE contract for ONE provider hour -- figures AND condition -- in
    the shape the timemachine `data[0]` and every adapted forecast slice share.
    Twin of `assertHourReading`.

    This is what a SINGLE-MOMENT caller wants: `build_weather_payload` reads
    every figure and the condition out of one adapted hour, so it validates one
    hour completely. A caller that aggregates several hours wants the two halves
    separately, per the field each hour actually contributes.

    Every refusal on this side was ALREADY implicit -- a `round()` that raised,
    a `KeyError`, a `.capitalize()` on None -- for the `current` and `hourly`
    tiers. Making it explicit is what puts the two runtimes on the same footing
    and, more importantly, makes it reachable on the `daily` tier, where
    `_hour_from_daily` used to default the value away before anything could
    refuse it (measured: `/weather/at` answered HTTP 200 with `tempF: 0` and a
    fabricated "Clear sky" for a body carrying no daily weather at all).

    WHAT THIS DOES NOT CLAIM. It checks ONE hour's figures, not their
    plausibility: `dt: 1e20` is a finite number, passes here, and both runtimes
    then agree on the (wrong) night reading it produces. Agreement is the
    property this guard delivers; range plausibility is unmeasured, is out of
    this build's scope rather than half-done in it, and is handed to the
    Chronicler as a ROADMAP.md candidate at closeout (nothing in ROADMAP.md
    names it yet).
    """
    assert_hour_figures(hour)
    assert_hour_condition(hour)


def wind_description(mph: float) -> str:
    for threshold, label in BEAUFORT:
        if mph <= threshold:
            return label
    return "Gale"


def cardinal(degrees: float) -> str:
    return CARDINALS[round(degrees / 45) % 8]


def condition_emoji(owm_id: int) -> str:
    if 200 <= owm_id <= 232:
        return "⛈️"
    if 300 <= owm_id <= 321:
        return "🌦️"
    if 500 <= owm_id <= 531:
        return "🌧️"
    if 600 <= owm_id <= 622:
        return "❄️"
    if 700 <= owm_id <= 781:
        return "🌫️"
    if owm_id == 800:
        return "☀️"
    if owm_id == 801:
        return "🌤️"
    if owm_id == 802:
        return "⛅"
    if owm_id == 803:
        return "🌥️"
    if owm_id == 804:
        return "☁️"
    return "🌡️"


# Moon phase — a port of lunarphase-js@2.0.3 (pinned from the npm dist), with one
# deliberate deviation: the Julian Day is computed in PURE UTC (the library bakes
# in the runtime's local tz offset). Both runtimes (this file and
# frontend/src/lib/weatherFormatter.ts) MUST use this same deterministic form so
# the TS and Python blocks stay byte-identical.
LUNAR_MONTH = 29.53058770576

# Bin upper bounds (age <) at odd multiples of LUNAR_MONTH / 16; ages at or
# past the last bound wrap back to New.
MOON_PHASE_BOUNDS = [
    1.84566173161,   # New
    5.53698519483,   # Waxing Crescent
    9.22830865805,   # First Quarter
    12.91963212127,  # Waxing Gibbous
    16.61095558449,  # Full
    20.30227904771,  # Waning Gibbous
    23.99360251093,  # Last Quarter
    27.68492597415,  # Waning Crescent
]

# Indexed by phase: New, Waxing Crescent, First Quarter, Waxing Gibbous, Full,
# Waning Gibbous, Last Quarter, Waning Crescent. The Southern Hemisphere sees
# the moon mirrored, so its set swaps the waxing/waning emoji.
MOON_NORTH = ["🌑", "🌒", "🌓", "🌔", "🌕", "🌖", "🌗", "🌘"]
MOON_SOUTH = ["🌑", "🌘", "🌗", "🌖", "🌕", "🌔", "🌓", "🌒"]


def moon_phase_emoji(unix_ts: int, lat: float) -> str:
    jd = (unix_ts * 1000) / 86400000 + 2440587.5
    frac = (jd - 2451550.1) / LUNAR_MONTH
    frac = frac - math.floor(frac)
    if frac < 0:
        frac += 1
    age = frac * LUNAR_MONTH
    emojis = MOON_SOUTH if lat < 0 else MOON_NORTH
    for bound, emoji in zip(MOON_PHASE_BOUNDS, emojis):
        if age < bound:
            return emoji
    return emojis[0]


def _is_night_hour(item: dict) -> bool:
    # A sampled hour is night when its dt falls outside the sunrise–sunset window.
    return item["dt"] < item["sunrise"] or item["dt"] > item["sunset"]


def format_range(values: list[float], unit: str = "") -> str:
    rounded = [round(v) for v in values]
    lo, hi = min(rounded), max(rounded)
    if lo == hi:
        return f"{lo}{unit}"
    return f"{lo} - {hi}{unit}"


def get_timezone(lat: float, lng: float) -> ZoneInfo:
    tz_name = _tf.timezone_at(lat=lat, lng=lng) or "UTC"
    return ZoneInfo(tz_name)


def format_local_time(unix_ts: int, tz: ZoneInfo) -> str:
    dt = datetime.fromtimestamp(unix_ts, tz=tz)
    hour = dt.strftime("%I").lstrip("0") or "12"
    return f"{hour}:{dt.strftime('%M%p').lower()}"


def format_weather(hourly_responses: list[dict], tz: ZoneInfo, lat: float) -> str:
    # The copy block is the WIDEST of the three malformed-figure surfaces and
    # the only one whose output a user pastes into a public eBird checklist, so
    # the refusal sits here rather than only in the callers: /weather/at (via
    # build_weather_payload) and /weather/{checklist_id} both funnel through
    # this one function. This side already refused 41 of the 50 measured
    # malformed hour shapes implicitly (a `round()` that raised, a KeyError, a
    # `.capitalize()` on None); the explicit form is what its TS twin can be
    # held to, and it also closes the 9 this side ACCEPTED -- the boolean rows,
    # where both runtimes agreed on a wrong number.
    #
    # THE CHECK IS PER FIELD-EACH-RESPONSE-CONTRIBUTES, not per response. The
    # nine figures are aggregated from EVERY sampled hour (including `dt`,
    # `sunrise` and `sunset`, via `_is_night_hour`), so every response's figures
    # are checked; the condition is read from `first` ALONE, so only `first`'s
    # condition is checked. Validating `first`-only fields on every response
    # would turn a provider hiccup on hour 2 of a 3-hour checklist into a total
    # refusal of a block whose every printed field is fine -- the same failure
    # mode the tier selector's candidate filter exists to prevent one module
    # over. Decision 11 carries the measurement and the both-directions
    # difference.
    if not isinstance(hourly_responses, list) or not hourly_responses:
        raise TypeError("malformed provider body: no hourly responses")
    for response in hourly_responses:
        if not isinstance(response, dict):
            raise TypeError("malformed provider body: a response is not an object")
        data = response.get("data")
        if not isinstance(data, list) or not data:
            raise TypeError("malformed provider body: data is not a non-empty list")
        assert_hour_figures(data[0])

    first = hourly_responses[0]["data"][0]
    assert_hour_condition(first)

    temps = [r["data"][0]["temp"] for r in hourly_responses]
    humids = [r["data"][0]["humidity"] for r in hourly_responses]
    dews = [r["data"][0]["dew_point"] for r in hourly_responses]
    wind_speeds = [r["data"][0]["wind_speed"] for r in hourly_responses]

    wind_descs = sorted(
        dict.fromkeys(wind_description(w) for w in wind_speeds),
        key=lambda d: _BEAUFORT_ORDER.get(d, 999),
    )
    wind_str = " - ".join(wind_descs)

    owm_id = first["weather"][0]["id"]
    condition = first["weather"][0]["description"].capitalize()
    emoji = condition_emoji(owm_id)
    wind_dirs = list(dict.fromkeys(cardinal(r["data"][0]["wind_deg"]) for r in hourly_responses))
    wind_dir = " - ".join(wind_dirs)
    clouds_list = [r["data"][0]["clouds"] for r in hourly_responses]

    sunrise = format_local_time(first["sunrise"], tz)
    sunset = format_local_time(first["sunset"], tz)

    # Night checklist (any sampled hour outside its sunrise–sunset window): append
    # the moon-phase emoji — computed from the checklist START hour, matching
    # raincrow — to the condition emoji, UNSPACED. Unspaced is load-bearing: the
    # comment stripper (commentBlocks.ts) anchors a block on its last emoji RUN; a
    # space would split the run and leak the condition emoji on strip.
    moon = (
        moon_phase_emoji(first["dt"], lat)
        if any(_is_night_hour(r["data"][0]) for r in hourly_responses)
        else ""
    )

    return (
        f"{emoji}{moon}\n"
        f"{condition}\n"
        f"Temperature: {format_range(temps, '°F')}\n"
        f"Wind: {wind_str}\n"
        f"Wind Direction: {wind_dir}\n"
        f"Cloud Cover: {format_range(clouds_list, '%')}\n"
        f"Humidity: {format_range(humids, '%')}\n"
        f"Dew point: {format_range(dews, '°F')}\n"
        f"Sunrise: {sunrise}\n"
        f"Sunset: {sunset}\n"
        f"{ATTRIBUTION}"
    )
