import math
from datetime import datetime
from zoneinfo import ZoneInfo
from timezonefinder import TimezoneFinder

_tf = TimezoneFinder()

BEAUFORT = [
    (1, "Calm"),
    (3, "Light air"),
    (7, "Light breeze"),
    (12, "Gentle breeze"),
    (18, "Moderate breeze"),
    (24, "Fresh breeze"),
    (31, "Strong breeze"),
    (38, "Near gale"),
    (math.inf, "Gale"),
]

CARDINALS = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]

ATTRIBUTION = 'Weather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'


def wind_description(mph: float) -> str:
    for threshold, label in BEAUFORT:
        if mph <= threshold:
            return label
    return "Gale"


def cardinal(degrees: float) -> str:
    return CARDINALS[round(degrees / 45) % 8]


def condition_emoji(owm_id: int) -> str:
    if 200 <= owm_id <= 232:
        return "⛈️"
    if 300 <= owm_id <= 321:
        return "🌦️"
    if 500 <= owm_id <= 531:
        return "🌧️"
    if 600 <= owm_id <= 622:
        return "❄️"
    if 700 <= owm_id <= 781:
        return "🌫️"
    if owm_id == 800:
        return "☀️"
    if owm_id == 801:
        return "🌤️"
    if owm_id == 802:
        return "⛅"
    if owm_id == 803:
        return "🌥️"
    if owm_id == 804:
        return "☁️"
    return "🌡️"


def format_range(values: list[float], unit: str = "") -> str:
    lo, hi = round(min(values)), round(max(values))
    if lo == hi:
        return f"{lo}{unit}"
    return f"{lo} - {hi}{unit}"


def get_timezone(lat: float, lng: float) -> ZoneInfo:
    tz_name = _tf.timezone_at(lat=lat, lng=lng) or "UTC"
    return ZoneInfo(tz_name)


def format_local_time(unix_ts: int, tz: ZoneInfo) -> str:
    dt = datetime.fromtimestamp(unix_ts, tz=tz)
    hour = dt.strftime("%I").lstrip("0") or "12"
    return f"{hour}:{dt.strftime('%M%p').lower()}"


def format_weather(hourly_responses: list[dict], tz: ZoneInfo) -> str:
    first = hourly_responses[0]["data"][0]

    temps = [r["data"][0]["temp"] for r in hourly_responses]
    humids = [r["data"][0]["humidity"] for r in hourly_responses]
    dews = [r["data"][0]["dew_point"] for r in hourly_responses]
    wind_speeds = [r["data"][0]["wind_speed"] for r in hourly_responses]

    wind_descs = list(dict.fromkeys(wind_description(w) for w in wind_speeds))
    wind_str = " - ".join(wind_descs)

    owm_id = first["weather"][0]["id"]
    condition = first["weather"][0]["description"].capitalize()
    emoji = condition_emoji(owm_id)
    wind_dirs = list(dict.fromkeys(cardinal(r["data"][0]["wind_deg"]) for r in hourly_responses))
    wind_dir = " - ".join(wind_dirs)
    clouds = first["clouds"]

    sunrise = format_local_time(first["sunrise"], tz)
    sunset = format_local_time(first["sunset"], tz)

    return (
        f"{emoji}\n"
        f"{condition}\n"
        f"Temperature: {format_range(temps, '°F')}\n"
        f"Wind: {wind_str}\n"
        f"Wind Direction: {wind_dir}\n"
        f"Cloud Cover: {clouds}%\n"
        f"Humidity: {format_range(humids, '%')}\n"
        f"Dew point: {format_range(dews, '°F')}\n"
        f"Sunrise: {sunrise}\n"
        f"Sunset: {sunset}\n"
        f"{ATTRIBUTION}"
    )
