// @vitest-environment jsdom
//
// A species name from the user's CSV must never reach a lookup table's
// PROTOTYPE (security review finding 1, Medium).
//
// `.claude/rules/security.md` writes this down twice -- `Object.hasOwn` on the
// read (v0.5.81) and `Object.create(null)` on the accumulator (v0.5.90) -- and
// the Statistics tab's `sciByNorm` / `sciFor` shipped to review with neither,
// because it was copied from the neighbouring table instead of from the rule.
//
// WHAT THAT COSTS, measured through the real aggregation rather than reasoned
// about. `Common Name` is a raw CSV column with no shape validation anywhere on
// its path, so on a bare `TABLE[key]`:
//
//   "__proto__"    -> Object.prototype, an OBJECT. React refuses to render it
//                     as a child, so the whole Statistics tab throws.
//   "constructor"  -> a truthy FUNCTION, which passes the `sciFor(...) &&`
//                     truthiness gate and then paints nothing: a silently wrong
//                     scientific name rather than an absent one. Eleven names
//                     behave this way (`toString`, `valueOf`, `hasOwnProperty`,
//                     `isPrototypeOf`, `toLocaleString`,
//                     `propertyIsEnumerable` and the four `__define*` /
//                     `__lookup*` accessors).
//
// Opening the picker is enough to reach it: `speciesOptions` maps `sciFor` over
// EVERY name and `SpeciesCombobox` renders each option's `sciName`, so no
// selection is required.
//
// WHY THE HOSTILE NAMES ARE IN THE FIXTURE'S CSV COLUMN and not written into a
// table by hand: `{ __proto__: x }` in source is special-cased by the language
// to set the prototype and creates NO own property, so a literal tests a shape
// that cannot arrive from storage. The rule says to build the probe with
// `JSON.parse`; going one better, this drives the REAL observation rows through
// the REAL memo, which is the path the value actually takes.
//
// THIS IS ALSO A POLLUTION PROBE, and it is expected to find none: the write is
// guarded and the value is a string, so `Object.prototype` is never touched.
// Asserted anyway, because "not exploitable for pollution" is a claim that
// should fail loudly if a later change makes it false.
//
// WHAT THE BEHAVIOURAL HALF CANNOT SEE, established by mutation rather than
// assumed. The fix has two protections and they are REDUNDANT: with
// `Object.create(null)` the table has no prototype to fall through to, and with
// `Object.hasOwn` the read never falls through. Removing EITHER alone leaves
// every test below green -- measured -- and only removing both turns them red.
// That is the "two mechanisms overlap and only one is guarded" shape, and the
// honest answer here is that there is no behaviour only one of them protects.
// So the pair is pinned at SOURCE level instead, which is the only instrument
// that can tell them apart, with comments stripped so this file's own
// explanation of the defect cannot satisfy the scan. The rule asks for both
// deliberately: the null prototype makes the table safe, and the guard makes
// that safety visible at the point of use, where a later reader cannot
// "simplify" it away invisibly.

/// <reference types="node" />
import { describe, it, expect, vi, beforeEach, afterEach, afterAll } from 'vitest'
import { render, screen, cleanup, waitFor, fireEvent } from '@testing-library/react'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { MLExportRow } from '../lib/parseMLExport'

const TEST_DATA = vi.hoisted(() => ({
  taxonomyCodesJson: '{"American Crow":"amecro"}',
  mlRows: null as MLExportRow[] | null,
}))

/** The three shapes that behave differently on a plain object. `__proto__` is
 *  the accessor that yields an object; `constructor` and `toString` are the
 *  truthy-function family; a normal name proves the table still works. */
const HOSTILE = ['__proto__', 'constructor', 'toString']

function row(submissionId: string, commonName: string, scientificName: string) {
  return {
    submissionId, commonName, scientificName,
    date: '2024-05-24', location: 'Pond', locationId: 'L1', latitude: 45, longitude: -93,
    county: 'Hennepin', count: 2, breedingCode: null, speciesComments: '', catalogIds: [],
    stateProvince: 'US-MN', duration: 30, distance: 1, protocol: 'Traveling', numObservers: 1,
    time: '07:00 AM', allObsReported: true, area: null,
    // A real SnowRaven block, so the Weather section renders at all: its
    // attribution gate refuses anything without one.
    checklistComments: '☁️  Overcast clouds  Temperature: 60°F  Wind: Light breeze  '
      + 'Wind Direction: W  Cloud Cover: 20%  Humidity: 72%  Dew point: 55°F  '
      + 'Sunrise: 6:16am  Sunset: 7:56pm  '
      + 'Weather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>',
  }
}

// Enough checklists to clear WEATHER_SECTION_MIN_READABLE, with the hostile
// names spread across them so they reach `species.names` and the picker.
const FIXTURE_OBS = [
  ...HOSTILE.flatMap((name, i) => [0, 1].map(k => row(`S${10 + i * 2 + k}`, name, `Sci ${name}`))),
  ...[0, 1].map(k => row(`S${20 + k}`, '__proto__ (Northern)', 'Sci __proto__ (Northern)')),
  ...[0, 1, 2].map(k => row(`S${30 + k}`, 'American Crow', 'Corvus brachyrhynchos')),
]

function mlRow(catalogId: string, commonName: string, format: MLExportRow['format']): MLExportRow {
  return {
    catalogId, commonName, format, scientificName: `Sci ${commonName}`,
    date: '2024-05-24', location: 'Pond', county: 'Hennepin', latitude: 45, longitude: -93,
    caption: '', mediaNotes: '', observationDetails: '', ageSex: '', behaviors: '', time: '',
    year: 2024, month: 5, avgRating: null, numRatings: 0, checklistId: 'S10',
  }
}

// SnowMap is heavy (MapLibre) and this file drives the tab all the way to ready,
// so the Geographic Stats map really does mount after the idle callback -- and
// the real one reads the persisted style through the storage seam, which this
// file mocks partially. Left unstubbed it produced an UNHANDLED REJECTION that
// outlived the file and surfaced against an unrelated later one, which is the
// same cross-file shape `.claude/rules/testing.md` records for the recharts
// timer. Stubbed exactly as `BirdingStats.test.tsx` does.
vi.mock('./SnowMap', () => ({
  SnowMap: ({ children }: { children?: React.ReactNode }) => (
    <div data-testid="snowmap-stub">{children}</div>
  ),
}))
vi.mock('react-map-gl/maplibre', () => ({
  Marker: ({ children }: { children?: React.ReactNode }) => <div>{children}</div>,
  Popup: ({ children }: { children?: React.ReactNode }) => <div>{children}</div>,
  useMap: () => ({ current: undefined }),
}))

vi.mock('../lib/observationsCache', () => ({
  loadEbirdObservations: vi.fn(async () => ({ headerLine: '', observations: FIXTURE_OBS })),
}))
vi.mock('../lib/mlExportCache', () => ({
  loadMLExport: vi.fn(async () => TEST_DATA.mlRows === null
    ? null
    : { entries: [], mediaMap: {}, rows: TEST_DATA.mlRows }),
}))
vi.mock('../lib/storage', () => ({
  storage: {
    getFilesStatus: vi.fn(async () => ({
      ebird: { filename: 'ebird.csv', uploadedAt: '2024-06-01' },
      ml: TEST_DATA.mlRows === null
        ? null
        : { filename: 'ML__fixture_USER.csv', uploadedAt: '2024-06-01' },
    })),
    getSetting: vi.fn(async () => null),
    setSetting: vi.fn(async () => {}),
    readFile: vi.fn(async () => null),
    getApiKey: vi.fn(async () => null),
  },
}))
vi.mock('../lib/transport', () => ({
  transport: {
    post: vi.fn(async (path: string) => (path === '/taxonomy/codes'
      ? { codes: JSON.parse(TEST_DATA.taxonomyCodesJson), orders: {} }
      : {})),
    get: vi.fn(async () => ({ species: [] })),
  },
}))

let BirdingStats: typeof import('./BirdingStats').BirdingStats

beforeEach(async () => {
  TEST_DATA.taxonomyCodesJson = '{"American Crow":"amecro"}'
  TEST_DATA.mlRows = null
  ;({ BirdingStats } = await import('./BirdingStats'))
})
afterEach(() => { cleanup(); vi.clearAllMocks() })
afterAll(() => new Promise((r) => setTimeout(r, 120)))

/** Drive the tab to its ready state. The section's own rAF gate is why this
 *  waits on rendered content rather than on a tick. */
async function renderStats() {
  render(<BirdingStats onGoToSettings={() => {}} onGoToWeather={() => {}} onOpenSpecies={() => {}} />)
  await waitFor(() => expect(screen.getByText('Statistics')).toBeTruthy(), { timeout: 10_000 })
  await waitFor(() => expect(screen.getByRole('heading', { name: 'Weather' })).toBeTruthy(), { timeout: 10_000 })
}

describe('a species named after a prototype member (security finding 1)', () => {
  it('does not crash the Statistics tab, and the Weather section renders', async () => {
    // The headline outcome: on the unfixed code `sciFor('__proto__')` returns
    // `Object.prototype`, React throws on it as a child, and the tab is gone.
    //
    // But this test CANNOT reject that revert, and saying so is the point.
    // `renderStats()` leaves the picker CLOSED, and the throw needs the options
    // rendered, so against the exact pre-fix shape this case stays green. The
    // test that actually holds the line is 'the picker lists every hostile name
    // with NO scientific name at all' below, which opens it; the source pin
    // holds the two protections apart, since either alone also stays green here
    // (they are redundant by design). Per .claude/rules/security.md, a
    // success-path fixture names the test that can reject the revert.
    const onError = vi.spyOn(console, 'error').mockImplementation(() => {})
    await renderStats()
    expect(screen.getByRole('heading', { name: 'Weather' })).toBeTruthy()
    // React logs its "Objects are not valid as a React child" through
    // console.error even where a boundary catches the throw, so a clean render
    // is asserted on the log too rather than only on the DOM.
    const shouted = onError.mock.calls.map(c => String(c[0])).join(' | ')
    expect(shouted).not.toMatch(/not valid as a React child/i)
    onError.mockRestore()
  })

  it('the picker lists every hostile name with NO scientific name at all', async () => {
    // Opening the picker is the whole trigger: `speciesOptions` maps `sciFor`
    // over every name, so the value is computed for all of them whether or not
    // one is chosen.
    await renderStats()
    const combo = screen.getByRole('combobox', { name: 'Filter by species' })
    fireEvent.focus(combo)
    const options = await screen.findAllByRole('option')
    const labels = options.map(o => o.textContent ?? '')

    for (const name of HOSTILE) {
      expect(labels.some(l => l.includes(name)), `${name} is offered`).toBe(true)
    }
    // The real name still resolves, so the table is doing its job rather than
    // being switched off -- the assertions above would pass on a `sciFor` that
    // always returned undefined.
    const crow = options.find(o => (o.textContent ?? '').includes('American Crow'))!
    expect(crow.textContent).toContain('Corvus brachyrhynchos')

    // And no option shows an inherited value. `[object Object]` is the
    // `__proto__` outcome; `function` the eleven-name outcome.
    for (const l of labels) {
      expect(l).not.toContain('[object Object]')
      expect(l.toLowerCase()).not.toContain('function')
    }
  })

  it('keeps BOTH protections, which only a source-level check can distinguish', () => {
    // See the header: each protection alone makes every behavioural assertion
    // above pass, so this is what stops one of them being dropped as redundant.
    // Resolved from the working directory, not from `import.meta.url`: this
    // file runs under jsdom, where `import.meta.url` is an http URL and
    // `fileURLToPath` throws. Vitest's cwd is `frontend/`.
    const src = stripComments(readFileSync(
      resolve(process.cwd(), 'src/components/BirdingStats.tsx'), 'utf8'))
    // Sliced to the memo and its accessor, so a match cannot come from an
    // unrelated table elsewhere in a 2,400-line file.
    const from = src.indexOf('const sciByNorm')
    const to = src.indexOf('const normTaxonOrder')
    expect(from, 'the sciByNorm memo is findable').toBeGreaterThan(-1)
    expect(to, 'the slice has an end').toBeGreaterThan(from)
    const body = src.slice(from, to)
    expect(body).toContain('Object.create(null)')
    expect(body).toContain('Object.hasOwn(m, norm)')
    expect(body).toContain('Object.hasOwn(sciByNorm, key)')
    // Non-vacuity: the stripper must not have eaten the code with the prose, or
    // three `toContain`s pass against an empty string.
    expect(body).toContain('const sciByNorm')
    expect(body.length).toBeGreaterThan(200)
    // And the shape that shipped to review must be gone, not merely joined.
    expect(body).not.toContain('sciByNorm[normalizeSpeciesName(name)]')
  })

  it('treats missing prototype names as absent and keeps them out of every external href', async () => {
    TEST_DATA.mlRows = [
      mlRow('101', '__proto__', 'Photo'),
      mlRow('102', 'constructor', 'Audio'),
      mlRow('103', 'toString', 'Video'),
    ]
    await renderStats()

    for (const name of HOSTILE) {
      expect(screen.queryByRole('link', {
        name: `View ${name} on eBird (opens in a new tab)`,
      })).toBeNull()
    }

    // Non-vacuity: a real own code still reaches the same BirdName path.
    const crowLinks = screen.getAllByRole('link', {
      name: 'View American Crow on eBird (opens in a new tab)',
    }) as HTMLAnchorElement[]
    expect(crowLinks.length).toBeGreaterThan(0)
    expect(crowLinks.every(a => a.getAttribute('href') === 'https://ebird.org/species/amecro')).toBe(true)

    // These are the three Media ranking links. On the unfixed code each has a
    // truthy inherited taxonCode; __proto__ becomes [object Object] and the two
    // function-valued names become encoded function source. A miss now omits
    // the taxonCode parameter instead of emitting inherited data.
    const mlLinks = Array.from(document.querySelectorAll<HTMLAnchorElement>(
      'a[href^="https://media.ebird.org/catalog?mediaType="]',
    ))
    expect(mlLinks).toHaveLength(3)
    for (const a of mlLinks) {
      expect(new URL(a.href).searchParams.has('taxonCode')).toBe(false)
      expect(a.href).not.toContain('%5Bobject%20Object%5D')
      expect(a.href.toLowerCase()).not.toContain('function')
    }
  })

  it('resolves a genuine own __proto__ code supplied by parsed JSON', async () => {
    const parsed = JSON.parse('{"__proto__":"proto-own","American Crow":"amecro"}') as Record<string, string>
    expect(Object.hasOwn(parsed, '__proto__')).toBe(true)
    expect(Object.hasOwn({ __proto__: 'proto-own' }, '__proto__')).toBe(false)
    TEST_DATA.taxonomyCodesJson = JSON.stringify(parsed)

    await renderStats()
    const links = screen.getAllByRole('link', {
      name: 'View __proto__ on eBird (opens in a new tab)',
    }) as HTMLAnchorElement[]
    expect(links.length).toBeGreaterThan(0)
    expect(links.every(a => a.getAttribute('href') === 'https://ebird.org/species/proto-own')).toBe(true)
  })

  it('retains a normalized __proto__ key in the real accumulator', async () => {
    // This is a realistic raw-form response key: the batch sends the raw form
    // and its parent, and a scientific-name match can resolve the raw entry.
    // codeFor receives the normalized name from Top Species, so the raw lookup
    // misses and only the normalized accumulator can answer.
    const parsed = JSON.parse('{"__proto__ (Northern)":"proto-norm","American Crow":"amecro"}') as Record<string, string>
    expect(Object.hasOwn(parsed, '__proto__ (Northern)')).toBe(true)
    expect(Object.hasOwn(parsed, '__proto__')).toBe(false)
    TEST_DATA.taxonomyCodesJson = JSON.stringify(parsed)

    await renderStats()
    const links = screen.getAllByRole('link', {
      name: 'View __proto__ on eBird (opens in a new tab)',
    }) as HTMLAnchorElement[]
    expect(links.length).toBeGreaterThan(0)
    expect(links.every(a => a.getAttribute('href') === 'https://ebird.org/species/proto-norm')).toBe(true)
  })

  it('keeps the taxon accumulator and all three reads visibly guarded in source', () => {
    const src = stripComments(readFileSync(
      resolve(process.cwd(), 'src/components/BirdingStats.tsx'), 'utf8'))
    const from = src.indexOf('const normTaxon')
    const to = src.indexOf('const sciByNorm')
    expect(from, 'the normTaxon memo is findable').toBeGreaterThan(-1)
    expect(to, 'the taxon slice has an end').toBeGreaterThan(from)
    const taxonBody = src.slice(from, to)
    expect(taxonBody).toContain('const m: Record<string, string> = Object.create(null)')
    expect(taxonBody).toContain('Object.hasOwn(mlTaxonMap, name)')
    expect(taxonBody).toContain('Object.hasOwn(normTaxon, norm)')
    expect(taxonBody).not.toContain('mlTaxonMap[name] ??')
    expect(taxonBody).not.toContain('normTaxon[normalizeSpeciesName(name)]')

    const coverFrom = src.indexOf('const coverIndex')
    const coverTo = src.indexOf('const provenance', coverFrom)
    expect(coverFrom, 'the cover-index memo is findable').toBeGreaterThan(-1)
    expect(coverTo, 'the cover-index slice has an end').toBeGreaterThan(coverFrom)
    const coverBody = src.slice(coverFrom, coverTo)
    expect(coverBody).toContain('Object.hasOwn(normTaxon, norm) ? normTaxon[norm] : undefined')
    expect(coverBody).not.toContain('norm => normTaxon[norm]')
  })

  it('leaves Object.prototype untouched, which is the claim rather than the outcome', async () => {
    // Flow a parsed own key with an object value through the actual accumulator,
    // not merely through a stand-in object constructed inside the assertion.
    TEST_DATA.taxonomyCodesJson = '{"__proto__":{"polluted":"yes"}}'
    const probe = JSON.parse(TEST_DATA.taxonomyCodesJson) as Record<string, unknown>
    expect(Object.hasOwn(probe, '__proto__')).toBe(true)
    await renderStats()
    expect(({} as Record<string, unknown>).polluted).toBeUndefined()
    expect(Object.prototype).not.toHaveProperty('polluted')
  })
})

/** Drop line and block comments. A source guard asserting a token is PRESENT
 *  must not be satisfied by a commented-out line -- the state a half-reverted
 *  change is in -- and one asserting a token is ABSENT must not be defeated by
 *  this file's own description of it. */
function stripComments(src: string): string {
  const OPEN = '/' + '*'
  const CLOSE = '*' + '/'
  const out: string[] = []
  let inBlock = false
  for (const line of src.split('\n')) {
    let l = line
    if (inBlock) {
      const c = l.indexOf(CLOSE)
      if (c === -1) continue
      inBlock = false
      l = l.slice(c + 2)
    }
    const o = l.indexOf(OPEN)
    if (o !== -1) {
      const c = l.indexOf(CLOSE, o + 2)
      if (c === -1) { inBlock = true; l = l.slice(0, o) }
      else l = l.slice(0, o) + l.slice(c + 2)
    }
    const lc = l.indexOf('//')
    if (lc !== -1) l = l.slice(0, lc)
    out.push(l)
  }
  return out.join('\n')
}
