// @vitest-environment jsdom
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react'

// Mock the map so maplibre never loads in jsdom.
vi.mock('./PredictMap', () => ({ PredictMap: () => <div data-testid="predict-map" /> }))
vi.mock('../lib/clipboard', () => ({ copyText: vi.fn().mockResolvedValue(true) }))

const getMock = vi.fn()
vi.mock('../lib/transport', () => ({ transport: { get: (path: string, params?: Record<string, string>) => getMock(path, params) } }))

const getCurrentLocationMock = vi.fn()
vi.mock('../lib/location', () => ({
  getCurrentLocation: () => getCurrentLocationMock(),
  describeLocationError: () => 'Location access was denied.',
}))

import { WeatherForecastPanel } from './WeatherForecastPanel'

const WEATHER_CURRENT = {
  resolution: 'current',
  formatted: '⛅\nScattered clouds\nTemperature: 61°F\nWeather generated by SnowRaven',
  summary: {
    emoji: '⛅', moon: '', description: 'Scattered clouds', isDaily: false,
    tempF: 61, highF: null, lowF: null, windDesc: 'Gentle breeze', windDir: 'W',
    cloudsPct: 40, humidityPct: 72, dewPointF: 52, sunrise: '5:08am', sunset: '8:31pm', isNight: false,
  },
  tz: 'America/Los_Angeles',
}

const TIDE_OK = {
  status: 'ok',
  formatted: '🌊\nPredicted\nWater level: 4.2 ft\nTide data from NOAA CO-OPS',
  body: '🌊\nPredicted\nWater level: 4.2 ft\nTide data from NOAA CO-OPS',
  station: { id: '9414816', name: 'Berkeley' },
  distanceMi: 1.2,
  reading: {
    source: 'predicted', levelMin: 4.2, levelMax: 5.1, trend: 'rising', turnedDuring: false,
    prevHL: { kind: 'low', v: 1.9, timeLocal: '2:02pm' },
    nextHL: { kind: 'high', v: 6.8, timeLocal: '8:14pm' },
    station: { id: '9414816', name: 'Berkeley' }, distanceMi: 1.2,
  },
}

beforeEach(() => { getMock.mockReset(); getCurrentLocationMock.mockReset() })
afterEach(cleanup)

describe('WeatherForecastPanel', () => {
  it('Current: shows live weather + tide summary', async () => {
    getCurrentLocationMock.mockResolvedValue({ lat: 37.87, lng: -122.30 })
    getMock.mockImplementation((p: string) =>
      p === '/weather/at' ? Promise.resolve(WEATHER_CURRENT)
        : p === '/tide/at' ? Promise.resolve(TIDE_OK)
          : Promise.reject(new Error('unexpected ' + p)))

    render(<WeatherForecastPanel />)
    fireEvent.click(screen.getByRole('button', { name: /current weather and tide/i }))

    await waitFor(() => expect(screen.getByText('61°F')).toBeTruthy())
    expect(screen.getByText('LIVE')).toBeTruthy()
    // "Rising ↑" only appears in the rendered tide summary (not in the canned block).
    expect(screen.getByText(/Rising/)).toBeTruthy()
  })

  it('Current denied: opens Predict with the location error', async () => {
    getCurrentLocationMock.mockRejectedValue({ code: 'permission-denied', platform: 'web' })

    render(<WeatherForecastPanel />)
    fireEvent.click(screen.getByRole('button', { name: /current weather and tide/i }))

    await waitFor(() => expect(screen.getByLabelText('Search for a place')).toBeTruthy())
    expect(screen.getByRole('alert').textContent).toMatch(/denied/i)
  })

  it('Predict beyond range: shows the no-forecast note, tide still shown', async () => {
    getCurrentLocationMock.mockRejectedValue({ code: 'unavailable' })
    getMock.mockImplementation((p: string) =>
      p === '/weather/at' ? Promise.resolve({ resolution: 'out-of-range', formatted: null, summary: null, tz: 'UTC' })
        : p === '/tide/at' ? Promise.resolve(TIDE_OK)
          : Promise.reject(new Error('unexpected ' + p)))

    render(<WeatherForecastPanel />)
    fireEvent.click(screen.getByRole('button', { name: /predict weather and tide/i }))

    await waitFor(() => expect(screen.getByLabelText(/Latitude/)).toBeTruthy())
    fireEvent.change(screen.getByLabelText(/Latitude/), { target: { value: '37.5' } })
    fireEvent.change(screen.getByLabelText(/Longitude/), { target: { value: '-122.5' } })
    fireEvent.change(screen.getByLabelText('Forecast date'), { target: { value: '2030-01-01' } })
    fireEvent.change(screen.getByLabelText('Forecast time'), { target: { value: '06:30' } })
    fireEvent.click(screen.getByRole('button', { name: 'Get forecast' }))

    await waitFor(() => expect(screen.getByText(/beyond the ~8-day window/i)).toBeTruthy())
    expect(screen.getByText('TIDE ONLY')).toBeTruthy()
    expect(screen.getByText(/Rising/)).toBeTruthy()
  })
})
