// The widget deep-link allowlist (ios-lifer-widgets FR-34, FR-35, NFR-04;
// QA-34, QA-35, QA-52; Stage 8 re-entry: the bird suffix). A link is one of
// fifteen exact view links, optionally followed by `&sp=<code>&loc=<locId>`.
// An inexact view part is rejected whole; a malformed bird suffix degrades to
// the view link.
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import {
  BIRD_SUFFIX_RE, buildWidgetLink, isLinkableBird, LINK_MAX_LENGTH, LINK_SCHEME, LOC_ID_RE, parseWidgetLink,
  WIDGET_LINKS, type WidgetLink,
} from './deepLink'
import { SPECIES_CODE_RE } from '../speciesCode'
import fixture from '../widgets/widgetRows.fixture.json'
import {
  LINK_BIRD, LINK_BIRD_BOUNDS, LINK_DEGRADED_SUFFIXES, LINK_REFUSED_PAIRS, LINK_REJECTED,
} from '../widgets/widgetRows.fixtureInputs'

const VALID = WIDGET_LINKS.map(v => buildWidgetLink(v))
const F = fixture.links

describe('the fifteen view links', () => {
  it('three lifers links with no media, twelve targets links with window then media', () => {
    expect(VALID).toHaveLength(15)
    expect(VALID.filter(u => u.includes('/lifers?'))).toEqual([
      'snowraven://map/lifers?window=day', 'snowraven://map/lifers?window=week', 'snowraven://map/lifers?window=all',
    ])
    const targets = VALID.filter(u => u.includes('/targets?'))
    expect(targets).toHaveLength(12)
    for (const u of targets) expect(u).toMatch(/^snowraven:\/\/map\/targets\?window=(day|week|all)&media=(photo|audio|video|any)$/)
    expect(new Set(VALID).size).toBe(15)
  })

  it('every one parses back to exactly the link that built it, with no bird', () => {
    for (const link of WIDGET_LINKS) expect(parseWidgetLink(buildWidgetLink(link))).toEqual(link)
  })

  it('the longest link (view plus the longest bird) fits the bound with no room for a payload', () => {
    const longestView = Math.max(...VALID.map(u => u.length))
    const longestViewLink = WIDGET_LINKS.find(v => buildWidgetLink(v).length === longestView)!
    const longestBird = buildWidgetLink({ ...longestViewLink, bird: { speciesCode: 'a'.repeat(16), locId: `L${'1'.repeat(15)}` } })
    expect(longestView).toBe(47)
    expect(longestBird.length).toBe(88)
    expect(LINK_MAX_LENGTH).toBe(96)
    expect(LINK_MAX_LENGTH).toBeGreaterThanOrEqual(longestBird.length)
    expect(LINK_MAX_LENGTH - longestBird.length).toBeLessThan(16)
    expect(LINK_SCHEME).toBe('snowraven')
  })

  it('a returned link is a copy: mutating it cannot change the next parse', () => {
    const a = parseWidgetLink('snowraven://map/lifers?window=day') as { window: string }
    a.window = 'all'
    expect(parseWidgetLink('snowraven://map/lifers?window=day')).toEqual({ view: 'lifers', window: 'day' })
  })
})

// The fixture's `expected` is generated by this parser, so these rows check each
// row against the family it was AUTHORED in (widgetRows.fixtureInputs.ts), which
// the generator cannot restate.
describe('the fixture link families (schema.md 7.2), each against its authored intent', () => {
  it('views: the fifteen, each parsing to its own view with no bird', () => {
    expect(F.views.map(r => r.raw)).toEqual(VALID)
    for (const r of F.views) expect(parseWidgetLink(r.raw)).toEqual(r.expected)
    for (const r of F.views) expect(r.expected).not.toHaveProperty('bird')
  })

  it('birds: every view link with a real-shaped bird, plus the bounds of both patterns, round trip', () => {
    expect(F.birds).toHaveLength(15 + LINK_BIRD_BOUNDS.length)
    for (const r of F.birds) {
      const got = parseWidgetLink(r.raw)
      expect(got, r.raw).toEqual(r.expected)
      expect(got!.bird, r.raw).toBeDefined()
      expect(buildWidgetLink(got!)).toBe(r.raw)
    }
    const carried = F.birds.map(r => r.expected!.bird)
    for (const b of [LINK_BIRD, ...LINK_BIRD_BOUNDS]) expect(carried).toContainEqual(b)
  })

  it('degraded: every malformed suffix drops the bird and keeps the view, never null', () => {
    expect(F.degraded).toHaveLength(2 * LINK_DEGRADED_SUFFIXES.length)
    for (const r of F.degraded) {
      const got = parseWidgetLink(r.raw)
      expect(got, JSON.stringify(r.raw)).toEqual(r.expected)
      expect(got, JSON.stringify(r.raw)).not.toBeNull()
      expect(got!.bird, JSON.stringify(r.raw)).toBeUndefined()
      expect(buildWidgetLink(got!), JSON.stringify(r.raw)).toBe(r.raw.slice(0, r.raw.indexOf('&sp=')))
    }
  })

  it('rejected: an inexact view part, or anything over the length bound, is refused whole', () => {
    expect(F.rejected.map(r => r.raw)).toEqual(LINK_REJECTED)
    for (const r of F.rejected) {
      expect(r.expected, JSON.stringify(r.raw)).toBeNull()
      expect(parseWidgetLink(r.raw), JSON.stringify(r.raw)).toBeNull()
    }
  })

  it('refused pairs: the builder throws rather than emit an out-of-pattern link', () => {
    expect(F.refusedPairs).toEqual(LINK_REFUSED_PAIRS)
    for (const bird of LINK_REFUSED_PAIRS) {
      expect(isLinkableBird(bird), JSON.stringify(bird)).toBe(false)
      expect(() => buildWidgetLink({ view: 'lifers', window: 'week', bird }), JSON.stringify(bird)).toThrow()
    }
  })
})

// Deterministic generators over every length in the two bounds (7.3 d).
const CODE_ALPHABET = 'abcdefghijklmnopqrstuvwxyz0123456789-'
function codesAtEveryLength(): string[] {
  const out: string[] = []
  for (let n = 2; n <= 16; n++) for (let k = 0; k < 4; k++) {
    let s = ''
    for (let i = 0; i < n; i++) s += CODE_ALPHABET[(i * 7 + k * 13 + n) % CODE_ALPHABET.length]
    out.push(s)
  }
  return out
}
function locIdsAtEveryLength(): string[] {
  const out: string[] = []
  for (let n = 1; n <= 15; n++) out.push(`L${'0123456789'.repeat(2).slice(n % 10, (n % 10) + n)}`)
  return out
}

describe('the structural rules (schema.md 7.3 d and e)', () => {
  it('(d) round trip: parse(build(view + bird)) is exactly (view + bird), for every view and every in-pattern bird', () => {
    const codes = codesAtEveryLength()
    const locs = locIdsAtEveryLength()
    let n = 0
    for (const v of WIDGET_LINKS) for (const speciesCode of codes) for (const locId of locs) {
      expect(SPECIES_CODE_RE.test(speciesCode) && LOC_ID_RE.test(locId)).toBe(true)
      const link: WidgetLink = { ...v, bird: { speciesCode, locId } }
      expect(parseWidgetLink(buildWidgetLink(link))).toEqual(link)
      n++
    }
    expect(n).toBe(15 * 60 * 15)
  })

  it('(e) degradation identity: a view link plus any suffix the pattern refuses parses exactly as the view link', () => {
    // Every single-position substitution, deletion and insertion of one valid
    // suffix over a wide alphabet, plus every prefix truncation of it.
    const valid = '&sp=norcar&loc=L123456'
    const alphabet = [...new Set(`${CODE_ALPHABET}ABCLMNZ&=#?%/ .\n\t١éL_:;+`)]
    const edits = new Set<string>()
    for (let i = 0; i <= valid.length; i++) {
      edits.add(valid.slice(0, i))
      for (const c of alphabet) {
        if (i < valid.length) edits.add(valid.slice(0, i) + c + valid.slice(i + 1))
        edits.add(valid.slice(0, i) + c + valid.slice(i))
      }
      if (i < valid.length) edits.add(valid.slice(0, i) + valid.slice(i + 1))
    }
    let refused = 0
    let accepted = 0
    for (const v of [WIDGET_LINKS[1]!, WIDGET_LINKS[14]!]) {
      const view = buildWidgetLink(v)
      for (const s of edits) {
        const raw = view + s
        const got = parseWidgetLink(raw)
        if (raw.indexOf('&sp=') !== view.length) {
          // The edit moved or removed the cut: then `v` is no longer the head,
          // and the result is null or the view itself (an empty tail).
          if (got !== null) expect(got).toEqual(parseWidgetLink(view))
          continue
        }
        if (BIRD_SUFFIX_RE.test(s)) {
          accepted++
          // The two-sided bound: anything this parser accepts as a bird is a pair
          // the Swift builder would have produced (both captures in pattern).
          expect(isLinkableBird(got!.bird!), JSON.stringify(s)).toBe(true)
          expect(buildWidgetLink(got!)).toBe(raw)
        } else {
          refused++
          expect(got, JSON.stringify(s)).toEqual(parseWidgetLink(view))
        }
      }
    }
    expect(edits.size).toBeGreaterThan(1500)
    expect(refused).toBeGreaterThan(1500)
    expect(accepted).toBeGreaterThan(50)
  })
})

describe('everything whose view part is not exact is rejected whole', () => {
  const HOSTILE: unknown[] = [
    'snowraven://map/hotspots?window=day',                // unknown path
    'snowraven://map/lifers?window=month',               // unknown window
    'snowraven://map/lifers',                            // missing window
    'snowraven://map/targets?window=day&media=both',     // superseded media value
    'snowraven://map/targets?window=day&media=all',      // superseded media value
    'snowraven://map/targets?window=day',                // targets with no media
    'snowraven://map/lifers?window=day&media=photo',     // media on the lifers path
    'snowraven://map/lifers?window=day&x=1',             // extra parameter
    'snowraven://map/targets?media=photo&window=day',    // reordered
    'snowraven://map/lifers?window=day#top',             // fragment
    'snowraven://map/lifers/?window=day',                // trailing slash
    'SNOWRAVEN://map/lifers?window=day',                 // case
    'snowraven://map/lifers?window=Day',
    'snowraven://map/lifers?window=%64ay',               // percent-encoding
    'snowraven://map%2Flifers?window=day',               // encoded slash
    ' snowraven://map/lifers?window=day',                // whitespace
    'snowraven://map/lifers?window=day\n',
    'snowraven://map/lifers?window=day\u0000',           // control character
    'javascript:alert(1)//snowraven://map/lifers?window=day',
    'https://example.com/?u=snowraven://map/lifers?window=day',
    'snowraven://map/lifers?window=day' + 'x'.repeat(LINK_MAX_LENGTH),
    'constructor', '__proto__', 'toString', 'hasOwnProperty', '',
    'constructor&sp=norcar&loc=L1', '__proto__&sp=norcar&loc=L1',
    null, undefined, 42, {}, ['snowraven://map/lifers?window=day'],
  ]
  it.each(HOSTILE.map(h => [JSON.stringify(h) ?? String(h), h]))('%s', (_label, raw) => {
    expect(parseWidgetLink(raw)).toBeNull()
  })

  it('the length gate runs before the cut and the lookup (read from source, comments stripped)', () => {
    const src = readFileSync(new URL('./deepLink.ts', import.meta.url), 'utf8')
      .split('\n').filter(l => !/^\s*\/\//.test(l)).join('\n')
    const body = src.slice(src.indexOf('export function parseWidgetLink'))
    const gate = body.indexOf('raw.length > LINK_MAX_LENGTH')
    const cut = body.indexOf("raw.indexOf('&sp=')")
    const lookup = body.indexOf('Object.hasOwn(TABLE, head)')
    expect(gate).toBeGreaterThan(-1)
    expect(cut).toBeGreaterThan(gate)
    expect(lookup).toBeGreaterThan(cut)
    expect(src).toContain('const TABLE: Record<string, ViewLink> = Object.create(null)')
    // No URL parsing or decoding, and the one pattern is the anchored suffix.
    expect(src).not.toMatch(/new URL\(|decodeURI|URLSearchParams|\.match\(/)
    expect(src.match(/new RegExp\(/g)).toHaveLength(1)
  })

  it('the suffix pattern is anchored, fixed-class and bounded, and derived from the two id patterns', () => {
    expect(BIRD_SUFFIX_RE.source).toBe('^&sp=([a-z0-9-]{2,16})&loc=(L[0-9]{1,15})$')
    expect(BIRD_SUFFIX_RE.source).toContain(SPECIES_CODE_RE.source.slice(1, -1))
    expect(BIRD_SUFFIX_RE.source).toContain(LOC_ID_RE.source.slice(1, -1))
    expect(BIRD_SUFFIX_RE.flags).toBe('')
  })

  it('10,000 generated hostile inputs up to 200k characters are all rejected, in bounded time', () => {
    let seed = 7
    const rand = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed }
    const base = 'snowraven://map/targets?window=week&media=photo&sp=norcar&loc=L1'
    const start = performance.now()
    for (let i = 0; i < 10_000; i++) {
      const len = rand() % 200_000
      const s = (i % 2 === 0 ? base : '') + String.fromCharCode(32 + (rand() % 90)).repeat(len > 64 ? len : 64)
      expect(parseWidgetLink(s)).toBeNull()
    }
    // The gate makes each rejection O(1); 10k rejections well under a second
    // is generous headroom, and an unbounded scan over 1e9 characters is not.
    expect(performance.now() - start).toBeLessThan(5_000)
  }, 60_000)

  it('the suffix pattern has no super-linear case: a 96-character adversarial tail is refused in constant work', () => {
    const view = 'snowraven://map/lifers?window=day'
    for (const tail of [
      '&sp=' + 'a'.repeat(16) + 'a'.repeat(LINK_MAX_LENGTH - view.length - 20),
      '&sp=' + 'a-'.repeat(8) + '&loc=L' + '1'.repeat(LINK_MAX_LENGTH - view.length - 26) + 'x',
      '&sp=' + '&sp='.repeat(Math.floor((LINK_MAX_LENGTH - view.length - 4) / 4)),
    ]) {
      const raw = (view + tail).slice(0, LINK_MAX_LENGTH)
      expect(raw.length).toBeLessThanOrEqual(LINK_MAX_LENGTH)
      expect(parseWidgetLink(raw)).toEqual({ view: 'lifers', window: 'day' })
    }
  })
})
