// The widget deep-link allowlist (ios-lifer-widgets FR-34, FR-35, NFR-04;
// QA-34, QA-35, QA-52; Stage 8 re-entry: the bird suffix). A link is one of
// fifteen exact view links, optionally followed by `&sp=<code>&loc=<locId>`.
// An inexact view part is rejected whole; a malformed bird suffix degrades to
// the view link.
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import {
  ALERT_LINK_PATTERN, ALERT_LINK_RE, BIRD_SUFFIX_RE, buildWidgetLink, FROM_DEFAULT_MARKER, isLinkableBird, LINK_MAX_LENGTH,
  LINK_SCHEME, LOC_ID_RE, parseWidgetLink, WIDGET_LINKS, type WidgetLink,
} from './deepLink'
import { SPECIES_CODE_RE } from '../speciesCode'
import fixture from '../widgets/widgetRows.fixture.json'
import {
  LINK_BIRD, LINK_BIRD_BOUNDS, LINK_DEGRADED_SUFFIXES, LINK_REFUSED_PAIRS, LINK_REJECTED,
} from '../widgets/widgetRows.fixtureInputs'

const VALID = WIDGET_LINKS.map(v => buildWidgetLink(v))
const F = fixture.links

describe('the fifteen view links', () => {
  it('three lifers links with no media, twelve targets links with window then media', () => {
    expect(VALID).toHaveLength(15)
    expect(VALID.filter(u => u.includes('/lifers?'))).toEqual([
      'snowraven://map/lifers?window=day', 'snowraven://map/lifers?window=week', 'snowraven://map/lifers?window=all',
    ])
    const targets = VALID.filter(u => u.includes('/targets?'))
    expect(targets).toHaveLength(12)
    for (const u of targets) expect(u).toMatch(/^snowraven:\/\/map\/targets\?window=(day|week|all)&media=(photo|audio|video|any)$/)
    expect(new Set(VALID).size).toBe(15)
  })

  it('every one parses back to exactly the link that built it, with no bird', () => {
    for (const link of WIDGET_LINKS) expect(parseWidgetLink(buildWidgetLink(link))).toEqual(link)
  })

  it('the longest link (view plus the longest bird) fits the bound with no room for a payload', () => {
    const longestView = Math.max(...VALID.map(u => u.length))
    const longestViewLink = WIDGET_LINKS.find(v => buildWidgetLink(v).length === longestView)!
    const longestBird = buildWidgetLink({ ...longestViewLink, bird: { speciesCode: 'a'.repeat(16), locId: `L${'1'.repeat(15)}` } })
    expect(longestView).toBe(47)
    expect(longestBird.length).toBe(88)
    // widget-measure-from-choice: the marker adds 13, still under the alert form.
    const longestMarked = buildWidgetLink({ ...longestViewLink, bird: { speciesCode: 'a'.repeat(16), locId: `L${'1'.repeat(15)}` }, fromDefault: true })
    expect(longestMarked.length).toBe(101)
    // ios-alerts (schema.md 5.1): the bound is set by the longest ALERT link,
    // 117 characters, and leaves no room for a payload beyond it.
    const longestAlert = buildWidgetLink({
      view: 'lifers', window: 'day', point: { lat: -12.34567, lng: -123.45678 }, radiusMi: 25,
      bird: { speciesCode: 'a'.repeat(16), locId: `L${'1'.repeat(15)}` }, show: 'all',
    })
    expect(longestAlert.length).toBe(117)
    expect(LINK_MAX_LENGTH).toBe(128)
    expect(LINK_MAX_LENGTH).toBeGreaterThanOrEqual(longestAlert.length)
    expect(LINK_MAX_LENGTH - longestAlert.length).toBeLessThan(16)
    expect(LINK_MAX_LENGTH).toBeGreaterThanOrEqual(longestBird.length)
    expect(LINK_SCHEME).toBe('snowraven')
  })

  it('a returned link is a copy: mutating it cannot change the next parse', () => {
    const a = parseWidgetLink('snowraven://map/lifers?window=day') as { window: string }
    a.window = 'all'
    expect(parseWidgetLink('snowraven://map/lifers?window=day')).toEqual({ view: 'lifers', window: 'day' })
  })
})

// The fixture's `expected` is generated by this parser, so these rows check each
// row against the family it was AUTHORED in (widgetRows.fixtureInputs.ts), which
// the generator cannot restate.
describe('the fixture link families (schema.md 7.2), each against its authored intent', () => {
  it('views: the fifteen, each parsing to its own view with no bird', () => {
    expect(F.views.map(r => r.raw)).toEqual(VALID)
    for (const r of F.views) expect(parseWidgetLink(r.raw)).toEqual(r.expected)
    for (const r of F.views) expect(r.expected).not.toHaveProperty('bird')
  })

  it('birds: every view link with a real-shaped bird, plus the bounds of both patterns, round trip', () => {
    expect(F.birds).toHaveLength(15 + LINK_BIRD_BOUNDS.length)
    for (const r of F.birds) {
      const got = parseWidgetLink(r.raw)
      expect(got, r.raw).toEqual(r.expected)
      expect(got!.bird, r.raw).toBeDefined()
      expect(buildWidgetLink(got!)).toBe(r.raw)
    }
    const carried = F.birds.map(r => r.expected!.bird)
    for (const b of [LINK_BIRD, ...LINK_BIRD_BOUNDS]) expect(carried).toContainEqual(b)
  })

  it('degraded: every malformed suffix drops the bird and keeps the view, never null', () => {
    expect(F.degraded).toHaveLength(2 * LINK_DEGRADED_SUFFIXES.length)
    for (const r of F.degraded) {
      const got = parseWidgetLink(r.raw)
      expect(got, JSON.stringify(r.raw)).toEqual(r.expected)
      expect(got, JSON.stringify(r.raw)).not.toBeNull()
      expect(got!.bird, JSON.stringify(r.raw)).toBeUndefined()
      expect(buildWidgetLink(got!), JSON.stringify(r.raw)).toBe(r.raw.slice(0, r.raw.indexOf('&sp=')))
    }
  })

  it('rejected: an inexact view part, or anything over the length bound, is refused whole', () => {
    expect(F.rejected.map(r => r.raw)).toEqual(LINK_REJECTED)
    for (const r of F.rejected) {
      expect(r.expected, JSON.stringify(r.raw)).toBeNull()
      expect(parseWidgetLink(r.raw), JSON.stringify(r.raw)).toBeNull()
    }
  })

  it('fromDefault: every view and bird row again with the marker, round trip, and the marker always last', () => {
    expect(F.fromDefault).toHaveLength(F.views.length + F.birds.length)
    expect(F.fromDefault.map(r => r.raw)).toEqual([...F.views, ...F.birds].map(r => r.raw + FROM_DEFAULT_MARKER))
    for (const r of F.fromDefault) {
      const got = parseWidgetLink(r.raw)
      expect(got, r.raw).toEqual(r.expected)
      expect(got!.fromDefault, r.raw).toBe(true)
      expect(buildWidgetLink(got!)).toBe(r.raw)
    }
    // No unmarked row carries the flag.
    for (const r of [...F.views, ...F.birds, ...F.degraded]) expect(r.expected).not.toHaveProperty('fromDefault')
  })

  it('refused pairs: the builder throws rather than emit an out-of-pattern link', () => {
    expect(F.refusedPairs).toEqual(LINK_REFUSED_PAIRS)
    for (const bird of LINK_REFUSED_PAIRS) {
      expect(isLinkableBird(bird), JSON.stringify(bird)).toBe(false)
      expect(() => buildWidgetLink({ view: 'lifers', window: 'week', bird }), JSON.stringify(bird)).toThrow()
    }
  })
})

// Deterministic generators over every length in the two bounds (7.3 d).
const CODE_ALPHABET = 'abcdefghijklmnopqrstuvwxyz0123456789-'
function codesAtEveryLength(): string[] {
  const out: string[] = []
  for (let n = 2; n <= 16; n++) for (let k = 0; k < 4; k++) {
    let s = ''
    for (let i = 0; i < n; i++) s += CODE_ALPHABET[(i * 7 + k * 13 + n) % CODE_ALPHABET.length]
    out.push(s)
  }
  return out
}
function locIdsAtEveryLength(): string[] {
  const out: string[] = []
  for (let n = 1; n <= 15; n++) out.push(`L${'0123456789'.repeat(2).slice(n % 10, (n % 10) + n)}`)
  return out
}

describe('the structural rules (schema.md 7.3 d and e)', () => {
  it('(d) round trip: parse(build(view + bird)) is exactly (view + bird), for every view and every in-pattern bird', () => {
    const codes = codesAtEveryLength()
    const locs = locIdsAtEveryLength()
    let n = 0
    for (const v of WIDGET_LINKS) for (const speciesCode of codes) for (const locId of locs) {
      expect(SPECIES_CODE_RE.test(speciesCode) && LOC_ID_RE.test(locId)).toBe(true)
      const link: WidgetLink = { ...v, bird: { speciesCode, locId } }
      expect(parseWidgetLink(buildWidgetLink(link))).toEqual(link)
      n++
    }
    expect(n).toBe(15 * 60 * 15)
  })

  it('(e) degradation identity: a view link plus any suffix the pattern refuses parses exactly as the view link', () => {
    // Every single-position substitution, deletion and insertion of one valid
    // suffix over a wide alphabet, plus every prefix truncation of it.
    const valid = '&sp=norcar&loc=L123456'
    const alphabet = [...new Set(`${CODE_ALPHABET}ABCLMNZ&=#?%/ .\n\t١éL_:;+`)]
    const edits = new Set<string>()
    for (let i = 0; i <= valid.length; i++) {
      edits.add(valid.slice(0, i))
      for (const c of alphabet) {
        if (i < valid.length) edits.add(valid.slice(0, i) + c + valid.slice(i + 1))
        edits.add(valid.slice(0, i) + c + valid.slice(i))
      }
      if (i < valid.length) edits.add(valid.slice(0, i) + valid.slice(i + 1))
    }
    let refused = 0
    let accepted = 0
    for (const v of [WIDGET_LINKS[1]!, WIDGET_LINKS[14]!]) {
      const view = buildWidgetLink(v)
      for (const s of edits) {
        const raw = view + s
        const got = parseWidgetLink(raw)
        if (raw.indexOf('&sp=') !== view.length) {
          // The edit moved or removed the cut: then `v` is no longer the head,
          // and the result is null or the view itself (an empty tail).
          if (got !== null) expect(got).toEqual(parseWidgetLink(view))
          continue
        }
        if (BIRD_SUFFIX_RE.test(s)) {
          accepted++
          // The two-sided bound: anything this parser accepts as a bird is a pair
          // the Swift builder would have produced (both captures in pattern).
          expect(isLinkableBird(got!.bird!), JSON.stringify(s)).toBe(true)
          expect(buildWidgetLink(got!)).toBe(raw)
        } else {
          refused++
          expect(got, JSON.stringify(s)).toEqual(parseWidgetLink(view))
        }
      }
    }
    expect(edits.size).toBeGreaterThan(1500)
    expect(refused).toBeGreaterThan(1500)
    expect(accepted).toBeGreaterThan(50)
  })

  // widget-measure-from-choice. The marker is independent of everything before
  // it, which is the claim this derives STRUCTURALLY rather than restating: a
  // string with the marker appended parses exactly as the same string without
  // it, plus `fromDefault`, or is rejected exactly when that one is. Run over
  // the (e) corpus, every fixture family and the hostile list below.
  it('(f) marker identity: parse(x + marker) is parse(x) plus fromDefault, for every non-alert x', () => {
    const valid = '&sp=norcar&loc=L123456'
    const alphabet = [...new Set(`${CODE_ALPHABET}ABCLMNZ&=#?%/ .\n\t١éL_:;+`)]
    const xs = new Set<string>()
    for (const v of [WIDGET_LINKS[1]!, WIDGET_LINKS[14]!]) {
      const view = buildWidgetLink(v)
      for (let i = 0; i <= valid.length; i++) {
        xs.add(view + valid.slice(0, i))
        for (const c of alphabet) if (i < valid.length) xs.add(view + valid.slice(0, i) + c + valid.slice(i + 1))
      }
    }
    for (const r of [...F.views, ...F.birds, ...F.degraded, ...F.rejected]) xs.add(r.raw)
    let marked = 0
    let rejected = 0
    for (const x of xs) {
      if (ALERT_LINK_RE.test(x)) continue
      const plain = parseWidgetLink(x)
      const got = parseWidgetLink(x + FROM_DEFAULT_MARKER)
      if (plain === null || x.length + FROM_DEFAULT_MARKER.length > LINK_MAX_LENGTH) {
        if (plain === null) { expect(got, JSON.stringify(x)).toBeNull(); rejected++ }
        continue
      }
      expect(got, JSON.stringify(x)).toEqual({ ...plain, fromDefault: true })
      marked++
    }
    expect(marked).toBeGreaterThan(500)
    expect(rejected).toBeGreaterThan(20)
  })

  it('the marker is refused on an alert link by the builder, and absent from every alert parse', () => {
    const alert: WidgetLink = {
      view: 'lifers', window: 'day', point: { lat: 1, lng: 1 }, radiusMi: 5, bird: { speciesCode: 'ruff', locId: 'L1' }, show: 'all',
    }
    expect(() => buildWidgetLink({ ...alert, fromDefault: true })).toThrow()
    expect(parseWidgetLink(buildWidgetLink(alert))).not.toHaveProperty('fromDefault')
    expect(parseWidgetLink(buildWidgetLink(alert) + FROM_DEFAULT_MARKER)).toBeNull()
  })
})

describe('everything whose view part is not exact is rejected whole', () => {
  const HOSTILE: unknown[] = [
    'snowraven://map/hotspots?window=day',                // unknown path
    'snowraven://map/lifers?window=month',               // unknown window
    'snowraven://map/lifers',                            // missing window
    'snowraven://map/targets?window=day&media=both',     // superseded media value
    'snowraven://map/targets?window=day&media=all',      // superseded media value
    'snowraven://map/targets?window=day',                // targets with no media
    'snowraven://map/lifers?window=day&media=photo',     // media on the lifers path
    'snowraven://map/lifers?window=day&x=1',             // extra parameter
    'snowraven://map/targets?media=photo&window=day',    // reordered
    'snowraven://map/lifers?window=day#top',             // fragment
    'snowraven://map/lifers/?window=day',                // trailing slash
    'SNOWRAVEN://map/lifers?window=day',                 // case
    'snowraven://map/lifers?window=Day',
    'snowraven://map/lifers?window=%64ay',               // percent-encoding
    'snowraven://map%2Flifers?window=day',               // encoded slash
    ' snowraven://map/lifers?window=day',                // whitespace
    'snowraven://map/lifers?window=day\n',
    'snowraven://map/lifers?window=day\u0000',           // control character
    'javascript:alert(1)//snowraven://map/lifers?window=day',
    'https://example.com/?u=snowraven://map/lifers?window=day',
    'snowraven://map/lifers?window=day' + 'x'.repeat(LINK_MAX_LENGTH),
    'constructor', '__proto__', 'toString', 'hasOwnProperty', '',
    'constructor&sp=norcar&loc=L1', '__proto__&sp=norcar&loc=L1',
    null, undefined, 42, {}, ['snowraven://map/lifers?window=day'],
  ]
  it.each(HOSTILE.map(h => [JSON.stringify(h) ?? String(h), h]))('%s', (_label, raw) => {
    expect(parseWidgetLink(raw)).toBeNull()
  })

  it('the length gate runs before the cut and the lookup (read from source, comments stripped)', () => {
    const src = readFileSync(new URL('./deepLink.ts', import.meta.url), 'utf8')
      .split('\n').filter(l => !/^\s*\/\//.test(l)).join('\n')
    const body = src.slice(src.indexOf('export function parseWidgetLink'))
    const gate = body.indexOf('raw.length > LINK_MAX_LENGTH')
    const alert = body.indexOf('ALERT_LINK_RE.exec(raw)')
    const marker = body.indexOf('raw.endsWith(FROM_DEFAULT_MARKER)')
    const cut = body.indexOf("rest.indexOf('&sp=')")
    const lookup = body.indexOf('Object.hasOwn(TABLE, head)')
    expect(gate).toBeGreaterThan(-1)
    // ios-alerts: the alert form is tried after the gate and before the cut;
    // widget-measure-from-choice: the marker is taken off after the alert form
    // and before the cut, so the cut and the lookup see exactly the shipped grammar.
    expect(alert).toBeGreaterThan(gate)
    expect(marker).toBeGreaterThan(alert)
    expect(cut).toBeGreaterThan(marker)
    expect(lookup).toBeGreaterThan(cut)
    expect(src).toContain('const TABLE: Record<string, ViewLink> = Object.create(null)')
    // No URL parsing or decoding, and the one pattern is the anchored suffix.
    expect(src).not.toMatch(/new URL\(|decodeURI|URLSearchParams|\.match\(/)
    // Two patterns: the anchored bird suffix, and (ios-alerts) the anchored
    // alert form, built from its one exported source string.
    expect(src.match(/new RegExp\(/g)).toHaveLength(2)
    expect(src).toContain('export const ALERT_LINK_RE = new RegExp(ALERT_LINK_PATTERN)')
  })

  it('the suffix pattern is anchored, fixed-class and bounded, and derived from the two id patterns', () => {
    expect(BIRD_SUFFIX_RE.source).toBe('^&sp=([a-z0-9-]{2,16})&loc=(L[0-9]{1,15})$')
    expect(BIRD_SUFFIX_RE.source).toContain(SPECIES_CODE_RE.source.slice(1, -1))
    expect(BIRD_SUFFIX_RE.source).toContain(LOC_ID_RE.source.slice(1, -1))
    expect(BIRD_SUFFIX_RE.flags).toBe('')
  })

  it('10,000 generated hostile inputs up to 200k characters are all rejected, in bounded time', () => {
    let seed = 7
    const rand = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed }
    const base = 'snowraven://map/targets?window=week&media=photo&sp=norcar&loc=L1'
    const start = performance.now()
    for (let i = 0; i < 10_000; i++) {
      const len = rand() % 200_000
      // At least 65 characters of tail, so every input is past the 128 bound.
      const s = (i % 2 === 0 ? base : '') + String.fromCharCode(32 + (rand() % 90)).repeat(len > 65 ? len : 65)
      expect(parseWidgetLink(s)).toBeNull()
    }
    // The gate makes each rejection O(1); 10k rejections well under a second
    // is generous headroom, and an unbounded scan over 1e9 characters is not.
    expect(performance.now() - start).toBeLessThan(5_000)
  }, 60_000)

  it('the suffix pattern has no super-linear case: a 96-character adversarial tail is refused in constant work', () => {
    const view = 'snowraven://map/lifers?window=day'
    for (const tail of [
      '&sp=' + 'a'.repeat(16) + 'a'.repeat(LINK_MAX_LENGTH - view.length - 20),
      '&sp=' + 'a-'.repeat(8) + '&loc=L' + '1'.repeat(LINK_MAX_LENGTH - view.length - 26) + 'x',
      '&sp=' + '&sp='.repeat(Math.floor((LINK_MAX_LENGTH - view.length - 4) / 4)),
    ]) {
      const raw = (view + tail).slice(0, LINK_MAX_LENGTH)
      expect(raw.length).toBeLessThanOrEqual(LINK_MAX_LENGTH)
      expect(parseWidgetLink(raw)).toEqual({ view: 'lifers', window: 'day' })
    }
  })
})


// ── ios-alerts (schema.md 5.1 and 5.2): the one anchored alert form ──────────
describe('the alert link form (ios-alerts)', () => {
  const HEAD = 'snowraven://map/lifers?window=day'
  const at = (lat: string, lng: string, r: string, show = 'all', sp = 'ruff', loc = 'L1000001') =>
    `${HEAD}&lat=${lat}&lng=${lng}&r=${r}&sp=${sp}&loc=${loc}&show=${show}`

  it('valid at every bound, both show modes, and the shortest and longest instances', () => {
    const rows: [string, string, string][] = [
      ['-90', '0', '1'], ['90', '0', '25'], ['0.00001', '-180', '5'], ['0', '180', '25'],
      ['38.54490', '-121.74050', '25'], ['-12.34567', '-123.45678', '1'],
    ]
    for (const [lat, lng, r] of rows) {
      for (const show of ['all', 'one'] as const) {
        const got = parseWidgetLink(at(lat, lng, r, show))
        expect(got, at(lat, lng, r, show)).toEqual({
          view: 'lifers', window: 'day', point: { lat: Number(lat), lng: Number(lng) }, radiusMi: Number(r),
          bird: { speciesCode: 'ruff', locId: 'L1000001' }, show,
        })
      }
    }
    const shortest = at('0', '0', '1', 'one', 'ab', 'L1')
    expect(parseWidgetLink(shortest)).not.toBeNull()
    const longest = at('-12.34567', '-123.45678', '25', 'all', 'a'.repeat(16), `L${'1'.repeat(15)}`)
    expect(longest.length).toBe(117)
    expect(parseWidgetLink(longest)).not.toBeNull()
  })

  it('rejected WHOLE (never degraded): out-of-range numbers, bad shapes, reordering, extras, over-length', () => {
    const rejected = [
      at('0', '0', '0'), at('0', '0', '26'), at('0', '0', '100'), at('91', '0', '5'), at('0', '-181', '5'),
      at('0.123456', '0', '5'), at('+1', '0', '5'), at('0', '0', '5', 'some'), at('0', '0', '5', 'ALL'),
      at('0', '0', '5', 'all', 'Ruff'), at('0', '0', '5', 'all', 'ruff', ''),
      `${HEAD}&lng=0&lat=0&r=5&sp=ruff&loc=L1&show=all`,
      `${at('0', '0', '5')}&x=1`, `${at('0', '0', '5')}#frag`, `${at('0', '0', '5')}\n`,
      `${HEAD}&lat=0&lng=0&r=5&sp=ruff&loc=L1`, // no show: not the alert form, and not a view link
      at('1.', '0', '5'), at('.5', '0', '5'), at('1e1', '0', '5'), at('0x1', '0', '5'),
      `${HEAD.replace('lifers', 'targets')}&lat=0&lng=0&r=5&sp=ruff&loc=L1&show=all`,
      `${HEAD.replace('day', 'week')}&lat=0&lng=0&r=5&sp=ruff&loc=L1&show=all`,
      (at('0', '0', '5') + 'x'.repeat(128)).slice(0, LINK_MAX_LENGTH + 1),
    ]
    for (const raw of rejected) expect(parseWidgetLink(raw), JSON.stringify(raw)).toBeNull()
  })

  it('negative zero reads as zero, so the two builders agree on the value', () => {
    const got = parseWidgetLink(at('-0.00000', '-0', '5'))
    expect(Object.is(got!.point!.lat, 0)).toBe(true)
    expect(Object.is(got!.point!.lng, 0)).toBe(true)
  })

  it('the builder refuses what the parser would reject, and round-trips over generated points and radii', () => {
    const base: WidgetLink = {
      view: 'lifers', window: 'day', point: { lat: 1, lng: 1 }, radiusMi: 5, bird: { speciesCode: 'ruff', locId: 'L1' }, show: 'all',
    }
    expect(() => buildWidgetLink({ ...base, radiusMi: 26 })).toThrow()
    expect(() => buildWidgetLink({ ...base, radiusMi: 2.5 })).toThrow()
    expect(() => buildWidgetLink({ ...base, point: { lat: 91, lng: 0 } })).toThrow()
    expect(() => buildWidgetLink({ ...base, bird: { speciesCode: 'Ruff', locId: 'L1' } })).toThrow()
    expect(() => buildWidgetLink({ ...base, show: undefined })).toThrow()
    expect(() => buildWidgetLink({ ...base, view: 'targets', media: 'any' } as WidgetLink)).toThrow()
    let seed = 11
    const rand = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff }
    for (let i = 0; i < 2000; i++) {
      const lat = Number((rand() * 180 - 90).toFixed(5)) || 0
      const lng = Number((rand() * 360 - 180).toFixed(5)) || 0
      const radiusMi = 1 + Math.floor(rand() * 25)
      const link: WidgetLink = { ...base, point: { lat, lng }, radiusMi, show: i % 2 ? 'one' : 'all' }
      const raw = buildWidgetLink(link)
      expect(raw.length).toBeLessThanOrEqual(LINK_MAX_LENGTH)
      expect(parseWidgetLink(raw)).toEqual(link)
    }
  })

  it('the pattern is one anchored literal: fixed classes, bounded quantifiers, the id classes spelled as the id patterns', () => {
    expect(ALERT_LINK_RE.source).toBe(new RegExp(ALERT_LINK_PATTERN).source)
    expect(ALERT_LINK_PATTERN.startsWith('^snowraven://map/lifers\\?window=day&')).toBe(true)
    expect(ALERT_LINK_PATTERN.endsWith('&show=(all|one)$')).toBe(true)
    expect(ALERT_LINK_PATTERN).toContain(`&sp=(${SPECIES_CODE_RE.source.slice(1, -1)})`)
    expect(ALERT_LINK_PATTERN).toContain(`&loc=(${LOC_ID_RE.source.slice(1, -1)})`)
    expect(ALERT_LINK_PATTERN).not.toMatch(/[*+](?![^{]*\})/)
    expect(ALERT_LINK_RE.flags).toBe('')
  })

  it('a 128-character adversarial near-miss is refused in linear time', () => {
    const tails = [
      '&lat=' + '1'.repeat(LINK_MAX_LENGTH), '&lat=1.' + '1'.repeat(LINK_MAX_LENGTH),
      '&lat=0&lng=0&r=5&sp=' + 'a-'.repeat(LINK_MAX_LENGTH), '&lat=0&lng=0&r=5&sp=ruff&loc=L' + '1'.repeat(LINK_MAX_LENGTH),
    ]
    const start = performance.now()
    for (let i = 0; i < 20_000; i++) {
      for (const t of tails) {
        const raw = (HEAD + t).slice(0, LINK_MAX_LENGTH)
        ALERT_LINK_RE.exec(raw)
      }
    }
    // 80,000 anchored scans over at most 128 characters: linear work, so a
    // generous ceiling; a backtracking blowup would be orders slower.
    expect(performance.now() - start).toBeLessThan(5_000)
  })
})
