// Builds the widget parity fixture document from the hand-authored inputs and
// the SHIPPED TypeScript twin (ios-lifer-widgets, schema.md section 7). Used by
// the env-gated generator, which writes it, and by widgetRows.parity.test.ts,
// which re-builds it on every run and asserts the tracked file equals it.
// Not shipped code: nothing in the app imports this module.

import retryFixture from '../hotspotActivity.fixture.json'
import { parseRetryAfterSeconds } from '../rateLimit'
import { buildWidgetLink, parseWidgetLink, WIDGET_LINKS, type ViewLink, type WidgetLink } from '../links/deepLink'
import {
  buildHandover, isValidHandoverName, HANDOVER_MAX_BYTES, MAX_KEY_LEN, MAX_NAME_UNITS, MAX_SET_ENTRIES,
} from './widgetHandover'
import {
  buildRecentObsUrl, buildWidgetRows, daysBetween, distanceMiles, FAMILY_ROWS, foldName, formatMiles,
  inWindow, localCivilDate, MEDIA_NEEDS, needsPhrase, parseObsDateStrict, recencyLabel, reduceWidgetRecords,
  RECORD_MAX_STRING, WIDGET_BACK_DAYS, WIDGET_DIST_KM, WIDGET_RADIUS_MI,
  type MediaNeed, type WidgetMedia, type WidgetWindow,
} from './widgetRows'
import {
  APP_VERSION, BODY, DATE_SEEDS, DISTANCE_PAIRS, DST_NOW_ISO, DST_OBS, FOLD_INPUTS, FORMAT_MILES, ML_ROWS,
  NOW_ISO, OBSERVATIONS, RECENCY_DAYS, REFERENCE, TZ,
  LINK_BIRD, LINK_BIRD_BOUNDS, LINK_DEGRADE_BASES, LINK_DEGRADED_SUFFIXES, LINK_REFUSED_PAIRS, LINK_REJECTED,
} from './widgetRows.fixtureInputs'

export const FIXTURE_KEY = 'fixtureKey123'
export const FIXTURE_DEFAULT_LOCATION = { lat: 37.3, lng: -121.9, dist: 5 }
const WINDOWS: WidgetWindow[] = ['day', 'week', 'all']
const MEDIA: WidgetMedia[] = ['photo', 'audio', 'video', 'any']

export function fixtureHandover() {
  const doc = buildHandover({
    nowMs: Date.parse(NOW_ISO),
    appVersion: APP_VERSION,
    ebirdKey: FIXTURE_KEY,
    observations: OBSERVATIONS,
    mlRows: ML_ROWS,
    mapDefaults: FIXTURE_DEFAULT_LOCATION,
  })
  if (!doc) throw new Error('fixture hand-over refused by its own builder')
  return doc
}

export function buildWidgetFixture() {
  const nowMs = Date.parse(NOW_ISO)
  const handover = fixtureHandover()
  const records = reduceWidgetRecords(BODY)
  if (!records) throw new Error('fixture body is not an array')

  const rows = (kind: 'lifers' | 'targets', window: WidgetWindow, media: WidgetMedia) =>
    buildWidgetRows({ records, handover, kind, window, media, reference: REFERENCE, nowMs, tz: TZ })

  const lifers = Object.fromEntries(WINDOWS.map(w => [w, rows('lifers', w, 'any')]))
  const targets = Object.fromEntries(MEDIA.map(m => [m, Object.fromEntries(WINDOWS.map(w => [w, rows('targets', w, m)]))]))

  const dstNow = localCivilDate(Date.parse(DST_NOW_ISO), TZ)
  const subsets: MediaNeed[][] = []
  for (let mask = 1; mask < 8; mask++) subsets.push(MEDIA_NEEDS.filter((_, i) => mask & (1 << i)))

  return {
    comment: 'GENERATED by widgetRows.fixtureGen.test.ts from widgetRows.fixtureInputs.ts. Do not edit by hand. Read by widgetRows.parity.test.ts (vitest, CI) and snowraven_widgetsTests (XCTest, release machine).',
    tz: TZ,
    nowIso: NOW_ISO,
    reference: REFERENCE,
    request: { radiusMi: WIDGET_RADIUS_MI, distKm: WIDGET_DIST_KM, backDays: WIDGET_BACK_DAYS, url: buildRecentObsUrl(REFERENCE.lat, REFERENCE.lng) },
    families: FAMILY_ROWS,
    constants: {
      handoverMaxBytes: HANDOVER_MAX_BYTES, maxSetEntries: MAX_SET_ENTRIES, maxNameUnits: MAX_NAME_UNITS,
      maxKeyLen: MAX_KEY_LEN, recordMaxString: RECORD_MAX_STRING,
    },
    observations: OBSERVATIONS,
    mlRows: ML_ROWS,
    handover,
    body: BODY,
    expectedReduced: records,
    expected: { lifers, targets },
    distanceRows: DISTANCE_PAIRS.map(p => {
      const miles = distanceMiles(p.lat1, p.lng1, p.lat2, p.lng2)
      return { ...p, miles, text: formatMiles(miles) }
    }),
    formatRows: FORMAT_MILES.map(miles => ({ miles, text: formatMiles(miles) })),
    dateRows: DATE_SEEDS.map(s => {
      const p = parseObsDateStrict(s)
      return p ? { s, valid: true, y: p.y, m: p.m, d: p.d } : { s, valid: false }
    }),
    dstFamily: {
      tz: TZ,
      nowIso: DST_NOW_ISO,
      rows: DST_OBS.map(obsDt => {
        const days = daysBetween(parseObsDateStrict(obsDt)!, dstNow)
        return { obsDt, days, inWeek: inWindow(days, 'week'), recency: recencyLabel(days) }
      }),
    },
    recencyRows: RECENCY_DAYS.map(days => ({ days, label: recencyLabel(days) })),
    retryAfterRows: retryFixture.rateLimit.retryAfterRows.map(r => ({ header: r.header, seconds: parseRetryAfterSeconds(r.header) })),
    foldRows: FOLD_INPUTS.map(s => ({ in: s, out: foldName(s), validHandoverName: isValidHandoverName(foldName(s)) })),
    needsRows: subsets.map(missing => ({ missing, phrase: needsPhrase(missing) })),
    links: linkFamilies(),
  }
}

/** The deep-link table (schema.md 7.2): each row is `{ raw, expected }`, the
 *  expectation produced by the SHIPPED parser; the Swift builder must produce
 *  every `views` and `birds` raw exactly, and the view link for every refused
 *  pair. The family a row sits in is its authored intent. */
function linkFamilies() {
  const row = (raw: string) => ({ raw, expected: parseWidgetLink(raw) })
  const birds: WidgetLink[] = [
    ...WIDGET_LINKS.map(v => ({ ...v, bird: LINK_BIRD })),
    ...LINK_BIRD_BOUNDS.map(bird => ({ ...WIDGET_LINKS[4]!, bird })),
  ]
  return {
    views: WIDGET_LINKS.map(v => row(buildWidgetLink(v))),
    birds: birds.map(l => row(buildWidgetLink(l))),
    degraded: LINK_DEGRADE_BASES.flatMap(v => LINK_DEGRADED_SUFFIXES.map(s => row(buildWidgetLink(v as ViewLink) + s))),
    rejected: LINK_REJECTED.map(row),
    refusedPairs: LINK_REFUSED_PAIRS,
  }
}
