// Every user-facing string of the Alerts section (ios-alerts, design-spec.md
// sections 1 to 8), verbatim, plus the pure builders for the ones that carry a
// time, a count or a place. One module so alertsCopy.test.ts can sweep the
// whole corpus (generated by CALLING every builder) for U+2014, British
// spellings, singular/plural agreement and the forbidden cadence words
// ("every hour", "exactly", a clock time), per ui.md's copy-guard rule.
//
// Lazy: imported only by the lazy section and the tests, never by the entry
// graph (entryChunk.test.ts). Pure: every builder takes its "now" as an
// argument (the snapshot's own `now`), never from the clock, so rendering stays
// pure (react-hooks/purity).
//
// American spelling; the middle dot U+00B7 is the in-line separator and the
// ellipsis U+2026 closes "Locating", as in the Default Location button.

import type { AlertBlocked, AlertOutcome, InboxRow, LastCheck, PlacePhrase } from './alertsState'
// The entry points' words live in the entry-safe module (the header bell and
// the sidebar item ride the entry chunk); re-exported here so this module's
// corpus sweep covers them with every other string.
export { BADGE_CAP_TEXT, INBOX_ENTRY_LABEL, badgeText, inboxEntryName } from './alertsInboxEntry'
import { daysBetween, localCivilDate, parseObsDateStrict } from '../widgets/widgetRows'
import { getDateFormatPref, type DateFormatPref } from '../formatDate'

export const ALERTS_HEADER = 'Alerts'
export const ALERTS_SWITCH_LABEL = 'Alerts'

export const INTRO = 'Tells you when eBird reports a species you have never recorded near a place you choose. Only on iPhone and iPad.'
export const OFF_NOTE = 'Off until you turn it on. Nothing is checked, sent or asked for before then.'
export const ON_NOTE = 'Checks run in the background and when you open the app. Turn it off and every scheduled check and pending notification stops at once.'

export const CADENCE_LABEL = 'Cadence'
export const CADENCE_DESC = 'Hourly checks about once an hour, Daily about once a day. iOS decides when a background check runs. Opening the app also checks, once the interval has passed.'
export const CADENCE_OPTIONS = { hourly: 'Hourly', daily: 'Daily' } as const

export const QUIET_LABEL = 'Quiet hours'
export const QUIET_DESC = 'No alert arrives inside the window. Anything found then goes into the inbox right away and is delivered when the window ends.'
export const QUIET_FROM = 'From'
export const QUIET_TO = 'To'
export const QUIET_EQUAL = 'Start and end must differ. Until they do, no quiet period applies.'

export const MEASURE_LABEL = 'Measure from'
export const MEASURE_OPTIONS = { fixed: 'Fixed place', 'my-location': 'My location' } as const
export const MEASURE_DESC_FIXED = 'Distances are measured from the place below.'
export const MEASURE_DESC_MY = 'Your most recent known position, under the same While Using permission as Use my location. With the app closed, a check uses the last position the app or a widget read from your device in the past 24 hours; SnowRaven never asks for Always. When no recent position is known, the fixed place below is used instead.'

export const FIXED_LABEL = 'Fixed place'
export const FIXED_LABEL_FALLBACK = 'Fixed place, used when no recent position is known'
export const FOLLOWING_DEFAULT = 'Following your Default Location'
export const LATITUDE = 'Latitude'
export const LONGITUDE = 'Longitude'
export const USE_MY_LOCATION = 'Use my location'
export const LOCATING = 'Locating…'
export const FOLLOW_DEFAULT = 'Follow Default Location'
export const FIXED_HINT = 'Editing this place never changes your Default Location, and saving a Default Location later leaves a place you set here alone.'

export const RADIUS_LABEL = 'Radius'
export const RADIUS_UNIT = 'miles'
export const RADIUS_HINT = 'A whole number from 1 to 25.'
export const RADIUS_REFUSED = 'Radius is a whole number from 1 to 25 miles.'

export const NOT_CHECKED = 'Not checked yet'
export const FROM_FIXED_CAPTION = 'From your fixed place'

/** The last-check outcome words after "Last checked {time}, " (design-spec 4). */
export function outcomeWords(outcome: AlertOutcome, hits: number): string {
  switch (outcome) {
    case 'nothing-new': return 'nothing new'
    case 'hits': return `${hits} ${hits === 1 ? 'lifer' : 'lifers'}`
    case 'unreachable': return 'offline'
    case 'no-answer': return 'eBird did not answer'
    case 'busy': return 'eBird busy'
    case 'key-rejected': return 'eBird did not accept your key'
  }
}

/** A blocked sentence: the lead (600, --sr-text) and the rest (muted). */
export const BLOCKED: Record<AlertBlocked, { lead: string; rest: string }> = {
  'no-key': { lead: 'Add your eBird API key', rest: ' in API Keys, above. Checks wait until then.' },
  'no-backup': { lead: 'Load your eBird backup', rest: ' in Default Files, above. Checks wait until then.' },
  'no-place': { lead: 'Set a place to measure from.', rest: ' Search a place name, enter coordinates, or use your location above.' },
  'location-off': { lead: 'Location is off for SnowRaven.', rest: ' Turn it on in Settings, Privacy & Security, Location Services, or set a fixed place instead.' },
  'no-position': { lead: 'No recent position.', rest: ' Open SnowRaven with Location on, or set a fixed place instead.' },
}

export const NOTIFICATIONS_DENIED = 'Notifications are off for SnowRaven, so checks fill the inbox but no banner is sent. Turn them on in Settings, Notifications, SnowRaven.'
export const BACKGROUND_REFRESH_OFF = 'Background App Refresh is off for SnowRaven, so checks run only when you open the app. Turn it on in Settings, General, Background App Refresh.'
/** A native command that failed (the section's only error line). */
export const SAVE_FAILED = 'That change could not be saved. Try again.'

export const FINE_NETWORK = 'A check sends the chosen coordinates to eBird with your own key, the same nearby-sightings request Nearby Lifers makes. Nothing is sent to the developer.'
export const FINE_COUNTABILITY = 'Alerts name species only. Spuhs, slashes and hybrids stay on the map and in the widgets, but never interrupt you.'

export const INBOX_LABEL = 'Inbox'
export const INBOX_LIST_LABEL = 'Past alerts, newest first'
export const INBOX_EMPTY = 'No alerts yet.'
export const INBOX_BOUND = 'Kept on this device for 30 days, up to 200 alerts, and never synced. Cleared with your eBird backup. Tap an alert to see it on the map.'
export const CLEAR = 'Clear'
export const CANCEL = 'Cancel'
export const CLEAR_TITLE = 'Clear the inbox?'
export const CLEAR_BODY = 'Removes every alert from this device. Your settings stay as they are, and alerts stay on. A species alerted before may alert again at the next check.'

export function inboxCount(n: number): string {
  return n === 0 ? '' : `${n} ${n === 1 ? 'alert' : 'alerts'}`
}

// ── The inbox as its own sheet (design-spec 7.1 to 7.5, the revision) ────────

/** The card row's second line when the inbox is empty (no period). */
export const INBOX_NONE_YET = 'No alerts yet'
/** The sheet's close button. */
export const CLOSE_INBOX = 'Close the inbox'
/** The word after a new row's name, and its accessible-name prefix. */
export const NEW_WORD = 'New'
export const NEW_PREFIX = 'New. '
/** The empty sheet's second line. */
export const INBOX_EMPTY_DETAIL = 'A species eBird reports near your place that is not in your backup appears here, and as a notification.'
/** The footer's Mark read button: its visible label and its accessible name
 *  (alerts-inbox-mark-read; no hidden "all", Clear does not say it either). */
export const MARK_READ = 'Mark read'
/** The one polite announcement after Mark read: it names the action, never a
 *  count (design-spec 7.5: the count is never announced live). */
export const MARKED_READ_STATUS = 'Marked read.'

/** The card row's second line: "6 alerts, 3 new", "1 alert", "No alerts yet". */
export function inboxRowSub(n: number, newCount: number): string {
  if (n === 0) return INBOX_NONE_YET
  return `${inboxCount(n)}${newCount > 0 ? `, ${newCount} new` : ''}`
}

/** The card row's accessible name: "Inbox, 6 alerts, 3 new", "Inbox, no alerts yet". */
export function inboxRowName(n: number, newCount: number): string {
  if (n === 0) return `${INBOX_LABEL}, no alerts yet`
  return `${INBOX_LABEL}, ${inboxRowSub(n, newCount)}`
}

// ── Times ─────────────────────────────────────────────────────────────────────

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] as const

/** A minute of the local day as the design writes it: "10:00 PM", "7:00 AM". */
export function clockFromMinutes(min: number): string {
  const h24 = Math.floor(min / 60) % 24
  const m = min % 60
  const h = h24 % 12 === 0 ? 12 : h24 % 12
  return `${h}:${String(m).padStart(2, '0')} ${h24 < 12 ? 'AM' : 'PM'}`
}

/** An instant's local time: "9:41 AM" (a plain space, never U+202F). */
export function clockAt(ms: number): string {
  const d = new Date(ms)
  return clockFromMinutes(d.getHours() * 60 + d.getMinutes())
}

function sameLocalDay(a: Date, b: Date): boolean {
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate()
}

/**
 * When something happened, relative to `nowMs`, in local time: the time alone
 * today ("9:41 AM"), "Yesterday, 4:10 PM", else the app's date format without
 * the year and the time ("Sep 27, 11:03 AM"). Used for the alerted time and
 * the status line's check time.
 */
export function whenLocal(ms: number, nowMs: number, pref: DateFormatPref = getDateFormatPref()): string {
  const at = new Date(ms)
  const now = new Date(nowMs)
  const t = clockAt(ms)
  if (sameLocalDay(at, now)) return t
  const y = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1)
  if (sameLocalDay(at, y)) return `Yesterday, ${t}`
  const mo = MONTHS[at.getMonth()]!
  const day = at.getDate()
  const date = pref === 'iso'
    ? `${at.getFullYear()}-${String(at.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`
    : pref === 'day-first' ? `${day} ${mo}` : `${mo} ${day}`
  return `${date}, ${t}`
}

/** The status line's lead sentence for a last check. */
export function lastCheckedSentence(check: LastCheck, nowMs: number, pref?: DateFormatPref): string {
  const at = Date.parse(check.completedAt)
  const when = Number.isFinite(at) ? whenLocal(at, nowMs, pref) : ''
  return `Last checked ${when}, ${outcomeWords(check.outcome, check.hits)}`
}

/** The quiet-hours note under the two times (design-spec section 3). */
export function quietNote(startMin: number, endMin: number): string {
  if (startMin === endMin) return QUIET_EQUAL
  const start = clockFromMinutes(startMin)
  const end = clockFromMinutes(endMin)
  const across = endMin < startMin ? ', across midnight' : ''
  return `Quiet from ${start} to ${end}${across}. A find inside the window is delivered at ${end}.`
}

/** The device's IANA zone (the widget twin's civil-day arithmetic needs one). */
export function deviceZone(): string {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'
  } catch {
    return 'UTC'
  }
}

/** "today", "yesterday", "3 days ago" (the widget twin's calendar days,
 *  lowercase inside the sentence); a future-dated report reads "today". */
export function reportedDayWord(obsDt: string, nowMs: number, tz: string = deviceZone()): string {
  const d = parseObsDateStrict(obsDt)
  if (!d) return 'on an unknown day'
  const days = daysBetween(d, localCivilDate(nowMs, tz))
  if (days <= 0) return 'today'
  if (days === 1) return 'yesterday'
  return `${days} days ago`
}

export function placeLabel(p: PlacePhrase): string {
  return p.kind === 'name' ? p.name : p.kind === 'near-you' ? 'Near you' : 'Nearby'
}

/** A row's visible third line: "Reported today · Alerted 9:41 AM". */
export function rowWhen(row: InboxRow, nowMs: number, tz?: string, pref?: DateFormatPref): { day: string; alerted: string } {
  const at = Date.parse(row.alertedAt)
  return {
    day: reportedDayWord(row.obsDt, nowMs, tz),
    alerted: Number.isFinite(at) ? whenLocal(at, nowMs, pref) : '',
  }
}

/** A row's accessible name, one sentence (design-spec section 7), prefixed
 *  "New. " for a row alerted after the inbox was last viewed (7.3). */
export function rowLabel(row: InboxRow, nowMs: number, tz?: string, pref?: DateFormatPref, isNew = false): string {
  const w = rowWhen(row, nowMs, tz, pref)
  const place = row.locName || placeLabel(row.place)
  return `${isNew ? NEW_PREFIX : ''}${row.comName}, ${place}, ${row.distanceMi.toFixed(1)} miles, reported ${w.day}, alerted ${w.alerted}. Show on the map`
}
