// `findBlockSpans` — the shared span finder (weather-stats FR-01, QA-01).
//
// The byte-golden suite next door pins the strip's OUTPUT. That is necessary and
// not sufficient: a refactor could move a span's start and end by the same
// amount inside text that is discarded either way, and the golden would stay
// green while the PARSER (which reads the span text, not the strip's leftovers)
// started reading the wrong characters. So this file asserts the offsets
// themselves, against the decoded string, and the two suites together are the
// proof FR-34 asks for.
//
// Fixtures are built by calling the REAL formatters wherever a block is needed,
// which is what `.claude/rules/weather-tide.md` requires: a wording drift in
// `weatherFormatter.ts` / `tideFormatter.ts` must break these tests.
import { describe, it, expect } from 'vitest'
import { findBlockSpans, stripWeatherTideBlocks } from './commentBlocks'
import { decodeEntities } from './commentText'
import { formatWeather } from './weatherFormatter'
import type { HourlyResponse } from './weatherFormatter'
import { formatTide, formatTideBody, buildCombined } from './tideFormatter'
import type { TideReading } from './tide'
import type { TideStation } from './tideStations'

const hour: HourlyResponse = {
  data: [{
    dt: 1716570000, temp: 64, humidity: 72, dew_point: 55, wind_speed: 6, wind_deg: 250,
    clouds: 20, weather: [{ id: 801, description: 'few clouds' }],
    sunrise: 1716550000, sunset: 1716600000,
  }],
}
const WEATHER_BLOCK = formatWeather([hour], 'America/Los_Angeles', 33.7)

const STN: TideStation = { id: '9410660', name: 'Los Angeles', lat: 33.7, lng: -118.2, state: 'CA', obs: true }
const reading: TideReading = {
  levelMin: 4.1, levelMax: 5.3, source: 'predicted', trend: 'falling', turnedDuring: true,
  prevHL: { kind: 'high', v: 5.4, timeLocal: '9:12am' },
  nextHL: { kind: 'low', v: 0.7, timeLocal: '4:38pm' },
  station: STN, distanceMi: 11.2,
}
const TIDE_BLOCK = formatTide(reading)
const COMBINED_BLOCK = buildCombined(WEATHER_BLOCK, formatTideBody(reading))

const RAINCROW_BLOCK =
  '⛅  Scattered clouds  Temperature: 56 - 63°F  Wind: Mostly calm - light breeze  ' +
  'Wind Direction: SW - W  Cloud Cover: 42%  Humidity: 62 - 80%  Dew point: 49 - 50°F  ' +
  'Sunrise: 7:22am  Sunset: 7:15pm  Weather generated by <a href="https://raincrow.app/">RainCrow</a>'

function entityEncode(s: string): string {
  return [...s].map(ch => {
    const cp = ch.codePointAt(0)!
    if (ch === '&') return '&amp;'
    return cp > 127 ? `&#${cp};` : ch
  }).join('')
}

describe('findBlockSpans — shape', () => {
  it('returns nothing for an empty, blockless or whitespace comment', () => {
    expect(findBlockSpans('')).toEqual([])
    expect(findBlockSpans('   \n  ')).toEqual([])
    expect(findBlockSpans('A lovely morning at the pond.')).toEqual([])
    // A single stray marker in prose is not a block, and must not become one.
    expect(findBlockSpans('Wind: gusty all morning, so nothing was singing.')).toEqual([])
  })

  it('spans are ascending and non-overlapping', () => {
    const c = `Before.\n\n${WEATHER_BLOCK}\n\nBetween.\n\n${TIDE_BLOCK}\n\nAfter.`
    const spans = findBlockSpans(c)
    expect(spans.length).toBe(2)
    for (const s of spans) expect(s.end).toBeGreaterThan(s.start)
    expect(spans[1].start).toBeGreaterThanOrEqual(spans[0].end)
  })

  it('offsets index the DECODED string, not the raw one', () => {
    const raw = entityEncode(`Quiet morning.\n\n${WEATHER_BLOCK}`)
    const decoded = decodeEntities(raw)
    const [span] = findBlockSpans(raw)
    // The raw comment is much longer than the decoded one, so an offset that
    // indexed the raw string would run past the block entirely.
    expect(raw.length).toBeGreaterThan(decoded.length)
    const text = decoded.slice(span.start, span.end)
    expect(text).toContain('Temperature:')
    expect(text).toContain('Weather generated by')
    expect(text.startsWith('🌤️')).toBe(true)
  })

  it('every span contains its own attribution, and the strip removes exactly the spans', () => {
    const c = `Before.\n\n${WEATHER_BLOCK}\n\nBetween.\n\n${TIDE_BLOCK}\n\nAfter.`
    const decoded = decodeEntities(c)
    const spans = findBlockSpans(c)
    expect(decoded.slice(spans[0].start, spans[0].end)).toContain('Weather generated by')
    expect(decoded.slice(spans[1].start, spans[1].end)).toContain('Tide data from NOAA CO-OPS')

    // Independently reconstruct the strip from the spans; the shipped strip must
    // agree, which is what makes "one span implementation" a property rather
    // than a claim about where the code sits.
    let out = ''
    let kept = 0
    for (const s of spans) { out += decoded.slice(kept, s.start); kept = s.end }
    out += decoded.slice(kept)
    const normalized = out.replace(/^[ \t]+$/gm, '').replace(/\n{3,}/g, '\n\n').trim()
    expect(stripWeatherTideBlocks(c)).toBe(normalized)
  })
})

describe('findBlockSpans — kind', () => {
  it('a SnowRaven weather block is "weather"', () => {
    expect(findBlockSpans(WEATHER_BLOCK).map(s => s.kind)).toEqual(['weather'])
  })

  it('a RainCrow weather block is "weather"', () => {
    expect(findBlockSpans(RAINCROW_BLOCK).map(s => s.kind)).toEqual(['weather'])
  })

  it('a standalone tide block is "tide"', () => {
    expect(findBlockSpans(TIDE_BLOCK).map(s => s.kind)).toEqual(['tide'])
  })

  // THE SHAPE THE PARSER HAS TO KNOW ABOUT, pinned here because it contradicts
  // the obvious reading of "a combined block is one span of kind 'combined'".
  //
  // `buildCombined` ends the tide BODY with the bare NOAA credit and then adds a
  // single "Weather and tide generated by …" line. ATTRIB_END_RE matches the
  // bare credit too, so a combined comment is TWO spans: a `'tide'` span
  // covering the whole weather body AND the tide body, and a `'combined'` span
  // covering only the trailing attribution. That is the shipped span walk, it is
  // what the byte-golden corpus pins, and it is why `parseWeatherBlock` selects
  // the first span that YIELDS A FIELD rather than the first span whose `kind`
  // says weather — the latter would hand it the attribution and nothing else on
  // every combined block.
  it('the combined block is TWO spans: the bodies, then the attribution', () => {
    const spans = findBlockSpans(COMBINED_BLOCK)
    expect(spans.map(s => s.kind)).toEqual(['tide', 'combined'])
    const decoded = decodeEntities(COMBINED_BLOCK)
    // The first span carries every weather field, which is what the parser reads.
    const body = decoded.slice(spans[0].start, spans[0].end)
    expect(body.startsWith('🌤️')).toBe(true)
    expect(body).toContain('Temperature:')
    expect(body).toContain('Sunset:')
    expect(body).toContain('Tide data from NOAA CO-OPS')
    // The second carries the attribution and nothing else.
    expect(decoded.slice(spans[1].start, spans[1].end)).toBe(
      'Weather and tide generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>',
    )
  })

  it('a weather block and a tide block in one comment are two spans of their own kinds', () => {
    expect(findBlockSpans(`${WEATHER_BLOCK}\n\n${TIDE_BLOCK}`).map(s => s.kind))
      .toEqual(['weather', 'tide'])
  })

  it('an attribution-less block takes its kind from the detectors, coarsely', () => {
    // No attribution to read, so the only evidence is which detectors fired
    // over the whole comment. Weather labels only → 'weather'.
    const wxOnly = '☁️  Broken clouds  Temperature: 45 - 48°F  Wind: Mostly calm  Sunrise: 6:37am  Sunset: 7:41pm'
    expect(findBlockSpans(wxOnly).map(s => s.kind)).toEqual(['weather'])
    // Tide markers only → 'tide'.
    const tideOnly = '🌊  Tide: falling  Water level: 4.1 - 5.3 ft  Relative to MLLW  Station: Los Angeles'
    expect(findBlockSpans(tideOnly).map(s => s.kind)).toEqual(['tide'])
    // Both detectors firing with no attribution anywhere → 'combined'.
    const both = '🌊  Temperature: 45°F  Wind: Calm  Tide: falling  Water level: 4.1 ft  Relative to MLLW'
    expect(findBlockSpans(both).map(s => s.kind)).toEqual(['combined'])
  })
})

describe('findBlockSpans — the shapes the parser depends on', () => {
  it('two weather blocks in one comment yield two spans, and the FIRST is the earlier one', () => {
    const c = `Pasted twice.\n\n${WEATHER_BLOCK}\n\n${WEATHER_BLOCK}`
    const spans = findBlockSpans(c)
    expect(spans.length).toBe(2)
    expect(spans.every(s => s.kind === 'weather')).toBe(true)
    expect(spans[0].start).toBeLessThan(spans[1].start)
  })

  it('a comment with only a tide block yields no weather-bearing span', () => {
    expect(findBlockSpans(TIDE_BLOCK).some(s => s.kind !== 'tide')).toBe(false)
  })

  it('the span starts at the emoji header, so prose before it is outside', () => {
    const c = 'Saw a ❄ Snow Bunting today!  ☀️  Clear sky  Temperature: 40°F  Wind: Calm  Weather generated by SnowRaven'
    const decoded = decodeEntities(c)
    const [span] = findBlockSpans(c)
    expect(decoded.slice(0, span.start)).toBe('Saw a ❄ Snow Bunting today!  ')
    expect(decoded.slice(span.start).startsWith('☀️')).toBe(true)
  })

  it('the span ends at the attribution, so prose after it is outside (collapsed CSV shape)', () => {
    const c = 'Class field trip.    ☀️  Clear sky  Temperature: 53 - 67°F  Wind: Mostly calm  Sunrise: 7:30am  Weather generated by RainCrow  Scrub jays at the trailhead.'
    const decoded = decodeEntities(c)
    const [span] = findBlockSpans(c)
    expect(decoded.slice(span.end)).toBe('  Scrub jays at the trailhead.')
  })

  it('is stateless across calls (module-level /g lastIndex)', () => {
    const first = findBlockSpans(`Great walk.\n\n${WEATHER_BLOCK}`)
    const second = findBlockSpans(`Great walk.\n\n${WEATHER_BLOCK}`)
    expect(second).toEqual(first)
    // The attribution-less fallback must see ALL markers on a later call.
    expect(findBlockSpans('Temperature: 50°F  Wind: 5 mph NW').length).toBe(1)
  })
})
