import { describe, it, expect } from 'vitest'
import { hasWeatherBlock, hasTideBlock, hasSnowravenWeatherBlock, hasRaincrowWeatherBlock, stripWeatherTideBlocks } from './commentBlocks'
import { formatWeather, ATTRIBUTION } from './weatherFormatter'
import type { HourlyResponse } from './weatherFormatter'
import { formatTide, formatTideBody, buildCombined } from './tideFormatter'
import type { TideReading } from './tide'
import type { TideStation } from './tideStations'

// ── Real fixtures: the detectors are coupled to what the formatters actually
//    emit, so a wording drift in a formatter breaks these tests (the intent). ──
const hour: HourlyResponse = {
  data: [{
    temp: 64, humidity: 72, dew_point: 55, wind_speed: 6, wind_deg: 250,
    clouds: 20, weather: [{ id: 801, description: 'few clouds' }],
    sunrise: 1716550000, sunset: 1716600000,
  }],
}
const WEATHER_BLOCK = formatWeather([hour], 'America/Los_Angeles')

const STN: TideStation = { id: '9410660', name: 'Los Angeles', lat: 33.7, lng: -118.2, state: 'CA', obs: true }
const reading: TideReading = {
  levelMin: 4.1, levelMax: 5.3, source: 'predicted', trend: 'falling', turnedDuring: true,
  prevHL: { kind: 'high', v: 5.4, timeLocal: '9:12am' },
  nextHL: { kind: 'low', v: 0.7, timeLocal: '4:38pm' },
  station: STN, distanceMi: 11.2,
}
const TIDE_BLOCK = formatTide(reading)
const COMBINED_BLOCK = buildCombined(WEATHER_BLOCK, formatTideBody(reading))

// Encode every non-ASCII char (emoji, en-dash) plus & as eBird does, to prove
// detection decodes first.
function entityEncode(s: string): string {
  return [...s]
    .map(ch => {
      const cp = ch.codePointAt(0)!
      if (ch === '&') return '&amp;'
      if (cp > 127) return `&#${cp};`
      return ch
    })
    .join('')
}

describe('hasWeatherBlock', () => {
  it('detects a real weather block (1)', () => {
    expect(hasWeatherBlock(WEATHER_BLOCK)).toBe(true)
  })
  it('does not flag a real tide block (2)', () => {
    expect(hasWeatherBlock(TIDE_BLOCK)).toBe(false)
  })
  it('detects the combined weather+tide block (3)', () => {
    expect(hasWeatherBlock(COMBINED_BLOCK)).toBe(true)
  })
  it('detects an entity-encoded weather block (4)', () => {
    const encoded = entityEncode(WEATHER_BLOCK)
    expect(encoded).not.toBe(WEATHER_BLOCK) // emoji/en-dash were encoded
    expect(hasWeatherBlock(encoded)).toBe(true)
  })
  it('ignores plain prose (6)', () => {
    expect(hasWeatherBlock('Lovely morning, lots of warblers.')).toBe(false)
  })
  it('ignores empty / whitespace (7)', () => {
    expect(hasWeatherBlock('')).toBe(false)
    expect(hasWeatherBlock('   \r\n  ')).toBe(false)
  })
  it('does not flag a single stray marker in prose (8)', () => {
    expect(hasWeatherBlock('Wind: light all morning, then it died down.')).toBe(false)
  })
  it('detects a block trimmed to emoji + condition + attribution only (9)', () => {
    const trimmed = '🌤️\nFew clouds\nWeather generated by SnowRaven'
    expect(hasWeatherBlock(trimmed)).toBe(true)
  })
})

describe('hasTideBlock', () => {
  it('does not flag a real weather block (1)', () => {
    expect(hasTideBlock(WEATHER_BLOCK)).toBe(false)
  })
  it('detects a real tide block (2)', () => {
    expect(hasTideBlock(TIDE_BLOCK)).toBe(true)
  })
  it('detects the combined weather+tide block (3)', () => {
    expect(hasTideBlock(COMBINED_BLOCK)).toBe(true)
  })
  it('detects an entity-encoded tide block (5)', () => {
    const encoded = entityEncode(TIDE_BLOCK)
    expect(encoded).not.toBe(TIDE_BLOCK)
    expect(hasTideBlock(encoded)).toBe(true)
  })
  it('ignores plain prose and empty (6/7)', () => {
    expect(hasTideBlock('Lovely morning, lots of warblers.')).toBe(false)
    expect(hasTideBlock('')).toBe(false)
    expect(hasTideBlock('   ')).toBe(false)
  })
  it('does not flag Station:/Tide: prose without "Relative to MLLW" or the NOAA credit (10)', () => {
    expect(hasTideBlock('Tide: coming in. Station: near the jetty.')).toBe(false)
  })
})

describe('combined block satisfies both detectors (QA-03)', () => {
  it('returns true from both hasWeatherBlock and hasTideBlock', () => {
    expect(hasWeatherBlock(COMBINED_BLOCK)).toBe(true)
    expect(hasTideBlock(COMBINED_BLOCK)).toBe(true)
  })
})

// raincrow.app mirrors the SnowRaven weather BODY format but credits itself, so
// the attribution is the only discriminator. Build a raincrow block by swapping
// the SnowRaven attribution line for raincrow's.
const RAINCROW_ATTRIB = 'Weather generated by <a href="https://raincrow.app">Raincrow</a>'
const RAINCROW_WEATHER = WEATHER_BLOCK.replace(ATTRIBUTION, RAINCROW_ATTRIB)

describe('hasSnowravenWeatherBlock', () => {
  it('detects a SnowRaven standalone weather block', () => {
    expect(hasSnowravenWeatherBlock(WEATHER_BLOCK)).toBe(true)
  })
  it('detects the combined weather+tide block (still SnowRaven weather)', () => {
    expect(hasSnowravenWeatherBlock(COMBINED_BLOCK)).toBe(true)
  })
  it('does NOT flag a raincrow weather block', () => {
    expect(hasWeatherBlock(RAINCROW_WEATHER)).toBe(true) // it IS a weather block…
    expect(hasSnowravenWeatherBlock(RAINCROW_WEATHER)).toBe(false) // …just not SnowRaven's
  })
  it('does NOT flag a standalone SnowRaven tide block ("via SnowRaven", no weather)', () => {
    expect(hasSnowravenWeatherBlock(TIDE_BLOCK)).toBe(false)
  })
  it('is robust to entity-encoded emoji/en-dash', () => {
    expect(hasSnowravenWeatherBlock(entityEncode(WEATHER_BLOCK))).toBe(true)
  })
  it('is robust to the attribution link being entity-encoded (&lt;a&gt;…)', () => {
    const encodedTags = WEATHER_BLOCK.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
    expect(encodedTags).toContain('&lt;a') // tags really were encoded
    expect(hasSnowravenWeatherBlock(encodedTags)).toBe(true)
  })
  it('does not match a SnowRaven weather block stripped of its attribution', () => {
    const noAttrib = WEATHER_BLOCK.replace(ATTRIBUTION, '').trim()
    expect(hasWeatherBlock(noAttrib)).toBe(true) // body labels remain
    expect(hasSnowravenWeatherBlock(noAttrib)).toBe(false) // can't tell who made it
  })
})

describe('hasRaincrowWeatherBlock (identified by its raincrow.app credit)', () => {
  it('flags a raincrow weather block (raincrow.app in the attribution link)', () => {
    expect(RAINCROW_WEATHER).toContain('raincrow.app')
    expect(hasRaincrowWeatherBlock(RAINCROW_WEATHER)).toBe(true)
  })
  it('finds raincrow.app even inside an entity-encoded link', () => {
    const encodedTags = RAINCROW_WEATHER.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
    expect(hasRaincrowWeatherBlock(encodedTags)).toBe(true)
  })
  it('does NOT flag a SnowRaven weather block', () => {
    expect(hasRaincrowWeatherBlock(WEATHER_BLOCK)).toBe(false)
  })
  it('does NOT flag a weather block with no recognizable attribution (positive, not exclusion)', () => {
    const noAttrib = WEATHER_BLOCK.replace(ATTRIBUTION, '').trim()
    expect(hasWeatherBlock(noAttrib)).toBe(true) // it IS a weather block…
    expect(hasRaincrowWeatherBlock(noAttrib)).toBe(false) // …but not a recognized Raincrow one
  })
  it('does NOT flag a tide-only block (no weather)', () => {
    expect(hasRaincrowWeatherBlock(TIDE_BLOCK)).toBe(false)
  })
  it('does NOT flag plain prose', () => {
    expect(hasRaincrowWeatherBlock('Great morning of warblers, no weather noted.')).toBe(false)
  })
})

describe('mixed comment: raincrow weather + SnowRaven tide (the contamination case)', () => {
  const MIXED = `${RAINCROW_WEATHER}\n\nLots of activity at the point.\n\n${TIDE_BLOCK}`
  it('weather is raincrow, NOT SnowRaven, even though the tide credits SnowRaven', () => {
    expect(hasWeatherBlock(MIXED)).toBe(true)
    expect(hasSnowravenWeatherBlock(MIXED)).toBe(false)
    expect(hasRaincrowWeatherBlock(MIXED)).toBe(true)
  })
  it('the SnowRaven tide is still detected', () => {
    expect(hasTideBlock(MIXED)).toBe(true)
  })
})

// ── stripWeatherTideBlocks — the Checklists tab's hide-blocks toggle ─────────
// Same real-formatter fixtures as the detectors: a wording drift in
// weatherFormatter/tideFormatter must break these tests.

describe('stripWeatherTideBlocks', () => {
  it('strips a weather block pasted below the user note (FR-05)', () => {
    const out = stripWeatherTideBlocks(`Great walk along the river.\n\n${WEATHER_BLOCK}`)
    expect(out).toBe('Great walk along the river.')
  })

  it('removes the emoji and free-text condition header lines with the block', () => {
    const out = stripWeatherTideBlocks(`Note.\n\n${WEATHER_BLOCK}`)
    expect(out).not.toContain('Few clouds')
    expect(out).not.toContain('🌤')
  })

  it('a block-only comment strips to empty (FR-07)', () => {
    expect(stripWeatherTideBlocks(WEATHER_BLOCK)).toBe('')
    expect(stripWeatherTideBlocks(TIDE_BLOCK)).toBe('')
    expect(stripWeatherTideBlocks(COMBINED_BLOCK)).toBe('')
  })

  it('keeps user text below the block', () => {
    expect(stripWeatherTideBlocks(`${WEATHER_BLOCK}\n\nSaw a kestrel on the wires.`)).toBe('Saw a kestrel on the wires.')
  })

  it('keeps user text sandwiched between two blocks (raincrow weather + SnowRaven tide)', () => {
    const mixed = `${RAINCROW_WEATHER}\n\nLots of activity at the point.\n\n${TIDE_BLOCK}`
    expect(stripWeatherTideBlocks(mixed)).toBe('Lots of activity at the point.')
  })

  it('preserves the user comment line breaks', () => {
    const out = stripWeatherTideBlocks(`Line one.\nLine two.\n\n${TIDE_BLOCK}`)
    expect(out).toBe('Line one.\nLine two.')
  })

  it('never leaves a triple blank gap where a block was removed', () => {
    const out = stripWeatherTideBlocks(`Before.\n\n${WEATHER_BLOCK}\n\nAfter.`)
    expect(out).toBe('Before.\n\nAfter.')
    expect(out).not.toMatch(/\n{3,}/)
  })

  it('strips an entity-encoded block (decodes first, like the detectors)', () => {
    const out = stripWeatherTideBlocks(entityEncode(`Quiet morning.\n\n${WEATHER_BLOCK}`))
    expect(out).toBe('Quiet morning.')
  })

  it('returns block-free prose unchanged (decoded + trimmed only)', () => {
    expect(stripWeatherTideBlocks('Lovely morning, lots of warblers.')).toBe('Lovely morning, lots of warblers.')
    expect(stripWeatherTideBlocks('A &amp; B')).toBe('A & B')
    expect(stripWeatherTideBlocks('')).toBe('')
  })

  it('does NOT strip a prose line that merely starts with a marker when no block is present', () => {
    const prose = 'Wind: light all morning, then it died down.\nGood sparrow movement.'
    expect(stripWeatherTideBlocks(prose)).toBe(prose)
  })
})

describe('stripWeatherTideBlocks — eBird-collapsed single-line comments (real CSV shape)', () => {
  // eBird's CSV export collapses a pasted block's line breaks into spaces, so
  // prose and block share one long line — and prose can continue AFTER the
  // attribution. The strip is a SPAN (emoji header → end of attribution link),
  // never the whole line. Shapes recreated from a real export (2026-06-10 bug:
  // a same-line comment after the block went missing).
  it('keeps prose before an inline block and strips emoji → linked attribution', () => {
    const c = 'Beautiful spring weather, wonderful group.    ⛅️☀️  Scattered clouds - clear sky  Temperature: 56 - 63°F  Wind: Mostly calm - light breeze  Wind Direction: SW - W  Cloud Cover: 42%  Humidity: 62 - 80%  Dew point: 49 - 50°F  Sunrise: 7:22am  Sunset: 7:15pm  Weather generated by <a href="https://raincrow.app/">RainCrow</a>'
    expect(stripWeatherTideBlocks(c)).toBe('Beautiful spring weather, wonderful group.')
  })

  it('keeps prose BEFORE and AFTER the block on the same line (bare-name attribution)', () => {
    const c = 'Class field trip.    ☀️☀️  Clear sky  Temperature: 53 - 67°F  Wind: Mostly calm  Sunrise: 7:30am  Weather generated by RainCrow  Scrub jays coming in to be fed at the trailhead.'
    const out = stripWeatherTideBlocks(c)
    expect(out).toContain('Class field trip.')
    expect(out).toContain('Scrub jays coming in to be fed at the trailhead.')
    expect(out).not.toContain('Temperature')
    expect(out).not.toContain('RainCrow')
  })

  it('a prose emoji earlier in the comment is not mistaken for the block header', () => {
    const c = 'Saw a ❄ Snow Bunting today!  ☀️  Clear sky  Temperature: 40°F  Wind: Calm  Weather generated by SnowRaven'
    const out = stripWeatherTideBlocks(c)
    expect(out).toContain('❄ Snow Bunting')
    expect(out).not.toContain('Clear sky')
  })

  it('free text between the emoji header and the body labels is part of the block', () => {
    const c = 'Group met at dawn.  ☀️⛅️  Clear sky - scattered clouds  Heavy fog at lake level  Temperature: 49 - 62°F  Wind: Mostly calm  Weather generated by RainCrow'
    expect(stripWeatherTideBlocks(c)).toBe('Group met at dawn.')
  })

  it('strips a night block headed by a moon-phase emoji (RainCrow night checklists)', () => {
    const c = 'Owling before dawn.  🌔  Clear sky  Temperature: 59°F  Wind: Light breeze - gentle breeze  Wind Direction: W  Cloud Cover: 0%  Humidity: 72%  Sunrise: 6:16am  Sunset: 7:56pm  Weather generated by <a href="https://raincrow.app/">RainCrow</a>'
    expect(stripWeatherTideBlocks(c)).toBe('Owling before dawn.')
  })

  it('a moon-emoji block-only comment strips to empty', () => {
    const c = '🌒  Clear sky  Temperature: 56 - 60°F  Wind: Mostly calm  Wind Direction: SW  Cloud Cover: 2%  Humidity: 76 - 92%  Dew point: 53 - 54°F  Sunrise: 6:16am  Sunset: 7:27pm  Weather generated by <a href="https://raincrow.app/">RainCrow</a>'
    expect(stripWeatherTideBlocks(c)).toBe('')
  })

  it('a block whose attribution was trimmed off still strips, ending after the last labeled value', () => {
    const c = '☁️🌧  Broken clouds - occasional squalls  Temperature: 45 - 48°F  Wind: Fairly gusty on the southwest side  Wind Direction: SW  Humidity: 77 - 86%  Sunrise: 6:37am  Sunset: 7:41pm    The class met at 7am on a blustery wet day.'
    const out = stripWeatherTideBlocks(c)
    expect(out).toBe('The class met at 7am on a blustery wet day.')
  })

  it('a block with NO emoji header absorbs its bare condition text but never a finished user sentence', () => {
    const c = 'Field trip with 18 participants.   Tide ebbing to a low around 10:23 AM, then rising.   Blue sky, broken clouds  Temperature: 53 - 60°F  Wind: Mostly calm - light breeze  Wind Direction: NE - W  Weather generated by RainCrow.'
    const out = stripWeatherTideBlocks(c)
    expect(out).toContain('Field trip with 18 participants.')
    expect(out).toContain('Tide ebbing to a low around 10:23 AM, then rising.')
    expect(out).not.toContain('Blue sky')
    expect(out).not.toContain('Temperature')
  })

  // Security-review regressions (2026-06-10): shared-module regex state and
  // hostile-input complexity.
  it('is stateless across calls — an attribution-less block strips the same after processing an attribution-bearing one', () => {
    // 1st call leaves the module-level marker regex's lastIndex dirty…
    expect(stripWeatherTideBlocks(`Great walk.\n\n${WEATHER_BLOCK}`)).toBe('Great walk.')
    // …2nd call takes the no-attribution fallback, which must see ALL markers
    // (a stale lastIndex previously made it skip them and leak the block).
    expect(stripWeatherTideBlocks('Temperature: 50°F  Wind: 5 mph NW')).toBe('')
  })

  it('handles attribution-spam comments without quadratic stall', () => {
    const spam = 'Weather generated by x '.repeat(9000) // ~207 KB hostile comment
    const t0 = performance.now()
    const out = stripWeatherTideBlocks(spam)
    const ms = performance.now() - t0
    expect(out).toBe('')
    expect(ms).toBeLessThan(1000) // quadratic version measured ~1s here; linear is ~ms
  })
})
