// BYTE-GOLDEN corpus for `stripWeatherTideBlocks` (weather-stats FR-34 / QA-02).
//
// WHY THIS FILE EXISTS AND WHY ITS COMMIT ORDER MATTERS. `commentBlocks.ts` is
// about to lose its private span loop to a shared `findBlockSpans` export, so
// that the new weather-block PARSER and the strip cannot disagree about where a
// block begins and ends. That extraction moves lines and must change no
// behaviour, and "before and after" can only be compared if the BEFORE exists as
// an artifact. So `commentBlocksStripGolden.json` was generated from the
// PRE-REFACTOR implementation and committed in its own commit, ahead of the
// refactor.
//
// **A GOLDEN REGENERATED IN THE SAME COMMIT AS THE REFACTOR IS THE REFACTOR
// FAILING SILENTLY.** The commit history is what makes that visible. If this
// suite goes red, the correct response is to fix the code, never the JSON.
//
// HOW THE CORPUS WAS BUILT (recorded so a regeneration is a deliberate act
// rather than a guess). Two halves:
//
//   synthetic/*  Every shape `commentBlocks.test.ts` exercises, with the blocks
//                built by calling the REAL formatters (`formatWeather`,
//                `formatTide`, `buildCombined`), plus day/night/storm headers,
//                multi-hour ranges, CRLF, tabs, entity-encoded copies, two
//                blocks in one comment, and the no-block cases.
//
//   export/*     220 distinct SHAPES taken from the author's own eBird backup
//                (3,252 checklist comments, 238 distinct shapes; every
//                block-bearing shape, plus 25 block-free ones). `.claude/rules/
//                weather-tide.md` requires real-export verification because all
//                three shipped strip bugs were invisible to formatter-fixture
//                tests, and these are those shapes.
//
//                THEY ARE REDACTED, and the redaction is why they may be
//                committed at all. Structural tokens are kept verbatim (the
//                eight weather labels, the tide labels, the attribution
//                phrases, the app names, `<a `/`</a>`/`href`/`https`, the
//                Beaufort words, numeric entity references and every emoji);
//                every other letter and digit is replaced by a deterministic
//                filler of the SAME LENGTH AND CASE. Lengths, punctuation,
//                whitespace runs, entity encodings, emoji runs and tag
//                positions are therefore real and the content is not, which is
//                exactly the set of properties the span walk reads. Nothing
//                here is a sighting, a place, a date or a reading.
//
// WHAT THIS SUITE CANNOT SEE: it pins the strip's OUTPUT, not its span offsets,
// so a refactor that moved a span start and end by the same amount inside text
// that is discarded either way would pass here. `commentBlocksSpans.test.ts`
// asserts the offsets directly, and the two together are the proof.
/// <reference types="node" />
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { stripWeatherTideBlocks } from './commentBlocks'

interface GoldenCase { id: string; input: string; output: string }
interface Golden { note: string; cases: GoldenCase[] }

const golden: Golden = JSON.parse(
  readFileSync(fileURLToPath(new URL('./commentBlocksStripGolden.json', import.meta.url)), 'utf8'),
)

describe('stripWeatherTideBlocks byte-golden corpus (FR-34, QA-02)', () => {
  it('the corpus is present and covers both halves', () => {
    // Non-vacuity: a deleted or emptied JSON must fail loudly rather than pass
    // as a clean sweep of nothing.
    expect(golden.cases.length).toBeGreaterThanOrEqual(250)
    expect(golden.cases.filter(c => c.id.startsWith('synthetic/')).length).toBeGreaterThanOrEqual(30)
    expect(golden.cases.filter(c => c.id.startsWith('export/')).length).toBeGreaterThanOrEqual(200)
  })

  it('the corpus exercises both outcomes, so equality is not trivially satisfied', () => {
    // A corpus of block-only comments would pass against an implementation that
    // returned '' for everything; a corpus of block-free ones would pass against
    // one that returned its input. Both outcomes have to be present in bulk.
    expect(golden.cases.filter(c => c.output === '').length).toBeGreaterThanOrEqual(50)
    expect(golden.cases.filter(c => c.output !== '').length).toBeGreaterThanOrEqual(50)
    // And at least one case where a block was removed and prose SURVIVED, which
    // is the only outcome that pins a span's two edges at once.
    expect(golden.cases.filter(c =>
      c.output !== '' && c.output !== c.input.trim() && /generated by/i.test(c.input),
    ).length).toBeGreaterThanOrEqual(5)
  })

  it('every case returns byte-identical output', () => {
    const drift: string[] = []
    for (const c of golden.cases) {
      const got = stripWeatherTideBlocks(c.input)
      if (got !== c.output) drift.push(`${c.id}\n  expected: ${JSON.stringify(c.output)}\n  actual:   ${JSON.stringify(got)}`)
    }
    expect(drift.join('\n')).toBe('')
  })

  it('the strip is stateless across the whole corpus in either direction', () => {
    // Module-level /g regexes carry shared mutable `lastIndex`, and a stale one
    // made the strip fail ORDER-DEPENDENTLY once already (0.5.27). Running the
    // corpus backwards must give the same answers as running it forwards.
    for (const c of [...golden.cases].reverse()) {
      expect(stripWeatherTideBlocks(c.input)).toBe(c.output)
    }
  })
})
