// Pure, decode-first detectors for whether a checklist comment already carries a
// SnowRaven / raincrow WEATHER or TIDE block. eBird returns comments
// HTML-entity-encoded, so detection runs on the DECODED text (via decodeEntities)
// and never touches innerHTML. The markers are taken verbatim from the real
// formatters (lib/weatherFormatter.ts, lib/tideFormatter.ts) — see schema.md §3.

import { decodeEntities } from './commentText'

// The labeled lines formatWeatherBody() emits. ≥2 of these (case-insensitive)
// signal a weather block; the ≥2 threshold (not 1) avoids a false positive from
// ordinary prose that happens to say e.g. "Wind: gusty".
const WEATHER_MARKERS = [
  'Temperature:',
  'Wind:',
  'Wind Direction:',
  'Cloud Cover:',
  'Dew point:',
  'Humidity:',
  'Sunrise:',
  'Sunset:',
] as const

// The WEATHER attribution signature (formatWeather appends ATTRIBUTION =
// "Weather generated by …SnowRaven"). Catches a weather block trimmed to just the
// emoji + condition + attribution. raincrow.app mirrors the same SnowRaven
// format. NOTE: it must be the weather-SPECIFIC phrase "Weather generated by" —
// NOT the bare "SnowRaven" / github token, because a standalone TIDE block's
// attribution ("Tide data from NOAA CO-OPS · via SnowRaven") also contains those,
// which would make hasWeatherBlock false-positive on a pure tide block.
const WEATHER_ATTRIB_TOKENS = [
  'Weather generated by',
] as const

// The tide block's most distinctive, always-present markers (formatTideBody).
// "Relative to MLLW" is the single strongest discriminator — it appears in no
// weather block and no ordinary birding prose. The NOAA credit is the
// attribution signature.
const TIDE_RELATIVE = 'Relative to MLLW'
const TIDE_WATER_LEVEL = 'Water level:'
const TIDE_STATION = 'Station:'
const TIDE_TREND = 'Tide:'
const TIDE_NOAA_CREDIT = 'Tide data from NOAA CO-OPS'

/** Count how many of `needles` appear (case-insensitive) in the lowercased haystack. */
function countMarkers(lowerHaystack: string, needles: readonly string[]): number {
  let n = 0
  for (const m of needles) {
    if (lowerHaystack.includes(m.toLowerCase())) n++
  }
  return n
}

function includesCI(lowerHaystack: string, needle: string): boolean {
  return lowerHaystack.includes(needle.toLowerCase())
}

/** True if the decoded comment contains a SnowRaven/raincrow WEATHER block (FR-06a). */
export function hasWeatherBlock(rawComment: string): boolean {
  if (!rawComment) return false
  const lower = decodeEntities(rawComment).toLowerCase()
  if (!lower.trim()) return false
  if (countMarkers(lower, WEATHER_MARKERS) >= 2) return true
  return countMarkers(lower, WEATHER_ATTRIB_TOKENS) >= 1
}

/** True if the decoded comment contains a SnowRaven TIDE block (FR-06b). */
export function hasTideBlock(rawComment: string): boolean {
  if (!rawComment) return false
  const lower = decodeEntities(rawComment).toLowerCase()
  if (!lower.trim()) return false
  // The NOAA credit alone is a definitive attribution signature.
  if (includesCI(lower, TIDE_NOAA_CREDIT)) return true
  // Otherwise require "Relative to MLLW" (the strongest discriminator) plus one
  // more tide-specific marker, so a stray prose "Tide: out" never matches.
  if (!includesCI(lower, TIDE_RELATIVE)) return false
  return (
    includesCI(lower, TIDE_WATER_LEVEL) ||
    includesCI(lower, TIDE_STATION) ||
    includesCI(lower, TIDE_TREND)
  )
}

// SnowRaven's WEATHER attribution is "Weather generated by …SnowRaven" and the
// combined block's is "Weather and tide generated by …SnowRaven" — both end in
// "generated by SnowRaven" once the <a> link is removed (the SnowRaven name is
// the link TEXT). A SnowRaven TIDE block instead credits "· via SnowRaven", and a
// raincrow weather block reads "generated by Raincrow", so this phrase marks a
// SnowRaven WEATHER block (standalone or combined) without mistaking a
// raincrow-weather + SnowRaven-tide comment for SnowRaven weather.
const SR_WEATHER_ATTRIB = 'generated by snowraven'

// Raincrow's attribution links to raincrow.app, so that domain positively
// identifies a Raincrow block. raincrow.app mirrors the SnowRaven *body* format,
// so hasWeatherBlock can't tell the two apart — the attribution link can. NOTE:
// raincrow.app lives in the link's href, so match the decoded text WITHOUT
// stripping tags (tag-stripping would remove the href).
const RAINCROW_ATTRIB = 'raincrow.app'

// Strip HTML tags (eBird may store the attribution as <a>…</a>, an entity-encoded
// &lt;a&gt;…, or bare link text), collapse whitespace, lowercase — so attribution
// LINK TEXT (e.g. "…generated by SnowRaven") matches regardless of how the link
// survived the round-trip.
function normalizeForApp(rawComment: string): string {
  return decodeEntities(rawComment).replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').toLowerCase()
}

/** True if the comment carries a SnowRaven WEATHER block — standalone, or the
 *  combined weather+tide block (both attribute the weather to SnowRaven). */
export function hasSnowravenWeatherBlock(rawComment: string): boolean {
  if (!hasWeatherBlock(rawComment)) return false
  return normalizeForApp(rawComment).includes(SR_WEATHER_ATTRIB)
}

/** True if the comment carries a Raincrow weather block, identified by its
 *  raincrow.app attribution link (raincrow.app mirrors the SnowRaven body format,
 *  so the attribution is the only reliable discriminator). */
export function hasRaincrowWeatherBlock(rawComment: string): boolean {
  if (!hasWeatherBlock(rawComment)) return false
  return decodeEntities(rawComment).toLowerCase().includes(RAINCROW_ATTRIB)
}
