import { describe, it, expect } from 'vitest'
import { hasWeatherBlock, hasTideBlock, hasSnowravenWeatherBlock, hasRaincrowWeatherBlock } from './commentBlocks'
import { formatWeather, ATTRIBUTION } from './weatherFormatter'
import type { HourlyResponse } from './weatherFormatter'
import { formatTide, formatTideBody, buildCombined } from './tideFormatter'
import type { TideReading } from './tide'
import type { TideStation } from './tideStations'

// ── Real fixtures: the detectors are coupled to what the formatters actually
//    emit, so a wording drift in a formatter breaks these tests (the intent). ──
const hour: HourlyResponse = {
  data: [{
    temp: 64, humidity: 72, dew_point: 55, wind_speed: 6, wind_deg: 250,
    clouds: 20, weather: [{ id: 801, description: 'few clouds' }],
    sunrise: 1716550000, sunset: 1716600000,
  }],
}
const WEATHER_BLOCK = formatWeather([hour], 'America/Los_Angeles')

const STN: TideStation = { id: '9410660', name: 'Los Angeles', lat: 33.7, lng: -118.2, state: 'CA', obs: true }
const reading: TideReading = {
  levelMin: 4.1, levelMax: 5.3, source: 'predicted', trend: 'falling', turnedDuring: true,
  prevHL: { kind: 'high', v: 5.4, timeLocal: '9:12am' },
  nextHL: { kind: 'low', v: 0.7, timeLocal: '4:38pm' },
  station: STN, distanceMi: 11.2,
}
const TIDE_BLOCK = formatTide(reading)
const COMBINED_BLOCK = buildCombined(WEATHER_BLOCK, formatTideBody(reading))

// Encode every non-ASCII char (emoji, en-dash) plus & as eBird does, to prove
// detection decodes first.
function entityEncode(s: string): string {
  return [...s]
    .map(ch => {
      const cp = ch.codePointAt(0)!
      if (ch === '&') return '&amp;'
      if (cp > 127) return `&#${cp};`
      return ch
    })
    .join('')
}

describe('hasWeatherBlock', () => {
  it('detects a real weather block (1)', () => {
    expect(hasWeatherBlock(WEATHER_BLOCK)).toBe(true)
  })
  it('does not flag a real tide block (2)', () => {
    expect(hasWeatherBlock(TIDE_BLOCK)).toBe(false)
  })
  it('detects the combined weather+tide block (3)', () => {
    expect(hasWeatherBlock(COMBINED_BLOCK)).toBe(true)
  })
  it('detects an entity-encoded weather block (4)', () => {
    const encoded = entityEncode(WEATHER_BLOCK)
    expect(encoded).not.toBe(WEATHER_BLOCK) // emoji/en-dash were encoded
    expect(hasWeatherBlock(encoded)).toBe(true)
  })
  it('ignores plain prose (6)', () => {
    expect(hasWeatherBlock('Lovely morning, lots of warblers.')).toBe(false)
  })
  it('ignores empty / whitespace (7)', () => {
    expect(hasWeatherBlock('')).toBe(false)
    expect(hasWeatherBlock('   \r\n  ')).toBe(false)
  })
  it('does not flag a single stray marker in prose (8)', () => {
    expect(hasWeatherBlock('Wind: light all morning, then it died down.')).toBe(false)
  })
  it('detects a block trimmed to emoji + condition + attribution only (9)', () => {
    const trimmed = '🌤️\nFew clouds\nWeather generated by SnowRaven'
    expect(hasWeatherBlock(trimmed)).toBe(true)
  })
})

describe('hasTideBlock', () => {
  it('does not flag a real weather block (1)', () => {
    expect(hasTideBlock(WEATHER_BLOCK)).toBe(false)
  })
  it('detects a real tide block (2)', () => {
    expect(hasTideBlock(TIDE_BLOCK)).toBe(true)
  })
  it('detects the combined weather+tide block (3)', () => {
    expect(hasTideBlock(COMBINED_BLOCK)).toBe(true)
  })
  it('detects an entity-encoded tide block (5)', () => {
    const encoded = entityEncode(TIDE_BLOCK)
    expect(encoded).not.toBe(TIDE_BLOCK)
    expect(hasTideBlock(encoded)).toBe(true)
  })
  it('ignores plain prose and empty (6/7)', () => {
    expect(hasTideBlock('Lovely morning, lots of warblers.')).toBe(false)
    expect(hasTideBlock('')).toBe(false)
    expect(hasTideBlock('   ')).toBe(false)
  })
  it('does not flag Station:/Tide: prose without "Relative to MLLW" or the NOAA credit (10)', () => {
    expect(hasTideBlock('Tide: coming in. Station: near the jetty.')).toBe(false)
  })
})

describe('combined block satisfies both detectors (QA-03)', () => {
  it('returns true from both hasWeatherBlock and hasTideBlock', () => {
    expect(hasWeatherBlock(COMBINED_BLOCK)).toBe(true)
    expect(hasTideBlock(COMBINED_BLOCK)).toBe(true)
  })
})

// raincrow.app mirrors the SnowRaven weather BODY format but credits itself, so
// the attribution is the only discriminator. Build a raincrow block by swapping
// the SnowRaven attribution line for raincrow's.
const RAINCROW_ATTRIB = 'Weather generated by <a href="https://raincrow.app">Raincrow</a>'
const RAINCROW_WEATHER = WEATHER_BLOCK.replace(ATTRIBUTION, RAINCROW_ATTRIB)

describe('hasSnowravenWeatherBlock', () => {
  it('detects a SnowRaven standalone weather block', () => {
    expect(hasSnowravenWeatherBlock(WEATHER_BLOCK)).toBe(true)
  })
  it('detects the combined weather+tide block (still SnowRaven weather)', () => {
    expect(hasSnowravenWeatherBlock(COMBINED_BLOCK)).toBe(true)
  })
  it('does NOT flag a raincrow weather block', () => {
    expect(hasWeatherBlock(RAINCROW_WEATHER)).toBe(true) // it IS a weather block…
    expect(hasSnowravenWeatherBlock(RAINCROW_WEATHER)).toBe(false) // …just not SnowRaven's
  })
  it('does NOT flag a standalone SnowRaven tide block ("via SnowRaven", no weather)', () => {
    expect(hasSnowravenWeatherBlock(TIDE_BLOCK)).toBe(false)
  })
  it('is robust to entity-encoded emoji/en-dash', () => {
    expect(hasSnowravenWeatherBlock(entityEncode(WEATHER_BLOCK))).toBe(true)
  })
  it('is robust to the attribution link being entity-encoded (&lt;a&gt;…)', () => {
    const encodedTags = WEATHER_BLOCK.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
    expect(encodedTags).toContain('&lt;a') // tags really were encoded
    expect(hasSnowravenWeatherBlock(encodedTags)).toBe(true)
  })
  it('does not match a SnowRaven weather block stripped of its attribution', () => {
    const noAttrib = WEATHER_BLOCK.replace(ATTRIBUTION, '').trim()
    expect(hasWeatherBlock(noAttrib)).toBe(true) // body labels remain
    expect(hasSnowravenWeatherBlock(noAttrib)).toBe(false) // can't tell who made it
  })
})

describe('hasRaincrowWeatherBlock (identified by its raincrow.app credit)', () => {
  it('flags a raincrow weather block (raincrow.app in the attribution link)', () => {
    expect(RAINCROW_WEATHER).toContain('raincrow.app')
    expect(hasRaincrowWeatherBlock(RAINCROW_WEATHER)).toBe(true)
  })
  it('finds raincrow.app even inside an entity-encoded link', () => {
    const encodedTags = RAINCROW_WEATHER.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
    expect(hasRaincrowWeatherBlock(encodedTags)).toBe(true)
  })
  it('does NOT flag a SnowRaven weather block', () => {
    expect(hasRaincrowWeatherBlock(WEATHER_BLOCK)).toBe(false)
  })
  it('does NOT flag a weather block with no recognizable attribution (positive, not exclusion)', () => {
    const noAttrib = WEATHER_BLOCK.replace(ATTRIBUTION, '').trim()
    expect(hasWeatherBlock(noAttrib)).toBe(true) // it IS a weather block…
    expect(hasRaincrowWeatherBlock(noAttrib)).toBe(false) // …but not a recognized Raincrow one
  })
  it('does NOT flag a tide-only block (no weather)', () => {
    expect(hasRaincrowWeatherBlock(TIDE_BLOCK)).toBe(false)
  })
  it('does NOT flag plain prose', () => {
    expect(hasRaincrowWeatherBlock('Great morning of warblers, no weather noted.')).toBe(false)
  })
})

describe('mixed comment: raincrow weather + SnowRaven tide (the contamination case)', () => {
  const MIXED = `${RAINCROW_WEATHER}\n\nLots of activity at the point.\n\n${TIDE_BLOCK}`
  it('weather is raincrow, NOT SnowRaven, even though the tide credits SnowRaven', () => {
    expect(hasWeatherBlock(MIXED)).toBe(true)
    expect(hasSnowravenWeatherBlock(MIXED)).toBe(false)
    expect(hasRaincrowWeatherBlock(MIXED)).toBe(true)
  })
  it('the SnowRaven tide is still detected', () => {
    expect(hasTideBlock(MIXED)).toBe(true)
  })
})
