// Pure, decode-first detectors for whether a checklist comment already carries a
// SnowRaven / raincrow WEATHER or TIDE block. eBird returns comments
// HTML-entity-encoded, so detection runs on the DECODED text (via decodeEntities)
// and never touches innerHTML. The markers are taken verbatim from the real
// formatters (lib/weatherFormatter.ts, lib/tideFormatter.ts) — see schema.md §3.

import { decodeEntities } from './commentText'

// The labeled lines formatWeatherBody() emits. ≥2 of these (case-insensitive)
// signal a weather block; the ≥2 threshold (not 1) avoids a false positive from
// ordinary prose that happens to say e.g. "Wind: gusty".
const WEATHER_MARKERS = [
  'Temperature:',
  'Wind:',
  'Wind Direction:',
  'Cloud Cover:',
  'Dew point:',
  'Humidity:',
  'Sunrise:',
  'Sunset:',
] as const

// The WEATHER attribution signature (formatWeather appends ATTRIBUTION =
// "Weather generated by …SnowRaven"). Catches a weather block trimmed to just the
// emoji + condition + attribution. raincrow.app mirrors the same SnowRaven
// format. NOTE: it must be the weather-SPECIFIC phrase "Weather generated by" —
// NOT the bare "SnowRaven" / github token, because a standalone TIDE block's
// attribution ("Tide data from NOAA CO-OPS · via SnowRaven") also contains those,
// which would make hasWeatherBlock false-positive on a pure tide block.
const WEATHER_ATTRIB_TOKENS = [
  'Weather generated by',
] as const

// The tide block's most distinctive, always-present markers (formatTideBody).
// "Relative to MLLW" is the single strongest discriminator — it appears in no
// weather block and no ordinary birding prose. The NOAA credit is the
// attribution signature.
const TIDE_RELATIVE = 'Relative to MLLW'
const TIDE_WATER_LEVEL = 'Water level:'
const TIDE_STATION = 'Station:'
const TIDE_TREND = 'Tide:'
const TIDE_NOAA_CREDIT = 'Tide data from NOAA CO-OPS'

/** Count how many of `needles` appear (case-insensitive) in the lowercased haystack. */
function countMarkers(lowerHaystack: string, needles: readonly string[]): number {
  let n = 0
  for (const m of needles) {
    if (lowerHaystack.includes(m.toLowerCase())) n++
  }
  return n
}

function includesCI(lowerHaystack: string, needle: string): boolean {
  return lowerHaystack.includes(needle.toLowerCase())
}

/** True if the decoded comment contains a SnowRaven/raincrow WEATHER block (FR-06a). */
export function hasWeatherBlock(rawComment: string): boolean {
  if (!rawComment) return false
  const lower = decodeEntities(rawComment).toLowerCase()
  if (!lower.trim()) return false
  if (countMarkers(lower, WEATHER_MARKERS) >= 2) return true
  return countMarkers(lower, WEATHER_ATTRIB_TOKENS) >= 1
}

/** True if the decoded comment contains a SnowRaven TIDE block (FR-06b). */
export function hasTideBlock(rawComment: string): boolean {
  if (!rawComment) return false
  const lower = decodeEntities(rawComment).toLowerCase()
  if (!lower.trim()) return false
  // The NOAA credit alone is a definitive attribution signature.
  if (includesCI(lower, TIDE_NOAA_CREDIT)) return true
  // Otherwise require "Relative to MLLW" (the strongest discriminator) plus one
  // more tide-specific marker, so a stray prose "Tide: out" never matches.
  if (!includesCI(lower, TIDE_RELATIVE)) return false
  return (
    includesCI(lower, TIDE_WATER_LEVEL) ||
    includesCI(lower, TIDE_STATION) ||
    includesCI(lower, TIDE_TREND)
  )
}

// SnowRaven's WEATHER attribution is "Weather generated by …SnowRaven" and the
// combined block's is "Weather and tide generated by …SnowRaven" — both end in
// "generated by SnowRaven" once the <a> link is removed (the SnowRaven name is
// the link TEXT). A SnowRaven TIDE block instead credits "· via SnowRaven", and a
// raincrow weather block reads "generated by Raincrow", so this phrase marks a
// SnowRaven WEATHER block (standalone or combined) without mistaking a
// raincrow-weather + SnowRaven-tide comment for SnowRaven weather.
const SR_WEATHER_ATTRIB = 'generated by snowraven'

// Raincrow's attribution links to raincrow.app, so that domain positively
// identifies a Raincrow block. raincrow.app mirrors the SnowRaven *body* format,
// so hasWeatherBlock can't tell the two apart — the attribution link can. NOTE:
// raincrow.app lives in the link's href, so match the decoded text WITHOUT
// stripping tags (tag-stripping would remove the href).
const RAINCROW_ATTRIB = 'raincrow.app'

// Strip HTML tags (eBird may store the attribution as <a>…</a>, an entity-encoded
// &lt;a&gt;…, or bare link text), collapse whitespace, lowercase — so attribution
// LINK TEXT (e.g. "…generated by SnowRaven") matches regardless of how the link
// survived the round-trip.
function normalizeForApp(rawComment: string): string {
  return decodeEntities(rawComment).replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').toLowerCase()
}

/** True if the comment carries a SnowRaven WEATHER block — standalone, or the
 *  combined weather+tide block (both attribute the weather to SnowRaven). */
export function hasSnowravenWeatherBlock(rawComment: string): boolean {
  if (!hasWeatherBlock(rawComment)) return false
  return normalizeForApp(rawComment).includes(SR_WEATHER_ATTRIB)
}

/** True if the comment carries a Raincrow weather block, identified by its
 *  raincrow.app attribution link (raincrow.app mirrors the SnowRaven body format,
 *  so the attribution is the only reliable discriminator). */
export function hasRaincrowWeatherBlock(rawComment: string): boolean {
  if (!hasWeatherBlock(rawComment)) return false
  return decodeEntities(rawComment).toLowerCase().includes(RAINCROW_ATTRIB)
}

// ── Stripping (the Checklists tab's hide-blocks toggle) ─────────────────────
//
// A block is the SPAN from its weather/tide emoji header through the END of its
// attribution link — never text before or after the span, even on the same
// line. This matters because eBird's CSV export collapses a pasted block's line
// breaks into spaces, so user prose routinely shares one long line with the
// block (and can continue AFTER the attribution); any line-based stripping
// would eat the user's words along with the block.

// The attribution that ENDS a block: SnowRaven/Raincrow weather ("Weather
// generated by …"), the combined block ("Weather and tide generated by …"), or
// the tide credit ("Tide data from NOAA CO-OPS · via …"). The credited name
// survives the eBird round-trip either as a decoded <a> link or as a bare word
// ("Weather generated by RainCrow"), so both forms are consumed.
// The <a> arms are length-BOUNDED ({0,400} attrs / {0,300} text — real
// attribution links are ~60 chars): an unbounded lazy [\s\S]*?<\/a> scans to
// the end of the comment on every unclosed '<a', which is one of the three
// scans that made hostile attribution-spam quadratic (security review).
const ATTRIB_END_RE =
  /(?:weather\s+and\s+tide\s+generated\s+by|weather\s+generated\s+by)[^\S\n]*(?:<a\b[^>]{0,400}>[\s\S]{0,300}?<\/a>|[^\s<]+)?|tide\s+data\s+from\s+noaa\s+co-ops(?:[^\S\n]*·[^\S\n]*via[^\S\n]*(?:<a\b[^>]{0,400}>[\s\S]{0,300}?<\/a>|[^\s<]+))?/giu

// Strong label-shaped body markers, used only to locate where a block's BODY
// begins, so the emoji header is searched in the right window. ("wind
// direction" before "wind" — alternation is first-match.)
const STRONG_MARKER_RE =
  /(?:temperature|wind direction|wind|cloud cover|humidity|dew point|sunrise|sunset|water level)\s*:|relative to mllw/giu

// A run of emoji (with optional variation selectors) — the block header, e.g.
// "🌤️", "☀️⛅️", "🌊". Any pictograph qualifies, not just SnowRaven's own
// condition set: RainCrow emits moon-phase emoji (🌒, 🌔, …) for night
// checklists. Safe because the span anchor is the LAST emoji run before the
// block's first labeled line — emoji in the user's own prose sit earlier.
const EMOJI_RUN_RE = /(?:\p{Extended_Pictographic}️?)+/gu

/** All [start, end) ranges of `re` (global) over `text`, scanned once with
 *  lastIndex reset — module-level /g regexes carry shared mutable state, and a
 *  stale lastIndex silently skips matches (security review: it made the strip
 *  fail order-dependently via matchAll inheriting lastIndex). */
function allMatchRanges(re: RegExp, text: string): Array<[number, number]> {
  re.lastIndex = 0
  const out: Array<[number, number]> = []
  let m: RegExpExecArray | null
  while ((m = re.exec(text)) !== null) {
    out.push([m.index, m.index + m[0].length])
    if (re.lastIndex === m.index) re.lastIndex++
  }
  return out
}

/** Largest value in sorted `arr` that is >= from and < end, or null. */
function lastInWindow(arr: number[], from: number, end: number): number | null {
  let lo = 0, hi = arr.length - 1, ans = -1
  while (lo <= hi) {
    const mid = (lo + hi) >> 1
    if (arr[mid] < end) { ans = mid; lo = mid + 1 } else { hi = mid - 1 }
  }
  return ans >= 0 && arr[ans] >= from ? arr[ans] : null
}

/** Smallest value in sorted `arr` that is >= from, or null. */
function firstAtOrAfter(arr: number[], from: number): number | null {
  let lo = 0, hi = arr.length - 1, ans = -1
  while (lo <= hi) {
    const mid = (lo + hi) >> 1
    if (arr[mid] >= from) { ans = mid; hi = mid - 1 } else { lo = mid + 1 }
  }
  return ans >= 0 ? arr[ans] : null
}

/**
 * Where a block's span begins, searching [from, markerIdx): the last emoji run
 * (the block header). When a block has NO emoji header (older or hand-trimmed
 * pastes), absorb the bare condition text directly before the first label —
 * one collapsed-line segment back (2+ spaces or a newline delimit segments,
 * since eBird collapses pasted newlines into spaces) — but never a finished
 * user sentence, so prose like "Tide ebbing to a low around 10:23 AM, then
 * rising." stays while "Blue sky, broken clouds" goes.
 */
function blockStart(decoded: string, from: number, markerIdx: number, emojiIdxs: number[]): number {
  const emojiIdx = lastInWindow(emojiIdxs, from, markerIdx)
  if (emojiIdx !== null) return emojiIdx
  const before = decoded.slice(from, markerIdx)
  const gap = /(?:[ \t]{2,}|\r?\n)(?=\S)/g
  let segStart = from
  let m: RegExpExecArray | null
  while ((m = gap.exec(before)) !== null) segStart = from + m.index + m[0].length
  const seg = decoded.slice(segStart, markerIdx).trim()
  if (seg && seg.length <= 80 && !/[.!?]$/.test(seg)) return segStart
  return markerIdx
}

/**
 * Remove SnowRaven/raincrow WEATHER blocks and SnowRaven TIDE blocks from a
 * comment, returning the user's own text — entity-DECODED and trimmed. A
 * block-only comment returns ''. A comment with no block returns the decoded
 * input unchanged (the detectors gate the scan).
 *
 * Each removed span runs from the block's emoji header (the last emoji run
 * before its first labeled body line; falling back to that first label, then to
 * the attribution itself) through the end of its attribution link. Text before
 * or after the span survives — including on the same line (FR-05 as clarified:
 * comments can precede OR follow a block in the same field).
 *
 * Single source of truth for the Checklists tab's "Show weather & tide blocks"
 * toggle (PRD FR-05/06/07): while blocks are hidden, DISPLAY and SEARCH must
 * both run on this function's output.
 */
export function stripWeatherTideBlocks(rawComment: string): string {
  if (!rawComment) return ''
  const decoded = decodeEntities(rawComment)
  if (!hasWeatherBlock(rawComment) && !hasTideBlock(rawComment)) return decoded.trim()

  // Single up-front scans (O(n) each); the span loop below then works off the
  // precomputed positions with binary searches instead of rescanning the tail
  // per attribution — keeps hostile attribution-spam comments linear instead
  // of quadratic (security review; same posture as namedBirds' NAME_TAG_RE).
  const markerRanges = allMatchRanges(STRONG_MARKER_RE, decoded)
  const markerStarts = markerRanges.map(r => r[0])
  const emojiIdxs = allMatchRanges(EMOJI_RUN_RE, decoded).map(r => r[0])

  const spans: Array<[number, number]> = []
  let pos = 0
  ATTRIB_END_RE.lastIndex = 0
  let attrib: RegExpExecArray | null
  while ((attrib = ATTRIB_END_RE.exec(decoded)) !== null) {
    const attribStart = attrib.index
    const attribEnd = attrib.index + attrib[0].length

    // Where this block's body begins: the first strong marker after the last
    // kept position (only if it precedes this attribution).
    const mk = firstAtOrAfter(markerStarts, pos)
    const markerIdx = mk !== null && mk < attribStart ? mk : attribStart

    spans.push([blockStart(decoded, pos, markerIdx, emojiIdxs), attribEnd])
    pos = attribEnd
    ATTRIB_END_RE.lastIndex = attribEnd
  }

  // Fallback for a block whose attribution was trimmed off (seen in real
  // exports): the detectors fired but no attribution exists anywhere, so the
  // span runs from the emoji header to the end of the LAST labeled value —
  // bounded at the next line break or 2+-space gap (eBird's collapsed-newline
  // separator), so prose following the block survives.
  if (spans.length === 0 && markerRanges.length >= 2) {
    const firstStart = markerRanges[0][0]
    const lastEnd = markerRanges[markerRanges.length - 1][1]
    const tail = decoded.slice(lastEnd)
    const value = /^[^\S\n]*[^\n]*?(?=[ \t]{2,}|\n|$)/.exec(tail)
    spans.push([blockStart(decoded, 0, firstStart, emojiIdxs), lastEnd + (value ? value[0].length : 0)])
  }

  let out = ''
  let kept = 0
  for (const [s, e] of spans) {
    out += decoded.slice(kept, s)
    kept = e
  }
  out += decoded.slice(kept)

  return out
    .replace(/^[ \t]+$/gm, '')   // lines reduced to whitespace
    .replace(/\n{3,}/g, '\n\n')  // no floating gaps where a block was removed
    .trim()
}
