// US county boundary geometry: types, viewport windowing, the canonical
// (state, county) join key, name normalization, and the eBird region-code
// derivation. The structural twin of `lib/atlasBlocks.ts` — counties are drawn
// for the CURRENT VIEWPORT only (countiesInBounds + a padded bbox, recomputed on
// `moveend`), and the keyboard "Counties in view" list is built from
// `countyListRows`. Pure + dependency-light so it unit-tests without the map.
//
// The geometry asset (frontend/src/assets/us-counties.json, generated by
// scripts/build-county-boundaries.mjs from US Census Cartographic Boundary
// Files — public domain) is dynamic-imported on first overlay enable, so it
// stays OFF the entry chunk (NFR-03). This module carries NO static import of
// that asset.

import type { Polygon, MultiPolygon } from 'geojson'
import { isWsChar } from './charClasses'

/** Map viewport as [minLng, minLat, maxLng, maxLat] (MapLibre LngLatBounds order). */
export type Bounds = [number, number, number, number]

export interface CountyProps {
  /** 5-digit FIPS = STATEFP(2) + COUNTYFP(3); the stable identity (FR-23). */
  geoid: string
  /** Bare county name (TIGER NAME field — no "County" suffix). */
  name: string
  /** 2-letter state postal code. */
  stusps: string
  /** 2-digit state FIPS. */
  statefp: string
}

export interface CountyFeature {
  type: 'Feature'
  /** [minLng, minLat, maxLng, maxLat] — precomputed by the build script so the
   *  runtime never derives a polygon bbox per `moveend`. */
  bbox: [number, number, number, number]
  properties: CountyProps
  geometry: Polygon | MultiPolygon
}

export interface CountyFC {
  type: 'FeatureCollection'
  features: CountyFeature[]
}

// ── Viewport windowing (mirrors atlasBlocks.padBounds / blocksInBounds) ────────

/** Do two bboxes overlap? (axis-aligned, [minLng,minLat,maxLng,maxLat]) */
export function bboxIntersects(a: Bounds, b: Bounds): boolean {
  return a[0] <= b[2] && a[2] >= b[0] && a[1] <= b[3] && a[3] >= b[1]
}

/**
 * Expand bounds by `frac` of their span on every side (e.g. 0.15 → 15% margin),
 * so viewport-capped layers regenerated on `moveend` don't pop in at the edges
 * during small pans. (Independent copy of the atlas helper to keep this module
 * decoupled.)
 */
export function padBounds(b: Bounds, frac: number): Bounds {
  const dLng = (b[2] - b[0]) * frac
  const dLat = (b[3] - b[1]) * frac
  return [b[0] - dLng, b[1] - dLat, b[2] + dLng, b[3] + dLat]
}

export interface CountiesInBoundsResult {
  /** Features intersecting the bounds (empty if tooMany). */
  features: CountyFeature[]
  /** True when the count would exceed `cap` — caller draws nothing and shows a
   *  "zoom in to see counties" hint. */
  tooMany: boolean
}

/**
 * Collect the county features whose bbox intersects `bounds`. If the count would
 * exceed `cap`, returns { features: [], tooMany: true } so the caller can show a
 * "Zoom in to see counties" hint instead of drawing thousands of polygons (the
 * full national zoom-out shows ~3,143 counties → over cap). A pure bbox-intersect
 * test — no polygon math, no point-in-polygon (FR-09).
 */
export function countiesInBounds(data: CountyFC, bounds: Bounds, cap: number): CountiesInBoundsResult {
  const out: CountyFeature[] = []
  for (const f of data.features) {
    if (!bboxIntersects(f.bbox, bounds)) continue
    out.push(f)
    if (out.length > cap) return { features: [], tooMany: true }
  }
  return { features: out, tooMany: false }
}

/** A county reduced to what the keyboard "Counties in view" list needs: identity
 *  plus the popup anchor (bbox centre, [lng, lat]). */
export interface CountyListRow {
  geoid: string
  name: string
  stusps: string
  /** [lng, lat] centre of the bbox — the popup anchor a list row opens. */
  center: [number, number]
}

/**
 * Reduce in-view county features to a sorted, capped list of rows for the
 * keyboard-accessible "Counties in view" panel (the only keyboard route to a
 * county popup — the on-map fill is a pointer-only canvas hit-test). Deduped by
 * `geoid` (a dateline-split borough is multiple features but one county), sorted
 * by name then state so the list is scannable, and capped like the marker lists
 * with an over-cap "zoom in" hint. Returns the pre-cap total too.
 */
export function countyListRows(features: CountyFeature[], cap: number): { rows: CountyListRow[]; total: number; overCap: boolean } {
  const seen = new Map<string, CountyFeature>()
  for (const f of features) if (!seen.has(f.properties.geoid)) seen.set(f.properties.geoid, f)
  const sorted = [...seen.values()].sort((a, b) =>
    a.properties.name.localeCompare(b.properties.name) || a.properties.stusps.localeCompare(b.properties.stusps))
  const rows = sorted.slice(0, cap).map(f => ({
    geoid: f.properties.geoid,
    name: f.properties.name,
    stusps: f.properties.stusps,
    center: [(f.bbox[0] + f.bbox[2]) / 2, (f.bbox[1] + f.bbox[3]) / 2] as [number, number],
  }))
  return { rows, total: sorted.length, overCap: sorted.length > cap }
}

// ── The canonical (state, county) join key (FR-10) ────────────────────────────

// The administrative suffixes a county name may carry, exactly as the
// alternation in the pattern this replaced listed them.
const ADMIN_SUFFIXES = [
  'county', 'parish', 'census area', 'borough', 'municipality',
  'city and borough', 'municipio',
] as const

/**
 * Drop a trailing whitespace-separated admin suffix - the linear replacement for
 * `/\s+(county|parish|census area|borough|municipality|city and borough|municipio)$/`
 * (improve: superlinear-regex-sweep).
 *
 * Why it is no longer a regex. `\s+` is unbounded and an alternation that can
 * fail follows it, so a name carrying a long whitespace run made the engine
 * consume that run and retry the alternation at every offset inside it, from
 * every start position: 2,496 ms on 40,000 spaces, 4.00x per doubling, measured
 * through `normalizeCountyName`. This site is amplified rather than incidental -
 * it runs once per observation from `countyShading` and `countyCompleteness`
 * over the CSV `County` column, which the parser does not cap.
 *
 * Equivalence. The pattern must reach `$`, so the alternative it matches is
 * whatever suffix the string ENDS with, preceded by at least one whitespace
 * character. `\s+` is greedy-then-backtracking and the overall match is
 * leftmost, so the cut lands at the START of the whitespace run before that
 * suffix. Two consequences the loop below reproduces deliberately:
 *   - Alternation ORDER cannot matter. Every alternative has to end at `$`, so
 *     at most one can equal the string's tail at a given cut point.
 *   - When two suffixes both fit ("city and borough" also ends with
 *     "borough"), leftmost-match picks the one whose whitespace run starts
 *     EARLIER, which is why this minimises the cut across all candidates rather
 *     than stopping at the first hit. Iterating longest-first would agree on
 *     today's list, but only by accident of that one nesting.
 */
function stripAdminSuffix(s: string): string {
  let cut = -1
  for (const suffix of ADMIN_SUFFIXES) {
    const at = s.length - suffix.length
    // `at > 0` leaves room for the whitespace the pattern requires; `at === 0`
    // (the string IS the suffix) has none, and never matched.
    if (at <= 0 || !s.endsWith(suffix)) continue
    let start = at
    while (start > 0 && isWsChar(s[start - 1])) start--
    if (start < at && (cut === -1 || start < cut)) cut = start
  }
  return cut === -1 ? s : s.slice(0, cut)
}

/** Lowercase, de-diacritic, strip admin suffixes, normalize Saint/St., collapse ws. */
export function normalizeCountyName(raw: string): string {
  // The surviving `\s+` below is unbounded, but nothing follows it in its
  // pattern, so there is no failure to backtrack into: measured flat. Only the
  // suffix strip was an instance of the defect.
  return stripAdminSuffix(
    raw
      .normalize('NFD').replace(/\p{Diacritic}/gu, '')                 // Doña Ana → Dona Ana
      .toLowerCase()
      .replace(/\bst\.?\b/g, 'saint').replace(/\bste\.?\b/g, 'sainte')
      .replace(/[.]/g, ''),
  )
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * STUSPS + normalized name → the join key. Same-named counties across states
 * ("Washington", "Jefferson") never conflate because the state is in the key.
 * STUSPS from the backup is the subnational1 code's 2nd segment:
 * "US-CA".split('-')[1] === "CA".
 */
export function countyKey(stusps: string, countyName: string): string {
  return `${stusps.toUpperCase()}|${normalizeCountyName(countyName)}`
}

/**
 * The backup's `stateProvince` is the eBird subnational1 code ("US-CA"). Returns
 * the join key only for US states (FR-26: non-US counties get no key → never
 * shaded); null otherwise.
 */
export function countyKeyFromState(stateProvince: string | null | undefined, countyName: string | null | undefined): string | null {
  if (!stateProvince || !countyName) return null
  const parts = stateProvince.split('-')
  if (parts[0] !== 'US' || !parts[1]) return null
  return countyKey(parts[1], countyName)
}

// ── eBird region-code derivation (FR-17, NFR-08) ──────────────────────────────

const COUNTY_REGION_RE = /^US-[A-Z]{2}-\d{3}$/

/**
 * GEOID "06097" + STUSPS "CA" → "US-CA-097", shape-validated; null when the geoid
 * is malformed (non-US / unresolved). The popup links the name to
 * `ebird.org/region/<code>` only when this is non-null — never a styled 404 link.
 */
export function deriveCountyRegionCode(geoid: string, stusps: string): string | null {
  if (!/^\d{5}$/.test(geoid)) return null
  const code = `US-${stusps.toUpperCase()}-${geoid.slice(-3)}` // last 3 = COUNTYFP
  return COUNTY_REGION_RE.test(code) ? code : null
}

// ── Full state names for the popup subtitle (offline, no fetch) ────────────────

/** 2-letter postal code → full state/DC name (the popup's State/Province line). */
export const US_STATE_NAMES: Record<string, string> = {
  AL: 'Alabama', AK: 'Alaska', AZ: 'Arizona', AR: 'Arkansas', CA: 'California',
  CO: 'Colorado', CT: 'Connecticut', DE: 'Delaware', DC: 'District of Columbia',
  FL: 'Florida', GA: 'Georgia', HI: 'Hawaii', ID: 'Idaho', IL: 'Illinois',
  IN: 'Indiana', IA: 'Iowa', KS: 'Kansas', KY: 'Kentucky', LA: 'Louisiana',
  ME: 'Maine', MD: 'Maryland', MA: 'Massachusetts', MI: 'Michigan', MN: 'Minnesota',
  MS: 'Mississippi', MO: 'Missouri', MT: 'Montana', NE: 'Nebraska', NV: 'Nevada',
  NH: 'New Hampshire', NJ: 'New Jersey', NM: 'New Mexico', NY: 'New York',
  NC: 'North Carolina', ND: 'North Dakota', OH: 'Ohio', OK: 'Oklahoma', OR: 'Oregon',
  PA: 'Pennsylvania', RI: 'Rhode Island', SC: 'South Carolina', SD: 'South Dakota',
  TN: 'Tennessee', TX: 'Texas', UT: 'Utah', VT: 'Vermont', VA: 'Virginia',
  WA: 'Washington', WV: 'West Virginia', WI: 'Wisconsin', WY: 'Wyoming',
}

export function stateNameFor(stusps: string): string {
  return US_STATE_NAMES[stusps.toUpperCase()] ?? stusps
}
