// Guard for improve: statistics-compute-off-thread.
//
// The Statistics tab's derivation chain moved out of a cascade of ~15 `useMemo`s in
// `components/BirdingStats.tsx` and into one pure function, so it can run in a
// worker. THE WHOLE POINT IS THAT NOTHING CHANGES, and "nothing changes" over a
// page of forty-odd figures, six ranked tables and five charts is not something a
// human eye is going to confirm by looking at it twice.
//
// So the pre-change cascade is written out here, verbatim, in the order and with
// the arguments `BirdingStats.tsx` used at 1.0.19 — and asserted equal to the
// bundle, field by field, across BOTH count rules and ALL FOUR accumulation
// granularities. If someone later "tidies" an argument in `statsBundle.ts` (feeds
// `computeGeo` the raw observations instead of the filtered ones, drops the
// escapee set from the second accumulation pass, reorders a call so a downstream
// consumer sees a different array), this is what says so.
//
// The fixture is deliberately awkward: forms the count rule drops, an escapee, a
// checklist whose only row is a spuh, several years and months, two same-named
// counties in different states, durations in and out of range, comment blocks, a
// breeding code, and an X count. A fixture that exercised only the easy path would
// let a swapped argument through.
import { describe, it, expect } from 'vitest'
import type { ObservationEntry } from '../types'
import {
  filterObservations, computeChecklists, computeLifeList, computeTopSpecies,
  computeTotals, computeAccumulation, computeTemporal, computeDurationBins,
  computeGeo, computeEffort, computeQuality, computeBreedingStats, computeFunStats,
} from './birdingStats'
import type { Granularity } from './birdingStats'
import { computeStatsBundle, EMPTY_STATS_BUNDLE } from './statsBundle'

function obs(p: Partial<ObservationEntry> & { submissionId: string; commonName: string; date: string }): ObservationEntry {
  return {
    scientificName: 'Sci name',
    location: 'Loc', locationId: 'L1',
    latitude: 44.9, longitude: -93.2, county: 'Hennepin',
    stateProvince: 'US-MN',
    count: 1, breedingCode: null, speciesComments: '', catalogIds: [],
    time: '07:30 AM', duration: 45, distance: 1.5, area: null,
    protocol: 'Traveling', numObservers: 1, allObsReported: true,
    checklistComments: '',
    ...p,
  }
}

// A real SnowRaven weather block's shape: two of the body markers plus the
// attribution line `hasSnowravenWeatherBlock` identifies it by. A hand-waved
// stand-in would count as no block at all and the assertion below would be
// asserting nothing.
const SNOWRAVEN_WEATHER = 'Temperature: 12C\nWind: 5 mph\nWeather generated by SnowRaven'

const FIXTURE: ObservationEntry[] = [
  // 2023, Hennepin US-MN — a full checklist with a weather block and a breeding code
  obs({ submissionId: 'S1', commonName: 'American Robin', date: '2023-04-02', count: 4, checklistComments: SNOWRAVEN_WEATHER, breedingCode: 'NY' }),
  obs({ submissionId: 'S1', commonName: 'Mallard', date: '2023-04-02', count: 12, speciesComments: 'on the pond' }),
  obs({ submissionId: 'S1', commonName: 'gull sp.', date: '2023-04-02', count: 3 }),
  obs({ submissionId: 'S1', commonName: 'Egyptian Goose', date: '2023-04-02', count: 2 }),

  // consecutive day, so there is a streak to find
  obs({ submissionId: 'S2', commonName: 'American Robin', date: '2023-04-03', count: null, duration: 200, distance: 6, numObservers: 3, location: 'Two', locationId: 'L2', latitude: 45.1, longitude: -93.9 }),
  obs({ submissionId: 'S2', commonName: 'Canada Goose (moffitti/maxima)', date: '2023-04-03', count: 30, location: 'Two', locationId: 'L2' }),

  // a same-named county in ANOTHER state, which must stay a distinct row
  obs({ submissionId: 'S3', commonName: 'Northern Cardinal', date: '2023-07-14', county: 'Hennepin', stateProvince: 'US-ND', location: 'Three', locationId: 'L3', duration: 1500, protocol: 'Stationary', allObsReported: false }),

  // a checklist whose ONLY row is dropped by the count rule
  obs({ submissionId: 'S4', commonName: 'hawk sp.', date: '2023-09-01', location: 'Four', locationId: 'L4' }),

  // a later year, a long gap before it (the dry spell), area instead of distance
  obs({ submissionId: 'S5', commonName: 'Snowy Owl', date: '2025-01-20', count: 1, distance: null, area: 8, protocol: 'Area', numObservers: 6, checklistComments: SNOWRAVEN_WEATHER }),
  obs({ submissionId: 'S5', commonName: "Brewster's Warbler (hybrid)", date: '2025-01-20', count: 1 }),
  obs({ submissionId: 'S5', commonName: 'American Robin', date: '2025-01-20', count: 7 }),
  obs({ submissionId: 'S5', commonName: 'Mandarin Duck', date: '2025-01-20', count: 1 }),

  // a middle year, and enough species that the life list crosses the first
  // milestone threshold (10) — without it the milestone map is empty and the
  // accumulation assertions have nothing to compare
  obs({ submissionId: 'S7', commonName: 'Barred Owl', date: '2024-05-11', count: 1, location: 'Five', locationId: 'L5', county: 'Ramsey', duration: 90, protocol: 'Traveling', numObservers: 2 }),
  obs({ submissionId: 'S7', commonName: 'Wood Duck', date: '2024-05-11', count: 6, location: 'Five', locationId: 'L5', county: 'Ramsey' }),
  obs({ submissionId: 'S7', commonName: 'Great Blue Heron', date: '2024-05-11', count: 2, location: 'Five', locationId: 'L5', county: 'Ramsey' }),
  obs({ submissionId: 'S7', commonName: 'Sandhill Crane', date: '2024-05-11', count: 9, location: 'Five', locationId: 'L5', county: 'Ramsey' }),
  obs({ submissionId: 'S7', commonName: 'Trumpeter Swan', date: '2024-05-11', count: 3, location: 'Five', locationId: 'L5', county: 'Ramsey' }),
  obs({ submissionId: 'S7', commonName: 'Bald Eagle', date: '2024-05-11', count: 1, location: 'Five', locationId: 'L5', county: 'Ramsey' }),

  // a duration outside eBird's own 24 h cap, which the bins must treat as absent
  obs({ submissionId: 'S6', commonName: 'Sora', date: '2025-06-30', duration: 99999, time: '11:15 PM', county: null, stateProvince: null }),
]

/** The escapee set the provenance pass publishes, in the two shapes that matter. */
const EXCLUDED_CASES: Array<[label: string, names: string[]]> = [
  ['no escapees resolved', []],
  ['two escapees resolved', ['Egyptian Goose', 'Mandarin Duck']],
]

const GRANULARITIES: Granularity[] = ['total', 'weekly', 'monthly', 'yearly']

/** `BirdingStats.tsx` at 1.0.19, transcribed: the same calls, in the same order,
 *  with the same arguments. Nothing here may be "simplified" — its whole value is
 *  being an independent copy of the wiring under test. */
function cascadeAt_1_0_19(
  rawObs: ObservationEntry[],
  includeSpuh: boolean,
  accGranularity: Granularity,
  excludedNames: ReadonlySet<string>,
) {
  const filteredObs = filterObservations(rawObs, includeSpuh)
  const checklists = computeChecklists(filteredObs)
  const lifeList = computeLifeList(filteredObs)
  const topSpecies = computeTopSpecies(filteredObs)
  const totals = computeTotals(checklists, lifeList)
  const all = computeAccumulation(filteredObs, accGranularity)
  const accumulationPair = {
    all,
    countable: excludedNames.size === 0
      ? all
      : computeAccumulation(filteredObs, accGranularity, excludedNames),
  }
  return {
    filteredObs,
    checklists,
    lifeList,
    topSpecies,
    totals,
    accumulationPair,
    temporal: computeTemporal(checklists, filteredObs),
    durationBins: computeDurationBins(checklists),
    geo: computeGeo(checklists, filteredObs),
    effort: computeEffort(checklists),
    quality: computeQuality(filteredObs, checklists),
    breedingStats: computeBreedingStats(filteredObs),
    funStats: computeFunStats(filteredObs, checklists, rawObs),
  }
}

describe('the bundle is the 1.0.19 cascade, figure for figure', () => {
  for (const [exLabel, names] of EXCLUDED_CASES) {
    for (const includeSpuh of [false, true]) {
      for (const granularity of GRANULARITIES) {
        it(`matches with includeSpuh=${includeSpuh}, ${granularity}, ${exLabel}`, () => {
          const excludedNames = new Set(names)
          const before = cascadeAt_1_0_19(FIXTURE, includeSpuh, granularity, excludedNames)
          const after = computeStatsBundle(FIXTURE, {
            includeSpuh, granularity,
            // The request carries a SORTED array; the bundle rebuilds the Set. A
            // reversed input here is deliberate — it proves the sort is not load
            // bearing for correctness, only for the cache key.
            excludedNames: [...names].reverse(),
          })

          expect(after.includeSpuh).toBe(includeSpuh)
          expect(after.granularity).toBe(granularity)
          expect(after.filteredCount).toBe(before.filteredObs.length)
          expect(after.checklists).toEqual(before.checklists)
          expect(after.lifeList).toEqual(before.lifeList)
          expect(after.topSpecies).toEqual(before.topSpecies)
          expect(after.totals).toEqual(before.totals)
          expect(after.accumulationAll).toEqual(before.accumulationPair.all)
          expect(after.accumulationCountable).toEqual(before.accumulationPair.countable)
          expect(after.temporal).toEqual(before.temporal)
          expect(after.durationBins).toEqual(before.durationBins)
          expect(after.geo).toEqual(before.geo)
          expect(after.effort).toEqual(before.effort)
          expect(after.quality).toEqual(before.quality)
          expect(after.breedingStats).toEqual(before.breedingStats)
          expect(after.funStats).toEqual(before.funStats)
        })
      }
    }
  }

  // Non-vacuity. Every assertion above would hold between two runs over an empty
  // fixture, so the fixture has to be shown to produce a page worth checking.
  it('the fixture exercises the figures those assertions are about', () => {
    const b = computeStatsBundle(FIXTURE, { includeSpuh: false, granularity: 'yearly', excludedNames: [] })
    expect(b.checklists).toHaveLength(6)            // S4 is spuh-only and drops out
    expect(b.filteredCount).toBeLessThan(FIXTURE.length)
    expect(b.lifeList.length).toBeGreaterThan(4)
    expect(b.totals.yearCount).toBe(3)
    expect(b.totals.stateCount).toBe(2)
    // Two "Hennepin" rows, one per state — the composite-key correctness case.
    expect(b.geo.topCounties.filter(c => c.name === 'Hennepin')).toHaveLength(2)
    expect(b.effort.longest).not.toBeNull()
    expect(b.breedingStats.total).toBeGreaterThan(0)
    expect(b.quality.snowravenWeatherCount).toBe(2)
    expect(b.quality.xCount).toBeGreaterThan(0)
    expect(b.funStats.maxStreak).toBe(2)
    expect(b.funStats.drySpell).toBeGreaterThan(0)
    expect(b.temporal.yearRows.length).toBe(3)
    expect(b.accumulationAll.milestones.size).toBeGreaterThan(0)
    // The out-of-range duration is excluded from the bins but the checklist is not
    // excluded from the count — the shipped `computeDurationBins` contract.
    expect(b.durationBins.durationCount).toBeLessThan(b.durationBins.totalCount)
  })

  // The count rule and the escapee rule really do move the numbers, so the eight
  // parameterized cases above are eight different comparisons rather than one
  // repeated eight times.
  it('the two rules the request carries actually change the answer', () => {
    const off = computeStatsBundle(FIXTURE, { includeSpuh: false, granularity: 'total', excludedNames: [] })
    const on = computeStatsBundle(FIXTURE, { includeSpuh: true, granularity: 'total', excludedNames: [] })
    expect(on.checklists.length).toBeGreaterThan(off.checklists.length)
    expect(on.lifeList.length).toBeGreaterThan(off.lifeList.length)

    const excl = computeStatsBundle(FIXTURE, {
      includeSpuh: false, granularity: 'total', excludedNames: ['Egyptian Goose', 'Mandarin Duck'],
    })
    // The running life-list total at the last lifer date, which is the figure the
    // headline Species tile and the accumulation chart's y-axis both read. NOT the
    // number of liferPoints: those are keyed by DATE, and both escapees here share
    // a date with a countable bird, so the point count is identical either way —
    // which is exactly the kind of near-miss assertion that passes forever without
    // testing anything.
    const lastCount = (a: { liferPoints: { count: number }[] }) => a.liferPoints.at(-1)!.count
    expect(lastCount(excl.accumulationCountable)).toBe(lastCount(excl.accumulationAll) - 2)
  })

  // With nothing excluded the second series IS the first, by reference. That is the
  // precompute-both-select-at-read shape (NFR-02) surviving the move across the
  // worker boundary: an unresolved provenance cache costs one comparison, not a
  // second full chronological pass.
  it('an empty escapee set shares one accumulation pass between both series', () => {
    const b = computeStatsBundle(FIXTURE, { includeSpuh: false, granularity: 'total', excludedNames: [] })
    expect(b.accumulationCountable).toBe(b.accumulationAll)
    const withExcl = computeStatsBundle(FIXTURE, {
      includeSpuh: false, granularity: 'total', excludedNames: ['Egyptian Goose'],
    })
    expect(withExcl.accumulationCountable).not.toBe(withExcl.accumulationAll)
  })

  // The shell pass. Before this change the tab fed its memo cascade a stable
  // `EMPTY_OBS` until the first frame had painted; this constant is that same pass,
  // computed once at module scope, and the tab renders it while the real bundle is
  // in flight. If it ever stopped matching, the shell would paint different numbers
  // from the ones 1.0.19 painted there.
  it('the empty bundle is the empty cascade', () => {
    const before = cascadeAt_1_0_19([], false, 'total', new Set())
    expect(EMPTY_STATS_BUNDLE.checklists).toEqual(before.checklists)
    expect(EMPTY_STATS_BUNDLE.totals).toEqual(before.totals)
    expect(EMPTY_STATS_BUNDLE.geo).toEqual(before.geo)
    expect(EMPTY_STATS_BUNDLE.effort).toEqual(before.effort)
    expect(EMPTY_STATS_BUNDLE.temporal).toEqual(before.temporal)
    expect(EMPTY_STATS_BUNDLE.funStats).toEqual(before.funStats)
    expect(EMPTY_STATS_BUNDLE.filteredCount).toBe(0)
  })

  // Serializability is a REQUIREMENT of this module, not a property it happens to
  // have: the bundle's whole purpose is to cross a worker boundary. A `Map` (two
  // of them are in here) survives structured clone; a function or a class instance
  // would not, and would surface as a `messageerror` at runtime rather than as a
  // type error at build.
  it('every request and every bundle survives a structured clone', () => {
    const request = { includeSpuh: false, granularity: 'weekly' as const, excludedNames: ['Egyptian Goose'] }
    expect(structuredClone(request)).toEqual(request)
    const b = computeStatsBundle(FIXTURE, request)
    const round = structuredClone(b)
    expect(round).toEqual(b)
    // Named explicitly: the two Maps are the fields most likely to be "simplified"
    // into something unclonable later.
    expect(round.accumulationAll.milestones).toBeInstanceOf(Map)
    expect(round.effort.protocolComplete).toBeInstanceOf(Map)
    expect([...round.accumulationAll.milestones.entries()])
      .toEqual([...b.accumulationAll.milestones.entries()])
  })
})
