// Taxonomic splits and lumps (taxonomic-splits-lumps): the asset's types and the
// derivation over the loaded backup. Pure: no React, no I/O, no Date.now(), no
// transport, no storage (schema.md section 6).
//
// The asset (`assets/ebird-taxonomy-history.json`) is a bundled BUILD-TIME
// artifact, generated by `scripts/build-taxonomy-history.mjs` and held to the
// bundled taxonomy snapshot by `taxonomyHistoryAsset.test.ts`. It is defended at
// build and CI time, never validated per entry at runtime (CLAUDE.md: a
// Vite-inlined JSON import is a different trust boundary from a persisted cache).
// The types below are the contract; the JSON is their literal form.
//
// ONE RULE, ONE RENDERER (NFR-07): countability is decided only by the shared
// `isNonCountableForm`, parent folding only by the shared `normalizeSpeciesName`,
// and code resolution only by the page's existing `/taxonomy/codes` result plus
// the asset-name fallback below. Nothing here classifies a name on its own.
//
// DECLARED SCAN OVER USER FILE CONTENT (schema.md 6.6, security.md v1.0.23):
// `buildTaxonomyHistoryIndex` visits every row once. Per row it does one
// `isNonCountableForm`, one `normalizeSpeciesName` (memoized), one `Map.get` on
// the raw or merged name, and per matched entry one lexical compare against a
// 10-character constant. No nested scan, no regex over the name, no
// `includes` / `indexOf` / `find` in the loop, so the pass is O(sum of row string
// lengths). Key resolution runs once per DISTINCT merged key (cached in
// `entriesByKey`), each a handful of hash lookups plus, for a retired name only,
// `midChainTier0`. Then, once per AFFECTED key, `lineageEvents` walks each
// matched entry's line, visiting each event at most once per direction. Both
// per-key walks are bounded by the asset, never by the file, so the total is
// O(distinct keys x the asset's chain bound): linear in the rows (schema.md 6.6,
// corrected at the security review). Measured linear through this entry point,
// including a hostile leg of 4,000-character names and dates and a leg where
// every row is a distinct affected key over the real asset, in
// `taxonomyHistory.test.ts`.
//
// MEMORY: the index retains per entry three integers and one key reference, per
// distinct key one small array of entry ids, and nothing per row. It is an
// in-memory derived value keyed on a user data file, so it is OUTSIDE
// `clearDerived.ts` by design (that registry holds on-disk documents only): what
// terminates it is the page's memo, whose `observations` dependency changes on
// every new load, leaving the old index unreachable.

import type { ObservationEntry } from '../types'
import { normalizeSpeciesName, isNonCountableForm } from './speciesUtils'
import { SPECIES_CODE_RE } from './speciesCode'

// ── The asset contract (schema.md 3.2) ─────────────────────────────────────────

export interface TaxonomyHistory {
  /** Asset schema version. A different value is a load failure (FR-28). */
  v: 1
  /** `version` of the bundled taxonomy snapshot every current-side code was
   *  resolved against. CI asserts equality with the snapshot. */
  snapshot: string
  /** ISO date the generator ran. Provenance only. */
  generated: string
  /** The input files the generator read, by basename. Provenance only. */
  inputs: string[]
  /** Every update the asset covers, ascending. An update with zero events is
   *  never listed, so coverage never claims a year the generator could not read. */
  updates: HistoryUpdate[]
  /** First and last of `updates`, or null when `updates` is empty. */
  coverage: { earliest: HistoryUpdate; latest: HistoryUpdate } | null
  /** Ascending by `published`, then by the before side's first scientific name. */
  events: HistoryEvent[]
}

export interface HistoryUpdate {
  /** eBird/Clements update year, e.g. 2025. */
  year: number
  /** The day eBird announced the update complete, YYYY-MM-DD. */
  published: string
}

export interface HistoryEvent {
  kind: 'split' | 'lump'
  year: number
  published: string
  /** A split has exactly one; a lump has two or more. */
  before: HistoryBeforeEntry[]
  /** A split has two or more; a lump has exactly one. */
  after: HistoryEntry[]
  /** Slash taxa the split created. Empty for a lump. */
  slashes: HistoryEntry[]
}

export interface HistoryEntry {
  code: string
  sci: string
  com: string
}

export interface HistoryBeforeEntry extends HistoryEntry {
  /** true when `com` is NOT a species common name in the bundled snapshot: the
   *  tier-0 gate below (only a retired common name is evidence of an export made
   *  before the update). */
  retired: boolean
}

// ── The derivation's inputs and output (schema.md 6.1, 6.4) ──────────────────

export interface HistoryCodeLookup {
  /** The page's existing `/taxonomy/codes` result, keyed by the name AS SENT.
   *  Read only through Object.hasOwn: a species name out of the CSV is an
   *  external-string key (security.md v0.5.81). Empty when the batch failed or has
   *  not landed; only the name tiers then apply. */
  codes: Readonly<Record<string, string>>
}

export interface AffectedEvent {
  eventIndex: number
  kind: 'split' | 'lump'
  year: number
  /** True when the user's rows under this key matched the event itself; false
   *  when the event is reached only through the chain (FR-03, FR-15). */
  direct: boolean
}

export interface AffectedSpecies {
  key: string
  /** Every event that touches the key, directly or through the chain, in date
   *  order ascending. The list shows these most recent first; the section shows
   *  them earliest first. */
  events: readonly AffectedEvent[]
}

export interface EntryView {
  code: string
  sci: string
  com: string
  /** Rows matched to this entry in the FULL backup. 0 = no reports under it. */
  count: number
  /** Rows dated on or before the update's published day. */
  onOrBefore: number
  /** Rows dated after it. Always `count - onOrBefore`. */
  after: number
  /** The merged key whose rows matched this entry (first seen wins), or null when
   *  `count` is 0 or the entry is a slash. */
  speciesKey: string | null
  /** True only for an after-side entry whose code is still a species after every
   *  covered update: the one kind of entry that may carry the eBird and Birds of
   *  the World marks (FR-23). False for an after code a later update retired
   *  (Macquarie Parakeet's `recpar23`), and always false on the before side and
   *  for a slash. See `currentAfterCode` in `buildTaxonomyHistoryIndex`. */
  current: boolean
}

export interface EventView {
  kind: 'split' | 'lump'
  year: number
  published: string
  before: readonly EntryView[]
  after: readonly EntryView[]
  /** Only the slashes the user holds rows under (count > 0). */
  slashes: readonly EntryView[]
  /** FR-19: some before entry has count > 0 and every after entry has count 0. */
  predates: boolean
}

export interface TaxonomyHistoryIndex {
  coverage: TaxonomyHistory['coverage']
  /** Merged keys that matched at least one entry, in first-seen order. */
  affected: ReadonlyMap<string, AffectedSpecies>
  /** Every event, with per-entry tallies attached, index-addressable. */
  events: readonly EventView[]
}

/** One row of the list control (FR-11): events most recent first. */
export interface HistoryListEntry {
  species: string
  events: readonly { kind: 'split' | 'lump'; year: number }[]
}

// ── Implementation ─────────────────────────────────────────────────────────────

type Side = 'before' | 'after' | 'slash'

interface EntrySlot {
  event: number
  side: Side
  entry: HistoryEntry
  count: number
  onOrBefore: number
  speciesKey: string | null
}

const lower = (s: string) => s.toLowerCase()

function pushTo<K>(map: Map<K, number[]>, key: K, id: number): void {
  const list = map.get(key)
  if (list) list.push(id)
  else map.set(key, [id])
}

/** Per event, keep the after-side candidates when any exist, else the before-side
 *  ones: the sci-name step's precedence (schema.md 6.2 tier 2), applied per event
 *  so a chained lineage keeps its match on both of its events. */
function preferAfterPerEvent(ids: readonly number[], slots: readonly EntrySlot[]): number[] {
  const byEvent = new Map<number, number[]>()
  for (const id of ids) pushTo(byEvent, slots[id].event, id)
  const out: number[] = []
  for (const list of byEvent.values()) {
    const after = list.filter(id => slots[id].side === 'after')
    out.push(...(after.length > 0 ? after : list))
  }
  return out
}

/**
 * The index over the full backup (schema.md section 6). Filters and toggles are
 * structurally not inputs (FR-09, FR-24), so the page memoizes this on the
 * observations array, the loaded asset and the codes result only.
 */
export function buildTaxonomyHistoryIndex(
  observations: readonly ObservationEntry[],
  history: TaxonomyHistory,
  lookup: HistoryCodeLookup,
): TaxonomyHistoryIndex {
  // ── Entry slots and the asset-side indexes (O(events x entries), once) ──
  const slots: EntrySlot[] = []
  const eventSlots: { before: number[]; after: number[]; slashes: number[] }[] = []
  const retiredByCom = new Map<string, number[]>()   // tier 0
  const afterByCode = new Map<string, number[]>()    // tier 1
  const beforeByCode = new Map<string, number[]>()   // tier 1 (only where no after has it)
  const byPair = new Map<string, number[]>()         // tier 2, (sci, com)
  const bySci = new Map<string, number[]>()          // tier 2, sci alone
  const byCom = new Map<string, number[]>()          // tier 2, com alone
  const slashByRawName = new Map<string, number[]>() // FR-08's exact-name exception

  history.events.forEach((ev, e) => {
    const mk = (entry: HistoryEntry, side: Side): number => {
      slots.push({ event: e, side, entry, count: 0, onOrBefore: 0, speciesKey: null })
      return slots.length - 1
    }
    const before = ev.before.map(b => mk(b, 'before'))
    const after = ev.after.map(a => mk(a, 'after'))
    const slashes = ev.slashes.map(s => mk(s, 'slash'))
    eventSlots.push({ before, after, slashes })

    const afterCodes = new Set(ev.after.map(a => a.code))
    before.forEach((id, i) => {
      const b = ev.before[i]
      if (b.retired) pushTo(retiredByCom, lower(b.com), id)
      if (!afterCodes.has(b.code)) pushTo(beforeByCode, b.code, id)
    })
    for (const id of after) pushTo(afterByCode, slots[id].entry.code, id)
    for (const id of [...before, ...after]) {
      const { sci, com } = slots[id].entry
      pushTo(byPair, `${lower(sci)}\u0000${lower(com)}`, id)
      pushTo(bySci, lower(sci), id)
      pushTo(byCom, lower(com), id)
    }
    for (const id of slashes) pushTo(slashByRawName, slots[id].entry.com, id)
  })

  /**
   * Tier 0 on a chain (QA fix errand 2). A retired name is the name the export
   * was made under, so a row carrying it PREDATES the update that retired it and
   * matches that update's before-side entry. But the name was CURRENT after any
   * EARLIER covered update whose after side carries the same code: an export
   * made between the two updates carries it (Macquarie Parakeet, current after
   * the 2023 split and lumped in 2024). So the row also matches each such earlier
   * after-side entry, by code (the after entry carries today's name, which may
   * differ from the export's, e.g. South Papuan Pitta shown as Papuan Pitta),
   * and at that earlier event it is an after-side row, not a before-side one:
   * where the same event also matched on its before side (a name the split KEPT,
   * like Slender-billed Crow in 2023), the after entry wins, one entry per event.
   * Each event's partition and its FR-19 "predates" reading then follow from the
   * row's side at THAT event: a 1 March 2024 Slender-billed Crow row is
   * "recorded since" at the 2023 split and predates only the 2024 update.
   *
   * Stated limit, the same kind as schema.md 6.2's: at an update that KEPT the
   * name (Slender-billed Crow, 2023), a backup exported BEFORE that update
   * carries the same name, and such a row is read as an export made after it.
   */
  const midChainTier0 = (matched: readonly number[]): number[] => {
    const ids = new Set(matched)
    for (const id of matched) {
      const { event, entry } = slots[id]
      for (const a of afterByCode.get(entry.code) ?? []) {
        if (history.events[slots[a].event].published < history.events[event].published) ids.add(a)
      }
    }
    const afterEvents = new Set([...ids].filter(id => slots[id].side === 'after').map(id => slots[id].event))
    return [...ids].filter(id => slots[id].side === 'after' || !afterEvents.has(slots[id].event))
  }

  // ── Key resolution (schema.md 6.2), once per distinct merged key ──
  const resolve = (key: string, sci: string): number[] => {
    // Tier 0: a retired before-side common name is direct evidence of an export
    // made before the update that retired it (finding 2.2), so it wins before
    // any code runs.
    const t0 = retiredByCom.get(lower(key))
    if (t0) return midChainTier0(t0)

    // Tier 1: the current code the page already resolved.
    const code = Object.hasOwn(lookup.codes, key) ? lookup.codes[key] : undefined
    if (typeof code === 'string' && SPECIES_CODE_RE.test(code)) {
      return [...(afterByCode.get(code) ?? []), ...(beforeByCode.get(code) ?? [])]
    }

    // Tier 2: only when tier 1 yielded no code at all. Pair, then sci, then com;
    // the scientific name wins over a conflicting common name.
    const pair = byPair.get(`${lower(sci)}\u0000${lower(key)}`)
    if (pair) return preferAfterPerEvent(pair, slots)
    const s = bySci.get(lower(sci))
    if (s) return preferAfterPerEvent(s, slots)
    const c = byCom.get(lower(key))
    if (c) return preferAfterPerEvent(c, slots)
    return []
  }

  const tally = (id: number, date: string, key: string | null): void => {
    const slot = slots[id]
    slot.count += 1
    // Lexical compare of YYYY-MM-DD strings, the page's own date-filter
    // convention; a row dated exactly on the published day is on-or-before.
    if (date <= history.events[slot.event].published) slot.onOrBefore += 1
    if (key !== null && slot.speciesKey === null) slot.speciesKey = key
  }

  // ── The row pass (schema.md 6.3): every row visited once ──
  const entriesByKey = new Map<string, number[]>()
  for (const o of observations) {
    if (isNonCountableForm(o.commonName)) {
      const ids = slashByRawName.get(o.commonName)
      if (ids) for (const id of ids) tally(id, o.date, null)
      continue
    }
    const key = normalizeSpeciesName(o.commonName)
    let ids = entriesByKey.get(key)
    if (ids === undefined) {
      ids = resolve(key, o.scientificName)
      entriesByKey.set(key, ids)
    }
    for (const id of ids) tally(id, o.date, key)
  }

  // ── The chain (FR-03, FR-15), over the asset alone ──
  // Which events carry each code on each side. A lineage is walked from the
  // matched entry in ONE direction at a time (lineageEvents below).
  const withBefore = new Map<string, number[]>()
  const withAfter = new Map<string, number[]>()
  history.events.forEach((ev, e) => {
    for (const b of ev.before) pushTo(withBefore, b.code, e)
    for (const a of ev.after) pushTo(withAfter, a.code, e)
  })
  const published = (e: number) => history.events[e].published

  /**
   * Whether an after-side code is still a species (security review L1). Asset
   * invariant I5 admits an after code that is no longer a species when a LATER
   * covered update carries it on its before side (the chain), and I6 requires a
   * before code that IS still a species to be kept on its own event's after
   * side. So a code is current exactly when the latest update that carries it
   * has it on an after side. Retired: Macquarie Parakeet (`recpar23`), after in
   * 2023, before only in 2024. Kept: Red-crowned Parakeet (`refpar4`), after in
   * 2023, before AND after in 2024. The shorter test "never on a later before
   * side" would wrongly drop the kept code's links, so it is not used.
   * `taxonomyHistoryAsset.test.ts` holds this to the snapshot over the whole
   * committed asset. Asset only, O(events x entries), once per index build.
   */
  const lastSeen = new Map<string, { published: string; onAfter: boolean }>()
  for (const ev of history.events) {
    const mark = (code: string, onAfter: boolean): void => {
      const prev = lastSeen.get(code)
      if (prev === undefined || ev.published > prev.published) lastSeen.set(code, { published: ev.published, onAfter })
      else if (ev.published === prev.published && onAfter) prev.onAfter = true
    }
    for (const b of ev.before) mark(b.code, false)
    for (const a of ev.after) mark(a.code, true)
  }
  const currentAfterCode = (code: string): boolean => lastSeen.get(code)?.onAfter === true

  /**
   * The events on ONE entry's own line of descent (FR-11, FR-15: "every covered
   * event that touches" the species). Forward, the line runs through the entry
   * itself (an after entry) or through its event's after side (a before entry,
   * whose reports went there), then through each later event that takes one of
   * those codes on its before side, and on through that event's after side.
   * Backward, it runs through the entry itself (a before entry) or its event's
   * before side (an after entry came from those), then through each earlier
   * event that produced one of those codes. The walk NEVER turns around: a
   * daughter does not inherit a sibling's later change, and a lump's co-parent
   * does not inherit its partner's earlier split. schema.md 6.5 closed over
   * links in both directions at once, which is the whole connected component
   * and attached a sibling's later split to a species it never touched
   * (decisions.md, Stage 5 QA fix 1).
   */
  const lineageEvents = (id: number, out: Set<number>): void => {
    const slot = slots[id]
    const e = slot.event
    out.add(e)
    const ev = history.events[e]
    const forwardFrom = slot.side === 'before' ? ev.after.map(a => a.code) : [slot.entry.code]
    const backwardFrom = slot.side === 'before' ? [slot.entry.code] : ev.before.map(b => b.code)

    const fwdSeen = new Set<number>()
    const fwd: [string, string][] = forwardFrom.map(c => [c, ev.published])
    while (fwd.length > 0) {
      const [code, t] = fwd.pop()!
      for (const f of withBefore.get(code) ?? []) {
        if (published(f) <= t || fwdSeen.has(f)) continue
        fwdSeen.add(f)
        out.add(f)
        for (const a of history.events[f].after) fwd.push([a.code, published(f)])
      }
    }

    const bwdSeen = new Set<number>()
    const bwd: [string, string][] = backwardFrom.map(c => [c, ev.published])
    while (bwd.length > 0) {
      const [code, t] = bwd.pop()!
      for (const g of withAfter.get(code) ?? []) {
        if (published(g) >= t || bwdSeen.has(g)) continue
        bwdSeen.add(g)
        out.add(g)
        for (const b of history.events[g].before) bwd.push([b.code, published(g)])
      }
    }
  }

  const events: EventView[] = history.events.map((ev, e) => {
    const view = (id: number): EntryView => {
      const s = slots[id]
      return {
        code: s.entry.code, sci: s.entry.sci, com: s.entry.com,
        count: s.count, onOrBefore: s.onOrBefore, after: s.count - s.onOrBefore,
        speciesKey: s.side === 'slash' || s.count === 0 ? null : s.speciesKey,
        current: s.side === 'after' && currentAfterCode(s.entry.code),
      }
    }
    const before = eventSlots[e].before.map(view)
    const after = eventSlots[e].after.map(view)
    const slashes = eventSlots[e].slashes.map(view).filter(v => v.count > 0)
    return {
      kind: ev.kind, year: ev.year, published: ev.published,
      before, after, slashes,
      predates: before.some(b => b.count > 0) && after.every(a => a.count === 0),
    }
  })

  // ── Affected keys: the direct events plus each matched entry's own line ──
  const affected = new Map<string, AffectedSpecies>()
  for (const [key, ids] of entriesByKey) {
    if (ids.length === 0) continue
    const direct = new Set(ids.map(id => slots[id].event))
    const all = new Set<number>()
    for (const id of ids) lineageEvents(id, all)
    const ordered = [...all].sort((a, b) =>
      history.events[a].published < history.events[b].published ? -1
        : history.events[a].published > history.events[b].published ? 1 : a - b)
    affected.set(key, {
      key,
      events: ordered.map(e => ({
        eventIndex: e, kind: history.events[e].kind, year: history.events[e].year, direct: direct.has(e),
      })),
    })
  }

  return { coverage: history.coverage, affected, events }
}

/** The lineage for one merged key, or null when the key is not affected. */
export function lineageFor(index: TaxonomyHistoryIndex, key: string | null): AffectedSpecies | null {
  if (key === null) return null
  return index.affected.get(key) ?? null
}

/** The list control's entries (FR-11): affected keys in the selector's order,
 *  each with its events most recent first. */
export function historyListEntries(
  index: TaxonomyHistoryIndex,
  speciesOrder: readonly string[],
): HistoryListEntry[] {
  const out: HistoryListEntry[] = []
  for (const species of speciesOrder) {
    const a = index.affected.get(species)
    if (!a) continue
    out.push({ species, events: [...a.events].reverse().map(e => ({ kind: e.kind, year: e.year })) })
  }
  return out
}
