import { describe, it, expect } from 'vitest'
import { formatTide, formatTideBody, NOAA_CREDIT, TIDE_ATTRIBUTION, COMBINED_ATTRIBUTION } from './tideFormatter'
import type { TideReading } from './tide'
import type { TideStation } from './tideStations'

const STN: TideStation = { id: '9414290', name: 'San Francisco', lat: 37.8, lng: -122.5, state: 'CA', obs: true }

const reading: TideReading = {
  levelMin: 3.2, levelMax: 4.1, source: 'observed', trend: 'rising', turnedDuring: false,
  prevHL: { kind: 'low', v: 0.6, timeLocal: '5:02am' },
  nextHL: { kind: 'high', v: 5.1, timeLocal: '11:18am' },
  station: STN, distanceMi: 3.4,
}

describe('formatTideBody', () => {
  it('renders the block ending in the bare NOAA credit (no SnowRaven)', () => {
    const b = formatTideBody(reading)
    expect(b).toContain('🌊')
    expect(b).toContain('Observed')
    expect(b).toContain('Water level: 3.2 – 4.1 ft')
    expect(b).toContain('Tide: Rising')
    expect(b).toContain('Previous low: 0.6 ft at 5:02am')
    expect(b).toContain('Next high: 5.1 ft at 11:18am')
    expect(b).toContain('Station: San Francisco (9414290), 3.4 mi away')
    expect(b).toContain('Relative to MLLW')
    expect(b.endsWith(NOAA_CREDIT)).toBe(true)
    expect(b).not.toContain('SnowRaven')
  })
  it('shows a single value when min == max', () => {
    expect(formatTideBody({ ...reading, levelMin: 3.0, levelMax: 3.0 })).toContain('Water level: 3.0 ft')
  })
  it('notes a tide that turned during the checklist', () => {
    expect(formatTideBody({ ...reading, turnedDuring: true })).toContain('Tide: Rising (turned during your checklist)')
  })
  it('labels predicted source', () => {
    expect(formatTideBody({ ...reading, source: 'predicted' })).toContain('Predicted')
  })
})

describe('formatTide (standalone)', () => {
  it('ends with the NOAA credit + SnowRaven attribution', () => {
    const s = formatTide(reading)
    expect(s.endsWith(TIDE_ATTRIBUTION)).toBe(true)
    expect(s).toContain(NOAA_CREDIT)
    expect(TIDE_ATTRIBUTION).toContain('SnowRaven')
  })
})

describe('attribution constants', () => {
  it('the combined attribution is a single SnowRaven line', () => {
    expect(COMBINED_ATTRIBUTION).toContain('Weather and tide generated by')
    expect(COMBINED_ATTRIBUTION).toContain('snowraven')
  })
})
