// GENERATOR for tideEpoch.fixture.json, the shared cross-transport fixture for
// the `epochMin` / `_epoch_min` twin pair. It runs ONLY when
// SR_GEN_TIDE_EPOCH_FIXTURE=1 is set:
//
//   SR_GEN_TIDE_EPOCH_FIXTURE=1 npx vitest run src/lib/tideEpoch.fixtureGen.test.ts
//
// and is otherwise skipped, so it is a regeneration path and not a gate; the
// gates are tideEpoch.parity.test.ts here and backend/tests/test_tide_epoch_parity.py.
// Every expected value is produced by the SHIPPED `epochMin` (never a retyped
// rule), and the Python twin then has to reproduce it from the same string,
// which IS the parity claim -- a hand-written expected column would encode the
// author's model of the data, which is the model that wrote the bug (v1.0.21).
//
// The inputs are NOAA `lst_ldt` strings shaped exactly as CO-OPS ships them,
// plus the malformed shapes a provider body can carry. A fixture of conforming
// strings alone cannot see one twin raising where the other returns a value
// (.claude/rules/security.md), so the malformed shapes are first-class here and
// the ones that genuinely DISAGREE ride in their own `divergent` list rather
// than being quietly left out: a row that separates the twins is what makes
// their agreement elsewhere a measurement instead of an assumption.
/// <reference types="node" />
import { describe, it } from 'vitest'
import { writeFileSync } from 'node:fs'
import { epochMin } from './tide'

const OUT = new URL('./tideEpoch.fixture.json', import.meta.url)

/** Strings both transports must read identically. */
const AGREEING: Array<[string, string]> = [
  ['2026-11-01 01:00', 'the fall-back hour\'s first pass at a US/Pacific station; 2026-11-01 is the LA transition date'],
  ['2026-11-01 03:00', 'two calendar hours after the row above, across that transition'],
  ['2026-03-08 01:00', 'the hour before the spring-forward gap'],
  ['2026-03-08 03:00', 'the hour after it'],
  ['2026-06-01 12:00', 'an ordinary midday with no transition anywhere near it'],
  ['2025-09-15 08:51', 'a real subordinate-station high-water time'],
  ['2026-11-01T03:00', 'the ISO `T` separator, which the character class admits'],
  ['2026-11-01 01:00:30', 'seconds ride along: both sides match a PREFIX, not the whole string'],
  ['2026-11-01 01:00\n', 'a trailing newline rides along for the same reason'],
  ['\n2026-11-01 01:00', 'a LEADING newline does not: both patterns are anchored at the start'],
  ['2026-11\n-01 01:00', 'an embedded newline breaks the fixed-width run'],
  ['', 'the empty string'],
  ['not a date', 'ordinary junk'],
  ['٢٠٢٦-09-12 22:41', 'Arabic-Indic digits: ASCII-only classes on BOTH sides refuse them'],
  ['1970-01-01 00:00', 'the epoch itself, whose 0 is indistinguishable from the no-match sentinel'],
  ['9999-12-31 23:59', 'the far end of the calendar, which both sides carry'],
]

/** Strings the twins read DIFFERENTLY, pinned so neither can drift silently. */
const DIVERGENT: Array<[string, string]> = [
  ['2026-13-40 25:61', 'month 13: Date.UTC rolls over into the next year, Python refuses the calendar value'],
  ['2026-02-30 12:00', 'February 30: Date.UTC rolls to March 2, Python refuses it'],
  ['0001-01-01 00:00', 'years 0000-0099 hit Date.UTC\'s legacy two-digit-year mapping and land in 1901; Python reads year 1'],
]

describe.skipIf(!process.env.SR_GEN_TIDE_EPOCH_FIXTURE)('regenerate the tide epoch parity fixture', () => {
  it('writes tideEpoch.fixture.json from the shipped epochMin', () => {
    const doc = {
      note: 'Generated by tideEpoch.fixtureGen.test.ts from the shipped epochMin in tide.ts. Do not hand-edit.',
      rows: AGREEING.map(([t, why]) => ({ t, epochMin: epochMin(t), why })),
      divergent: DIVERGENT.map(([t, why]) => ({ t, epochMin: epochMin(t), why })),
    }
    writeFileSync(OUT, JSON.stringify(doc, null, 1) + '\n')
  })
})
