/**
 * Golden test suite for weatherFormatter.ts.
 *
 * Expected values were generated by running:
 *   python3 frontend/src/lib/weatherFormatter.golden.py
 *
 * Re-run that script if backend/formatters/weather.py changes.
 */
import { describe, it, expect } from 'vitest'
import {
  bankersRound,
  windDescription,
  cardinal,
  conditionEmoji,
  formatRange,
  formatLocalTime,
  formatWeather,
  type HourlyResponse,
} from './weatherFormatter'

// ─── Shared fixture helpers ───────────────────────────────────────────────────

const SR = 1714494600  // UTC → 4:30pm UTC (used in non-production fixtures)
const SS = 1714545000  // UTC → 6:30am UTC

function fixture(overrides: Partial<{
  temp: number; humidity: number; dew_point: number;
  wind_speed: number; wind_deg: number; clouds: number;
  owmId: number; description: string;
  sunrise: number; sunset: number;
}>): HourlyResponse {
  return {
    data: [{
      temp:        overrides.temp        ?? 72.0,
      humidity:    overrides.humidity    ?? 60,
      dew_point:   overrides.dew_point   ?? 55.0,
      wind_speed:  overrides.wind_speed  ?? 8.0,
      wind_deg:    overrides.wind_deg    ?? 0,
      clouds:      overrides.clouds      ?? 20,
      weather:     [{ id: overrides.owmId ?? 800, description: overrides.description ?? 'clear sky' }],
      sunrise:     overrides.sunrise     ?? SR,
      sunset:      overrides.sunset      ?? SS,
    }],
  }
}

// ─── bankersRound (QA-03 prerequisite) ────────────────────────────────────────

describe('bankersRound', () => {
  it('rounds .5 to even — 0.5 → 0', () => expect(bankersRound(0.5)).toBe(0))
  it('rounds .5 to even — 1.5 → 2', () => expect(bankersRound(1.5)).toBe(2))
  it('rounds .5 to even — 2.5 → 2', () => expect(bankersRound(2.5)).toBe(2))
  it('rounds .5 to even — 3.5 → 4', () => expect(bankersRound(3.5)).toBe(4))
  it('rounds .5 to even — 51.5 → 52', () => expect(bankersRound(51.5)).toBe(52))
  it('delegates non-.5 values to Math.round', () => {
    expect(bankersRound(54.3)).toBe(54)
    expect(bankersRound(0.4)).toBe(0)
    expect(bankersRound(1.6)).toBe(2)
  })
})

// ─── windDescription — Beaufort thresholds (QA-01) ────────────────────────────

describe('windDescription', () => {
  it('returns Calm at boundary ≤1', () => {
    expect(windDescription(0)).toBe('Calm')
    expect(windDescription(1)).toBe('Calm')
  })
  it('returns Mostly calm at boundary ≤3', () => {
    expect(windDescription(1.1)).toBe('Mostly calm')
    expect(windDescription(3)).toBe('Mostly calm')
  })
  it('returns Light breeze at boundary ≤7', () => {
    expect(windDescription(3.1)).toBe('Light breeze')
    expect(windDescription(7)).toBe('Light breeze')
  })
  it('returns Gentle breeze at boundary ≤12', () => {
    expect(windDescription(7.1)).toBe('Gentle breeze')
    expect(windDescription(12)).toBe('Gentle breeze')
  })
  it('returns Moderate breeze at boundary ≤18', () => {
    expect(windDescription(12.1)).toBe('Moderate breeze')
    expect(windDescription(18)).toBe('Moderate breeze')
  })
  it('returns Fresh breeze at boundary ≤24', () => {
    expect(windDescription(18.1)).toBe('Fresh breeze')
    expect(windDescription(24)).toBe('Fresh breeze')
  })
  it('returns Strong breeze at boundary ≤31', () => {
    expect(windDescription(24.1)).toBe('Strong breeze')
    expect(windDescription(31)).toBe('Strong breeze')
  })
  it('returns Near gale at boundary ≤38', () => {
    expect(windDescription(31.1)).toBe('Near gale')
    expect(windDescription(38)).toBe('Near gale')
  })
  it('returns Gale above 38', () => {
    expect(windDescription(38.1)).toBe('Gale')
    expect(windDescription(100)).toBe('Gale')
  })
})

// ─── cardinal — 8 directions (QA-02, QA-03) ───────────────────────────────────

describe('cardinal', () => {
  it('N at 0°', () => expect(cardinal(0)).toBe('N'))
  it('NE at 45°', () => expect(cardinal(45)).toBe('NE'))
  it('E at 90°', () => expect(cardinal(90)).toBe('E'))
  it('SE at 135°', () => expect(cardinal(135)).toBe('SE'))
  it('S at 180°', () => expect(cardinal(180)).toBe('S'))
  it('SW at 225°', () => expect(cardinal(225)).toBe('SW'))
  it('W at 270°', () => expect(cardinal(270)).toBe('W'))
  it('NW at 315°', () => expect(cardinal(315)).toBe('NW'))
  it('wraps back to N at 360°', () => expect(cardinal(360)).toBe('N'))

  // QA-03: banker's rounding at the 22.5° boundary — Python round(0.5) = 0 → N, not NE
  it('QA-03: cardinal(22.5) returns N, not NE (banker rounding)', () => {
    expect(cardinal(22.5)).toBe('N')
  })
  // Additional boundary checks
  it('67.5° rounds to E (bankersRound(1.5) = 2)', () => expect(cardinal(67.5)).toBe('E'))
  it('112.5° stays E (bankersRound(2.5) = 2)', () => expect(cardinal(112.5)).toBe('E'))
  it('157.5° rounds to S (bankersRound(3.5) = 4)', () => expect(cardinal(157.5)).toBe('S'))
})

// ─── conditionEmoji ────────────────────────────────────────────────────────────

describe('conditionEmoji', () => {
  it('maps thunderstorm range 200–232', () => {
    expect(conditionEmoji(200)).toBe('⛈️')
    expect(conditionEmoji(232)).toBe('⛈️')
  })
  it('maps drizzle range 300–321', () => expect(conditionEmoji(300)).toBe('🌦️'))
  it('maps rain range 500–531', () => expect(conditionEmoji(500)).toBe('🌧️'))
  it('maps snow range 600–622', () => expect(conditionEmoji(600)).toBe('❄️'))
  it('maps atmosphere range 700–781', () => expect(conditionEmoji(700)).toBe('🌫️'))
  it('maps 800 clear sky', () => expect(conditionEmoji(800)).toBe('☀️'))
  it('maps 801 few clouds', () => expect(conditionEmoji(801)).toBe('🌤️'))
  it('maps 802 scattered', () => expect(conditionEmoji(802)).toBe('⛅'))
  it('maps 803 broken', () => expect(conditionEmoji(803)).toBe('🌥️'))
  it('maps 804 overcast', () => expect(conditionEmoji(804)).toBe('☁️'))
  it('falls back to thermometer for unknown IDs', () => expect(conditionEmoji(999)).toBe('🌡️'))
})

// ─── formatRange (QA-04, QA-05) ───────────────────────────────────────────────

describe('formatRange', () => {
  it('QA-04: equal values return single value without separator', () => {
    expect(formatRange([72, 72], '°F')).toBe('72°F')
  })
  it('QA-05: different values return range', () => {
    expect(formatRange([68, 74], '°F')).toBe('68 - 74°F')
  })
  it('uses bankersRound — 51.5 rounds to 52', () => {
    expect(formatRange([51.5, 54.3], '°F')).toBe('52 - 54°F')
  })
  it('single value array returns single value', () => {
    expect(formatRange([54.3], '°F')).toBe('54°F')
  })
  it('works with percent unit', () => {
    expect(formatRange([100], '%')).toBe('100%')
  })
})

// ─── formatLocalTime (QA-06, QA-07) ───────────────────────────────────────────

describe('formatLocalTime', () => {
  // QA-06: no leading zero on the hour
  it('QA-06: no leading zero — 5:08am not 05:08am', () => {
    expect(formatLocalTime(1714554480, 'America/New_York')).toBe('5:08am')
  })
  // QA-07: noon returns 12:xx pm correctly
  it('QA-07: noon — 1714494600 in America/New_York → 12:30pm', () => {
    expect(formatLocalTime(1714494600, 'America/New_York')).toBe('12:30pm')
  })
  it('midnight — 1714450500 in America/New_York → 12:15am', () => {
    expect(formatLocalTime(1714450500, 'America/New_York')).toBe('12:15am')
  })
  it('formats minutes with zero-padding', () => {
    // sunrise on the production fixture: 5:08am — minutes "08" are zero-padded
    expect(formatLocalTime(1714554480, 'America/New_York')).toMatch(/:\d{2}/)
  })
})

// ─── formatWeather — golden matches ───────────────────────────────────────────

const ATTR = 'Weather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'

describe('formatWeather — attribution line (QA-13)', () => {
  it('output ends with the exact attribution HTML', () => {
    const out = formatWeather([fixture({})], 'UTC')
    expect(out.split('\n').at(-1)).toBe(ATTR)
  })
})

describe('formatWeather — single hour, calm wind', () => {
  it('golden match', () => {
    const f = fixture({ wind_speed: 0.5, wind_deg: 0, temp: 72.0, humidity: 60,
      dew_point: 55.0, clouds: 20, owmId: 800, description: 'clear sky' })
    const expected =
      '☀️\nClear sky\nTemperature: 72°F\nWind: Calm\nWind Direction: N\n' +
      'Cloud Cover: 20%\nHumidity: 60%\nDew point: 55°F\n' +
      'Sunrise: 4:30pm\nSunset: 6:30am\n' + ATTR
    expect(formatWeather([f], 'UTC')).toBe(expected)
  })
})

describe('formatWeather — single hour, gale wind', () => {
  it('golden match', () => {
    const f = fixture({ wind_speed: 45.0, wind_deg: 315, temp: 45.0, humidity: 80,
      dew_point: 40.0, clouds: 90, owmId: 500, description: 'light rain' })
    const expected =
      '🌧️\nLight rain\nTemperature: 45°F\nWind: Gale\nWind Direction: NW\n' +
      'Cloud Cover: 90%\nHumidity: 80%\nDew point: 40°F\n' +
      'Sunrise: 4:30pm\nSunset: 6:30am\n' + ATTR
    expect(formatWeather([f], 'UTC')).toBe(expected)
  })
})

describe('formatWeather — multi-hour, same Beaufort description (QA-08)', () => {
  it('deduplicates to single description', () => {
    const h1 = fixture({ wind_speed: 9.0, wind_deg: 90, temp: 60.0, humidity: 70,
      dew_point: 50.0, clouds: 30, owmId: 801, description: 'few clouds' })
    const h2 = fixture({ wind_speed: 11.0, wind_deg: 180, temp: 65.0, humidity: 65,
      dew_point: 48.0, clouds: 40, owmId: 801, description: 'few clouds' })
    const expected =
      '🌤️\nFew clouds\nTemperature: 60 - 65°F\nWind: Gentle breeze\nWind Direction: E - S\n' +
      'Cloud Cover: 30 - 40%\nHumidity: 65 - 70%\nDew point: 48 - 50°F\n' +
      'Sunrise: 4:30pm\nSunset: 6:30am\n' + ATTR
    expect(formatWeather([h1, h2], 'UTC')).toBe(expected)
  })
})

describe('formatWeather — multi-hour, different Beaufort descriptions sorted (QA-08)', () => {
  it('sorts by Beaufort order, not insertion order', () => {
    // Fresh breeze (20 mph) appears first, Light breeze (5 mph) second —
    // output must be Light breeze - Fresh breeze (sorted, not insertion order)
    const h1 = fixture({ wind_speed: 20.0, wind_deg: 90, temp: 60.0, humidity: 70,
      dew_point: 50.0, clouds: 30, owmId: 801, description: 'few clouds' })
    const h2 = fixture({ wind_speed: 5.0, wind_deg: 45, temp: 65.0, humidity: 65,
      dew_point: 48.0, clouds: 40, owmId: 801, description: 'few clouds' })
    const out = formatWeather([h1, h2], 'UTC')
    expect(out).toContain('Wind: Light breeze - Fresh breeze')
  })
})

describe('formatWeather — multi-hour, same cardinal direction (QA-09)', () => {
  it('deduplicates to single direction', () => {
    // 268° and 272° both round to W
    const h1 = fixture({ wind_speed: 8.0, wind_deg: 268, temp: 70.0, humidity: 50,
      dew_point: 45.0, clouds: 0, owmId: 800, description: 'clear sky' })
    const h2 = fixture({ wind_speed: 10.0, wind_deg: 272, temp: 72.0, humidity: 48,
      dew_point: 44.0, clouds: 5, owmId: 800, description: 'clear sky' })
    expect(formatWeather([h1, h2], 'UTC')).toContain('Wind Direction: W\n')
  })
})

describe('formatWeather — multi-hour, different directions preserve insertion order (QA-09)', () => {
  it('SW first then NE — not sorted', () => {
    const h1 = fixture({ wind_speed: 8.0, wind_deg: 225, temp: 68.0, humidity: 55,
      dew_point: 47.0, clouds: 10, owmId: 800, description: 'clear sky' })
    const h2 = fixture({ wind_speed: 9.0, wind_deg: 45, temp: 70.0, humidity: 52,
      dew_point: 45.0, clouds: 15, owmId: 800, description: 'clear sky' })
    expect(formatWeather([h1, h2], 'UTC')).toContain('Wind Direction: SW - NE\n')
  })
})

describe('formatWeather — equal-value range produces single value', () => {
  it('all identical values → no " - " separator', () => {
    const f = fixture({ temp: 72.0, humidity: 60, dew_point: 55.0, clouds: 50,
      owmId: 802, description: 'scattered clouds' })
    const out = formatWeather([f, f], 'UTC')
    expect(out).toContain('Temperature: 72°F\n')
    expect(out).toContain('Cloud Cover: 50%\n')
    expect(out).toContain('Humidity: 60%\n')
    expect(out).toContain('Dew point: 55°F\n')
  })
})

describe('formatWeather — condition capitalize (QA-10)', () => {
  it('lowercases all then uppercases first char only', () => {
    const f = fixture({ owmId: 803, description: 'BROKEN CLOUDS' })
    expect(formatWeather([f], 'UTC')).toContain('\nBroken clouds\n')
  })
  it('lowercases mixed-case description', () => {
    const f = fixture({ owmId: 804, description: 'overcast clouds' })
    expect(formatWeather([f], 'UTC')).toContain('\nOvercast clouds\n')
  })
})

describe('formatWeather — real production fixture golden match (QA-11)', () => {
  it('matches Python output byte-for-byte', () => {
    const response: HourlyResponse = {
      data: [{
        temp: 54.3, humidity: 89, dew_point: 51.5,
        wind_speed: 8.3, wind_deg: 270, clouds: 100,
        weather: [{ id: 804, description: 'overcast clouds' }],
        sunrise: 1714554480, sunset: 1714603980,
      }],
    }
    const expected =
      '☁️\nOvercast clouds\nTemperature: 54°F\nWind: Gentle breeze\nWind Direction: W\n' +
      'Cloud Cover: 100%\nHumidity: 89%\nDew point: 52°F\n' +
      'Sunrise: 5:08am\nSunset: 6:53pm\n' + ATTR
    expect(formatWeather([response], 'America/New_York')).toBe(expected)
  })
})

describe('formatWeather — multi-hour production-style golden match (QA-12)', () => {
  it('aggregates ranges and deduplicates directions correctly', () => {
    const h1: HourlyResponse = {
      data: [{
        temp: 54.3, humidity: 89, dew_point: 51.5,
        wind_speed: 8.3, wind_deg: 270, clouds: 100,
        weather: [{ id: 804, description: 'overcast clouds' }],
        sunrise: 1714554480, sunset: 1714603980,
      }],
    }
    const h2: HourlyResponse = {
      data: [{
        temp: 60.0, humidity: 85, dew_point: 55.0,
        wind_speed: 11.0, wind_deg: 270, clouds: 95,
        weather: [{ id: 804, description: 'overcast clouds' }],
        sunrise: 1714554480, sunset: 1714603980,
      }],
    }
    const out = formatWeather([h1, h2], 'America/New_York')
    expect(out).toContain('Temperature: 54 - 60°F')
    expect(out).toContain('Wind: Gentle breeze')      // both are Gentle breeze, deduped
    expect(out).toContain('Wind Direction: W')         // both 270°, deduped
    expect(out).toContain('Cloud Cover: 95 - 100%')
    expect(out).toContain('Humidity: 85 - 89%')
    expect(out).toContain('Dew point: 52 - 55°F')
    expect(out).toContain('Sunrise: 5:08am')
    expect(out).toContain('Sunset: 6:53pm')
    expect(out.split('\n').at(-1)).toBe(ATTR)
  })
})
