export interface HourlyResponse {
  data: Array<{
    dt: number;
    temp: number;
    humidity: number;
    dew_point: number;
    wind_speed: number;
    wind_deg: number;
    clouds: number;
    weather: Array<{ id: number; description: string }>;
    sunrise: number;
    sunset: number;
  }>;
}

const BEAUFORT: Array<[number, string]> = [
  [1, 'Calm'],
  [3, 'Mostly calm'],
  [7, 'Light breeze'],
  [12, 'Gentle breeze'],
  [18, 'Moderate breeze'],
  [24, 'Fresh breeze'],
  [31, 'Strong breeze'],
  [38, 'Near gale'],
  [Infinity, 'Gale'],
];

const BEAUFORT_ORDER: Record<string, number> = Object.fromEntries(
  BEAUFORT.map(([, label], i) => [label, i])
);

// Exported for lib/weatherBlockParse.ts, which READS these blocks back. Three
// export keywords, no logic change and no output change: the reader must take
// its vocabulary from the writer rather than restating it, which is what
// .claude/rules/weather-tide.md means by keeping the marker vocabulary synced.
export const CARDINALS = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'];

/** The nine Beaufort words in ORDINAL ORDER, derived from BEAUFORT so the two
 *  cannot drift. windDescription() emits exactly these and nothing else. */
export const BEAUFORT_WORDS = BEAUFORT.map(([, label]) => label);

/**
 * The closed 11-value condition set, in conditionEmoji()'s own branch order.
 *
 * This array is the INDEX CONTRACT for every weather figure: WeatherStats rows
 * are aligned to it, so reordering it silently re-labels every chart. Display
 * order is a separate, component-side decision.
 *
 * The PRESENTATION is load-bearing and is not uniform: ten of the eleven carry
 * the U+FE0F variation selector and the eleventh (U+26C5) does not, exactly as
 * conditionEmoji() emits them, so rendering a member reproduces what the block
 * says. U+FE0F is invisible, so an editor or a formatter could drop one with
 * nothing to see in review -- `weatherFormatter.test.ts` calls the real function
 * across every documented OpenWeather id range and asserts membership, which is
 * what turns that from a hope into a failure.
 */
export const CONDITION_EMOJI = [
  '⛈️', '🌦️', '🌧️', '❄️',
  '🌫️', '☀️', '🌤️', '⛅',
  '🌥️', '☁️', '🌡️',
] as const;

export type ConditionEmoji = typeof CONDITION_EMOJI[number];

export const ATTRIBUTION = 'Weather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>';

/**
 * THE ONE PREDICATE FOR "IS THIS PROVIDER FIGURE USABLE" ON THIS RUNTIME.
 * Byte-twin of `is_finite_figure` in backend/formatters/weather.py; every
 * refusal below and in forecastSlice.ts is expressed through it, so the two
 * transports cannot drift on what a malformed figure IS (.claude/rules/
 * security.md, "a twinned builder pair agrees on what a malformed figure is").
 *
 * The BOOLEAN exclusion is the one member a reader is likely to think
 * redundant, and it is MEASURED rather than reasoned: `Math.round(true)` is 1
 * and Python's `round(True)` is 1, so a boolean `temp` rendered
 * "Temperature: 1°F" on BOTH runtimes -- an AGREEING wrong number, which no
 * amount of cross-transport parity checking could ever have caught, and which
 * is the shape this build exists to remove. It was 9 of the 50 measured hour
 * shapes. `Number.isFinite` excludes NaN and both infinities.
 */
export function isFiniteFigure(v: unknown): v is number {
  return typeof v === 'number' && Number.isFinite(v);
}

/**
 * The nine figures every single-moment weather surface reads out of ONE
 * provider hour: the six the summary prints, plus the three clock fields
 * `formatLocalTime` and the night test dereference. Derived-from nothing --
 * this list IS the contract, and `assertHourFigures` iterates it, so a tenth
 * consumed field must be added here rather than checked ad hoc.
 */
export const HOUR_FIGURES = [
  'dt', 'temp', 'humidity', 'dew_point', 'wind_speed', 'wind_deg', 'clouds',
  'sunrise', 'sunset',
] as const;

function assertHourObject(hour: unknown): Record<string, unknown> {
  if (typeof hour !== 'object' || hour === null || Array.isArray(hour)) {
    throw new TypeError('malformed provider hour: not an object');
  }
  return hour as Record<string, unknown>;
}

/**
 * Refuse a malformed provider hour's NINE FIGURES. Twin of
 * `assert_hour_figures`.
 *
 * THIS IS THE HALF EVERY SAMPLED HOUR OF A MULTI-HOUR BODY CONTRIBUTES, which
 * is why it is separable from the condition half below. `formatWeatherBody`
 * aggregates six of these over every response it is handed (the Temperature,
 * Wind, Wind Direction, Cloud Cover, Humidity and Dew-point lines), and -- the
 * non-obvious three -- it reads `dt`, `sunrise` and `sunset` from every
 * response too, because `isNightHour` runs over all of them to decide whether
 * the block carries a moon emoji. A reader who sees only `first.sunrise` below
 * would conclude the clock fields were first-only; they are not, and that is
 * the reason this whole list is checked per response rather than split further.
 */
export function assertHourFigures(hour: unknown): void {
  const h = assertHourObject(hour);
  for (const field of HOUR_FIGURES) {
    if (!isFiniteFigure(h[field])) {
      throw new TypeError(`malformed provider hour: ${field} is not a finite number`);
    }
  }
}

/**
 * Refuse a malformed provider hour's CONDITION. Twin of
 * `assert_hour_condition`.
 *
 * THIS IS THE HALF ONLY THE FIRST SAMPLED HOUR CONTRIBUTES. `weather[0].id`
 * and `weather[0].description` become the emoji and the condition line, and
 * `formatWeatherBody` reads both from `first` alone -- a three-hour checklist's
 * later hours never reach them.
 *
 * VALIDATE WHAT IS DEREFERENCED is already this function's rule one level down:
 * `weather[1]` is deliberately unchecked because nothing reads it, and both
 * runtimes ignore it identically. Applying the same rule one level UP is what
 * keeps a provider hiccup on hour 2 of 3 from refusing a copy block whose every
 * printed field is fine -- see decision 11 in
 * pipeline/weather-at-malformed-parity/decisions.md for the measurement, and
 * `weatherAtMalformedParity.test.ts`'s multi-hour rows for the guard.
 */
export function assertHourCondition(hour: unknown): void {
  const h = assertHourObject(hour);
  const list = h.weather;
  if (!Array.isArray(list) || list.length === 0) {
    throw new TypeError('malformed provider hour: weather is not a non-empty list');
  }
  const first = list[0] as unknown;
  if (typeof first !== 'object' || first === null || Array.isArray(first)) {
    throw new TypeError('malformed provider hour: weather[0] is not an object');
  }
  const condition = first as Record<string, unknown>;
  if (!isFiniteFigure(condition.id)) {
    throw new TypeError('malformed provider hour: weather[0].id is not a finite number');
  }
  if (typeof condition.description !== 'string') {
    throw new TypeError('malformed provider hour: weather[0].description is not a string');
  }
}

/**
 * The WHOLE contract for ONE provider hour -- figures AND condition -- in the
 * shape the timemachine `data[0]` and every adapted forecast slice share. Twin
 * of `assert_hour_reading`.
 *
 * This is what a SINGLE-MOMENT caller wants: `buildWeatherPayload` reads every
 * figure and the condition out of one adapted hour, so it validates one hour
 * completely. A caller that aggregates several hours wants the two halves
 * separately, per the field each hour actually contributes.
 *
 * The verdict is a THROW rather than a null, because every caller already maps
 * a throw to the provider-error state its surface carries (502 on /weather/at
 * and /weather/{checklist_id}, `{status: 502}` on their desktop twins) -- the
 * containment closed at v1.0.31. A soft return would need eight new branches
 * and would put the honest state behind whichever caller remembered to check.
 *
 * WHAT THIS DOES NOT CLAIM. It is a check on ONE hour's figures, not a
 * plausibility check: `dt: 1e20` is a finite number and passes here, and both
 * runtimes then agree on the (wrong) night reading it produces. Agreement is
 * the property this guard delivers; range plausibility is a separate question
 * nobody has measured, is out of this build's scope rather than half-done in
 * it, and is handed to the Chronicler as a ROADMAP.md candidate at closeout
 * (nothing in ROADMAP.md names it yet).
 */
export function assertHourReading(hour: unknown): void {
  assertHourFigures(hour);
  assertHourCondition(hour);
}

// Replicates Python's round() which uses round-half-to-even (banker's rounding).
// JavaScript's Math.round() uses round-half-away-from-zero and diverges at .5 boundaries.
export function bankersRound(n: number): number {
  const floor = Math.floor(n);
  const diff = n - floor;
  if (diff === 0.5) return floor % 2 === 0 ? floor : floor + 1;
  return Math.round(n);
}

export function windDescription(mph: number): string {
  for (const [threshold, label] of BEAUFORT) {
    if (mph <= threshold) return label;
  }
  return 'Gale';
}

export function cardinal(degrees: number): string {
  return CARDINALS[bankersRound(degrees / 45) % 8];
}

export function conditionEmoji(owmId: number): string {
  if (owmId >= 200 && owmId <= 232) return '⛈️';
  if (owmId >= 300 && owmId <= 321) return '🌦️';
  if (owmId >= 500 && owmId <= 531) return '🌧️';
  if (owmId >= 600 && owmId <= 622) return '❄️';
  if (owmId >= 700 && owmId <= 781) return '🌫️';
  if (owmId === 800) return '☀️';
  if (owmId === 801) return '🌤️';
  if (owmId === 802) return '⛅';
  if (owmId === 803) return '🌥️';
  if (owmId === 804) return '☁️';
  return '🌡️';
}

// Moon phase — a port of lunarphase-js@2.0.3 (pinned from the npm dist), with one
// deliberate deviation: the Julian Day is computed in PURE UTC (the library bakes
// in the runtime's local tz offset). Both runtimes (this file and
// backend/formatters/weather.py) MUST use this same deterministic form so the
// TS and Python blocks stay byte-identical.
const LUNAR_MONTH = 29.53058770576;

// Bin upper bounds (age <) at odd multiples of LUNAR_MONTH / 16; ages at or
// past the last bound wrap back to New.
const MOON_PHASE_BOUNDS = [
  1.84566173161,  // New
  5.53698519483,  // Waxing Crescent
  9.22830865805,  // First Quarter
  12.91963212127, // Waxing Gibbous
  16.61095558449, // Full
  20.30227904771, // Waning Gibbous
  23.99360251093, // Last Quarter
  27.68492597415, // Waning Crescent
];

// Indexed by phase: New, Waxing Crescent, First Quarter, Waxing Gibbous, Full,
// Waning Gibbous, Last Quarter, Waning Crescent. The Southern Hemisphere sees
// the moon mirrored, so its set swaps the waxing/waning emoji.
// Exported (keyword only, no logic change) so the READER's own eight-glyph set
// can be asserted equal to their union. What weatherBlockParse.ts needs is the
// SET, and these two are orderings of it, so it holds its own literals -- the
// guard is what makes a future ninth glyph reach the parser rather than quietly
// failing to mark a checklist as night.
export const MOON_NORTH = ['🌑', '🌒', '🌓', '🌔', '🌕', '🌖', '🌗', '🌘'];
export const MOON_SOUTH = ['🌑', '🌘', '🌗', '🌖', '🌕', '🌔', '🌓', '🌒'];

export function moonPhaseEmoji(unixTs: number, lat: number): string {
  const jd = (unixTs * 1000) / 86400000 + 2440587.5;
  let frac = (jd - 2451550.1) / LUNAR_MONTH;
  frac = frac - Math.floor(frac);
  if (frac < 0) frac += 1;
  const age = frac * LUNAR_MONTH;
  const emojis = lat < 0 ? MOON_SOUTH : MOON_NORTH;
  for (let i = 0; i < MOON_PHASE_BOUNDS.length; i++) {
    if (age < MOON_PHASE_BOUNDS[i]) return emojis[i];
  }
  return emojis[0];
}

// A sampled hour is night when its dt falls outside the sunrise–sunset window.
function isNightHour(d: HourlyResponse['data'][number]): boolean {
  return d.dt < d.sunrise || d.dt > d.sunset;
}

export function formatRange(values: number[], unit: string): string {
  const rounded = values.map(bankersRound);
  const lo = Math.min(...rounded);
  const hi = Math.max(...rounded);
  if (lo === hi) return `${lo}${unit}`;
  return `${lo} - ${hi}${unit}`;
}

export function formatLocalTime(unixTs: number, tzName: string): string {
  const date = new Date(unixTs * 1000);
  const parts = new Intl.DateTimeFormat('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
    timeZone: tzName,
  }).formatToParts(date);
  const hour = parts.find(p => p.type === 'hour')!.value;
  const minute = parts.find(p => p.type === 'minute')!.value;
  const dayPeriod = parts.find(p => p.type === 'dayPeriod')!.value.toLowerCase();
  return `${hour}:${minute}${dayPeriod}`;
}

function capitalize(s: string): string {
  if (!s) return s;
  const lower = s.toLowerCase();
  return lower[0].toUpperCase() + lower.slice(1);
}

// The weather block WITHOUT the SnowRaven attribution line. The standalone
// formatWeather appends ATTRIBUTION; the "Copy Weather and Tide Together" action
// uses the body so it can emit ONE combined attribution at the very bottom.
export function formatWeatherBody(responses: HourlyResponse[], tzName: string, lat: number): string {
  // The copy block is the WIDEST of the three malformed-figure surfaces and the
  // only one whose output a user pastes into a public eBird checklist, so the
  // refusal sits here rather than only in the two callers: `/weather/at` (via
  // buildWeatherPayload) and `/weather/{checklist_id}` (via the desktop
  // getWeather / the FastAPI route) both funnel through this one function.
  // Before this guard, 37 of 50 measured malformed hour shapes produced
  // pasteable text here -- "Temperature: NaN - NaN°F", "Temperature: 0°F" from
  // a null, "Wind: Calm" from a null wind speed, "Wind: Gale" from the string
  // "warm", and an empty condition line, 8 of them carrying `NaN` -- where the
  // Python twin refused 41 of them. The 9 it also accepted are the boolean rows
  // described on `isFiniteFigure`, and on those the two AGREED on a wrong
  // number, which is why that exclusion is not redundant.
  //
  // THE CHECK IS PER FIELD-EACH-RESPONSE-CONTRIBUTES, not per response. The
  // nine figures are aggregated from EVERY sampled hour (including `dt`,
  // `sunrise` and `sunset`, via `isNightHour`), so every response's figures are
  // checked; the condition is read from `first` ALONE, so only `first`'s
  // condition is checked. Validating `first`-only fields on every response
  // would turn a provider hiccup on hour 2 of a 3-hour checklist into a total
  // refusal of a block whose every printed field is fine -- the same failure
  // mode the tier selector's candidate filter exists to prevent one module
  // over. Decision 11 carries the measurement and the both-directions
  // difference.
  if (!Array.isArray(responses) || responses.length === 0) {
    throw new TypeError('malformed provider body: no hourly responses');
  }
  for (const response of responses as unknown[]) {
    if (typeof response !== 'object' || response === null) {
      throw new TypeError('malformed provider body: a response is not an object');
    }
    const data = (response as { data?: unknown }).data;
    if (!Array.isArray(data) || data.length === 0) {
      throw new TypeError('malformed provider body: data is not a non-empty list');
    }
    assertHourFigures(data[0]);
  }

  const first = responses[0].data[0];
  assertHourCondition(first);

  const temps = responses.map(r => r.data[0].temp);
  const humids = responses.map(r => r.data[0].humidity);
  const dews = responses.map(r => r.data[0].dew_point);
  const windSpeeds = responses.map(r => r.data[0].wind_speed);

  const windDescs = [...new Set(windSpeeds.map(windDescription))].sort(
    (a, b) => BEAUFORT_ORDER[a] - BEAUFORT_ORDER[b]
  );

  const seenDirs = new Set<string>();
  const windDirs: string[] = [];
  for (const r of responses) {
    const dir = cardinal(r.data[0].wind_deg);
    if (!seenDirs.has(dir)) {
      seenDirs.add(dir);
      windDirs.push(dir);
    }
  }

  const clouds = responses.map(r => r.data[0].clouds);
  const emoji = conditionEmoji(first.weather[0].id);
  const condition = capitalize(first.weather[0].description);
  const sunrise = formatLocalTime(first.sunrise, tzName);
  const sunset = formatLocalTime(first.sunset, tzName);

  // Night checklist (any sampled hour outside its sunrise–sunset window): append
  // the moon-phase emoji — computed from the checklist START hour, matching
  // raincrow — to the condition emoji, UNSPACED. Unspaced is load-bearing: the
  // comment stripper (commentBlocks.ts) anchors a block on its last emoji RUN; a
  // space would split the run and leak the condition emoji on strip.
  const moon = responses.some(r => isNightHour(r.data[0]))
    ? moonPhaseEmoji(first.dt, lat)
    : '';

  return [
    `${emoji}${moon}`,
    condition,
    `Temperature: ${formatRange(temps, '°F')}`,
    `Wind: ${windDescs.join(' - ')}`,
    `Wind Direction: ${windDirs.join(' - ')}`,
    `Cloud Cover: ${formatRange(clouds, '%')}`,
    `Humidity: ${formatRange(humids, '%')}`,
    `Dew point: ${formatRange(dews, '°F')}`,
    `Sunrise: ${sunrise}`,
    `Sunset: ${sunset}`,
  ].join('\n');
}

export function formatWeather(responses: HourlyResponse[], tzName: string, lat: number): string {
  return `${formatWeatherBody(responses, tzName, lat)}\n${ATTRIBUTION}`;
}
