// SHARED-FIXTURE PARITY TEST -- the TS half of the Weather/tide Planner's twin
// builders (tide-weather-planner NFR-04 / QA-44), on weatherTidePlan.fixture.json,
// which backend/tests/test_weather_tide_plan_parity.py also drives. This side
// exercises the SHIPPED builders (buildWeatherPlan, buildTidePlan,
// planTideRange), never a retyped rule, and asserts deep equality with the
// expected halves plus canonical-JSON byte equality; the Python side does the
// same from the same raw bodies, which is the parity claim.
//
// The fixture is regenerated by the env-gated generator beside it. Each family
// also carries a non-vacuity check that it really contains the shape it is
// named for (the discriminating rows a fixture can quietly lose).
import { describe, it, expect } from 'vitest'
import fixture from './weatherTidePlan.fixture.json'
import { buildWeatherPlan, PLAN_CELLS_MAX, PLAN_DAYS_MAX, PLAN_EVENTS_MAX, PLAN_NIGHT_SPANS_MAX } from './weatherPlan'
import { buildTidePlan, planTideRange, PLAN_CURVE_MAX, PLAN_HILO_MAX } from './tidePlan'
import type { OneCallResponse } from './forecastSlice'
import type { TidePlanOk, WeatherPlan } from './plan'

interface Family {
  name: string
  shape: string
  tz: string
  nowTs: number
  lat: number
  lng: number
  station: { id: string; name: string }
  distanceMi: number
  force: boolean
  onecall: unknown
  predBody: unknown
  hiloBody: unknown
  span: { axisStartTs: number; tideEndTs: number; hiloStartTs: number; hiloEndTs: number }
  expectedWeather: { ok: true; plan: WeatherPlan } | { ok: false; reason: string }
  expectedTide: { status: string } & Partial<TidePlanOk>
}

const FAMILIES = (fixture as { families: Family[] }).families
const byName = Object.fromEntries(FAMILIES.map(f => [f.name, f])) as Record<string, Family>

const EXPECTED_NAMES = [
  'reference', 'subordinate', 'dst-fall', 'dst-spring', 'far-station', 'gap',
  'no-hourly', 'five-daily', 'polar', 'no-daily', 'missing-daily',
  'now-in-hour', 'same-minute-high', 'maximal',
]

/** Canonical (sorted-key, compact) JSON, the byte-comparison form both twins share. */
function canonical(v: unknown): string {
  const sort = (x: unknown): unknown => {
    if (Array.isArray(x)) return x.map(sort)
    if (x && typeof x === 'object') {
      return Object.fromEntries(Object.keys(x as object).sort().map(k => [k, sort((x as Record<string, unknown>)[k])]))
    }
    return x
  }
  return JSON.stringify(sort(v))
}

const plan = (name: string): WeatherPlan => (byName[name].expectedWeather as { ok: true; plan: WeatherPlan }).plan
const tide = (name: string): TidePlanOk => byName[name].expectedTide as TidePlanOk

describe('the shipped builders reproduce every family byte for byte', () => {
  it('the fixture carries every named family, in order', () => {
    expect(FAMILIES.map(f => f.name)).toEqual(EXPECTED_NAMES)
  })

  it.each(EXPECTED_NAMES)('%s: weather half', (name) => {
    const f = byName[name]
    const got = buildWeatherPlan(f.onecall as OneCallResponse, f.nowTs, f.tz, f.lat, f.lng)
    expect(got).toEqual(f.expectedWeather)
    expect(canonical(got)).toBe(canonical(f.expectedWeather))
  })

  it.each(EXPECTED_NAMES)('%s: tide half', (name) => {
    const f = byName[name]
    const span = planTideRange(f.nowTs, f.tz)
    expect(span).toEqual(f.span)
    const got = buildTidePlan(f.predBody, f.hiloBody, f.station, f.distanceMi, f.tz, span)
    expect(got).toEqual(f.expectedTide)
    expect(canonical(got)).toBe(canonical(f.expectedTide))
  })
})

describe('each family really holds the shape it is named for (non-vacuity)', () => {
  it('reference: continuous six-minute series, eight days, hourly and daily events', () => {
    const p = plan('reference'), t = tide('reference')
    expect(p.days).toHaveLength(8)
    expect(t.continuous).toBe(true)
    expect(t.curve.every(s => !s.hilo)).toBe(true)
    expect(p.events.some(e => e.weather.resolution === 'hourly')).toBe(true)
    expect(p.events.some(e => e.weather.resolution === 'daily')).toBe(true)
  })

  it('subordinate: the continuous body is a NOAA error and every sample is interpolated', () => {
    const f = byName['subordinate'], t = tide('subordinate')
    expect((f.predBody as { error?: unknown }).error).toBeTruthy()
    expect(t.continuous).toBe(false)
    expect(t.curve.length).toBeGreaterThan(0)
    expect(t.curve.every(s => s.hilo)).toBe(true)
  })

  it('dst-fall and dst-spring: the changed day is 25 or 23 hours long and a turning point inside the repeated hour lands at its instant', () => {
    expect(plan('dst-fall').days.some(d => d.endTs - d.startTs + 1 === 90000)).toBe(true)
    expect(plan('dst-spring').days.some(d => d.endTs - d.startTs + 1 === 82800)).toBe(true)
    const repeated = tide('dst-fall').turningPoints.filter(p => p.local === '2026-11-01 01:10')
    expect(repeated).toHaveLength(1)
    expect(repeated[0].t).toBe(Date.UTC(2026, 10, 1, 9, 10) / 1000)
  })

  it('far-station: the same GMT bodies land on the same instants with a different local clock', () => {
    const ref = tide('reference'), far = tide('far-station')
    expect(byName['far-station'].force).toBe(true)
    expect(far.tz).toBe('America/New_York')
    const byT = new Map(ref.turningPoints.map(p => [p.t, p]))
    const shared = far.turningPoints.filter(p => byT.has(p.t))
    expect(shared.length).toBeGreaterThan(20)
    for (const p of shared) {
      expect(p.v).toBe(byT.get(p.t)!.v)
      expect(p.local).not.toBe(byT.get(p.t)!.local)
    }
  })

  it('gap: the samples around the first sunrise are interpolated while the rest are continuous', () => {
    const p = plan('gap'), t = tide('gap')
    const sunrise = p.events.find(e => e.kind === 'sunrise')!.t
    const around = t.curve.filter(s => Math.abs(s.t - sunrise) <= 1800)
    expect(around.length).toBeGreaterThan(0)
    expect(around.every(s => s.hilo)).toBe(true)
    expect(t.curve.some(s => !s.hilo)).toBe(true)
  })

  it('no-hourly: the hourly end sits at the axis start and every cell and event is daily', () => {
    const p = plan('no-hourly')
    expect(p.hourlyEndTs).toBe(p.window.axisStartTs)
    expect(p.cells.length).toBeGreaterThan(0)
    expect(p.cells.every(c => c.resolution === 'daily')).toBe(true)
    expect(p.events.every(e => e.weather.resolution === 'daily')).toBe(true)
  })

  it('five-daily: the window ends on the fifth day', () => {
    const p = plan('five-daily')
    expect(p.days).toHaveLength(5)
    expect(p.window.endTs).toBe(p.days[4].endTs)
  })

  it('polar: missing events are omitted, never substituted', () => {
    const p = plan('polar')
    expect(p.days.some(d => d.sunset === null)).toBe(true)
    expect(p.days.some(d => d.sunrise === null)).toBe(true)
    const kinds = new Set(p.events.map(e => `${e.date}:${e.kind}`))
    for (const d of p.days) {
      if (d.sunset === null) expect(kinds.has(`${d.date}:sunset`)).toBe(false)
      if (d.sunrise === null) expect(kinds.has(`${d.date}:sunrise`)).toBe(false)
    }
  })

  it('no-daily and missing-daily: no plan', () => {
    expect(byName['no-daily'].expectedWeather).toEqual({ ok: false, reason: 'no-daily' })
    expect(byName['missing-daily'].expectedWeather).toEqual({ ok: false, reason: 'no-daily' })
  })

  it('now-in-hour: the first event reads the current block and labels it hourly', () => {
    const f = byName['now-in-hour'], p = plan('now-in-hour')
    const cur = (f.onecall as { current: { dt: number; weather: Array<{ description: string }> }; hourly: Array<{ weather: Array<{ description: string }> }> }).current
    expect(Math.abs(p.events[0].t - cur.dt)).toBeLessThanOrEqual(3600)
    expect(p.events[0].weather.resolution).toBe('hourly')
    expect(p.events[0].weather.description.toLowerCase()).toBe(cur.weather[0].description)
  })

  it('same-minute-high: a high sits at a sunrise minute', () => {
    const p = plan('same-minute-high'), t = tide('same-minute-high')
    const minutes = new Set(p.events.map(e => e.t - (e.t % 60)))
    expect(t.turningPoints.some(tp => tp.kind === 'high' && minutes.has(tp.t))).toBe(true)
  })

  it('maximal: the largest conforming shape stays under every cap', () => {
    const p = plan('maximal'), t = tide('maximal')
    expect(p.days.length).toBeLessThanOrEqual(PLAN_DAYS_MAX)
    expect(p.events.length).toBeLessThanOrEqual(PLAN_EVENTS_MAX)
    expect(p.cells.length).toBeLessThanOrEqual(PLAN_CELLS_MAX)
    expect(p.nightSpans.length).toBeLessThanOrEqual(PLAN_NIGHT_SPANS_MAX)
    expect(t.curve.length).toBeLessThanOrEqual(PLAN_CURVE_MAX)
    expect(t.turningPoints.length).toBeLessThanOrEqual(PLAN_HILO_MAX)
    expect(t.curve.length).toBeGreaterThanOrEqual(400)
  })
})
