/// <reference types="node" />
// Banding, the thresholds, the denominators, the row alignment and the
// zero-input bundle (weather-stats FR-13 … FR-28, NFR-02).
//
// Fixtures build their blocks by calling the REAL formatters, per
// `.claude/rules/weather-tide.md`, and their checklists through
// `computeChecklists` over real-shaped observation rows rather than by hand —
// a hand-written fixture encodes the author's mental model of the data, which
// is the same model that would write the bug, and ordering, grouping and
// de-duplication are precisely the properties it cannot test.
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import {
  computeWeatherStats, weatherSectionState, tempBandIndex, windBandIndex,
  cloudBandIndex, TEMP_BANDS, CLOUD_BANDS,
  WEATHER_SECTION_MIN_READABLE, WEATHER_BAND_MIN_TO_SHOW,
} from './weatherStats'
import type { WeatherStats } from './weatherStats'
import { computeChecklists } from './birdingStats'
import { CONDITION_EMOJI, formatWeather, ATTRIBUTION } from './weatherFormatter'
import type { HourlyResponse } from './weatherFormatter'
import type { ObservationEntry } from '../types'

// ── Block builders ──────────────────────────────────────────────────────────

const TZ = 'America/Los_Angeles'
function hourly(over: Partial<HourlyResponse['data'][number]> = {}): HourlyResponse {
  return {
    data: [{
      dt: 1716570000, temp: 64, humidity: 72, dew_point: 55, wind_speed: 6, wind_deg: 250,
      clouds: 20, weather: [{ id: 801, description: 'few clouds' }],
      sunrise: 1716550000, sunset: 1716600000, ...over,
    }],
  }
}

/** A SnowRaven block from the real formatter, at the given temperature. */
function srBlock(temp: number, owmId = 801, night = false): string {
  return formatWeather([hourly({ temp, weather: [{ id: owmId, description: 'x' }], ...(night ? { dt: 1716540000 } : {}) })], TZ, 33.7)
}

/** A RainCrow block, the collapsed single-line shape a real export carries. */
function rcBlock(body: string, header = '⛅'): string {
  return `${header}  Scattered clouds  ${body}  Weather generated by <a href="https://raincrow.app/">RainCrow</a>`
}

/** A block-shaped comment with weather LABELS and NO app attribution — the
 *  comment the attribution gate must refuse. */
function unattributed(body: string): string {
  return `⛅  Scattered clouds  ${body}`
}

// ── Observation builders ────────────────────────────────────────────────────

let seq = 0
const OBS_BASE: Omit<ObservationEntry, 'submissionId' | 'commonName' | 'scientificName'> = {
  date: '2024-05-24', location: 'Pond', locationId: 'L1', latitude: 1, longitude: 2,
  county: 'C', count: 1, breedingCode: null, speciesComments: '', catalogIds: [],
  time: '07:00 AM', duration: 60, distance: 1, area: null, protocol: 'Traveling',
  numObservers: 1, allObsReported: true, checklistComments: '', stateProvince: 'US-CA',
}

interface ChecklistSpec {
  comment: string
  species?: string[]
  duration?: number | null
  /** Extra observation ROWS for a species already listed, to prove counts are
   *  checklists rather than rows. */
  extraRows?: string[]
}

function build(specs: ChecklistSpec[]): { obs: ObservationEntry[]; stats: WeatherStats } {
  const obs: ObservationEntry[] = []
  for (const spec of specs) {
    const sub = `S${100000 + seq++}`
    const names = spec.species ?? ['Anna\'s Hummingbird']
    for (const n of [...names, ...(spec.extraRows ?? [])]) {
      obs.push({
        ...OBS_BASE,
        submissionId: sub,
        commonName: n,
        scientificName: 'Genus species',
        duration: spec.duration === undefined ? 60 : spec.duration,
        checklistComments: spec.comment,
      })
    }
  }
  const checklists = computeChecklists(obs)
  return { obs, stats: computeWeatherStats(checklists, obs) }
}

/** N checklists carrying the same block, each with its own species set. */
function repeat(n: number, comment: string, species: () => string[], duration: (i: number) => number | null = () => 60): ChecklistSpec[] {
  const out: ChecklistSpec[] = []
  for (let i = 0; i < n; i++) out.push({ comment, species: species(), duration: duration(i) })
  return out
}

const condRow = (s: WeatherStats, glyph: string) => s.byCondition[CONDITION_EMOJI.indexOf(glyph as never)]
const tempRow = (s: WeatherStats, label: string) => s.byTempBand[TEMP_BANDS.indexOf(label as never)]

// ── The two thresholds (FR-18) ──────────────────────────────────────────────

describe('the thresholds are named constants with their reasons in the code (FR-18)', () => {
  it('has both, at their approved values', () => {
    expect(WEATHER_SECTION_MIN_READABLE).toBe(5)
    expect(WEATHER_BAND_MIN_TO_SHOW).toBe(8)
  })

  it('does not import RATINGS_MIN_TO_SHOW, which happens to agree', () => {
    // Two independent judgements that agree today; coupling them would make a
    // future change to one silently move the other, so the module must carry no
    // IMPORT EDGE to it.
    //
    // Comments are stripped first, both forms: this module's own explanation of
    // why it does NOT import that constant names it, and a plain substring scan
    // would fail a correct file. Same rule as the observations-cache drift
    // guard, in the opposite direction.
    const src = source('./weatherStats.ts')
    expect(src).not.toContain('RATINGS_MIN_TO_SHOW')
    expect(src).not.toContain('mediaStats')
    // Non-vacuity: the stripper must not have eaten the code along with the
    // prose, or every assertion above passes against an empty string.
    expect(src).toContain('WEATHER_BAND_MIN_TO_SHOW = 8')
    expect(src).toContain("from './weatherBlockParse'")
  })

  it('imports neither the storage nor the transport seam, so nothing can be written', () => {
    const src = source('./weatherStats.ts')
    expect(src).not.toContain("from './storage'")
    expect(src).not.toContain("from './transport'")
    expect(src).not.toContain('setSetting')
    expect(src).not.toContain('deleteSetting')
    expect(src).not.toContain('fetch(')
  })

  it('neither new module scans export text with includes / indexOf / find (NFR-03)', () => {
    // The linearity grep, written down as an assertion rather than left as a
    // habit. Comments are stripped so each module's own explanation of why it
    // avoids these cannot fail the scan.
    for (const file of ['./weatherStats.ts', './weatherBlockParse.ts']) {
      const src = source(file)
      for (const bad of ['.includes(', '.indexOf(', '.find(', '.filter(']) {
        expect(src, `${file} contains ${bad}`).not.toContain(bad)
      }
      // Non-vacuity per file.
      expect(src.length, file).toBeGreaterThan(2000)
    }
  })
})

function source(rel: string): string {
  return stripComments(readFileSync(fileURLToPath(new URL(rel, import.meta.url)), 'utf8'))
}

/**
 * Drop line and block comments, line-wise. A source guard asserting a token is
 * ABSENT must not be defeated by prose, and one asserting a token is PRESENT
 * must not be satisfied by a commented-out line -- which is exactly the state a
 * half-reverted change leaves behind.
 */
function stripComments(src: string): string {
  const BLOCK_OPEN = '/' + '*'
  const BLOCK_CLOSE = '*' + '/'
  const out: string[] = []
  let inBlock = false
  for (const line of src.split('\n')) {
    let l = line
    if (inBlock) {
      const close = l.indexOf(BLOCK_CLOSE)
      if (close === -1) continue
      inBlock = false
      l = l.slice(close + 2)
    }
    const open = l.indexOf(BLOCK_OPEN)
    if (open !== -1) {
      const close = l.indexOf(BLOCK_CLOSE, open + 2)
      if (close === -1) { inBlock = true; l = l.slice(0, open) }
      else l = l.slice(0, open) + l.slice(close + 2)
    }
    const lineComment = l.indexOf('//')
    if (lineComment !== -1) l = l.slice(0, lineComment)
    out.push(l)
  }
  return out.join('\n')
}

// ── Banding (FR-19, FR-20, OQ-02) ───────────────────────────────────────────

describe('temperature bands: exactly one band, by the midpoint (FR-19)', () => {
  it('places each band by its own midpoint', () => {
    expect(tempBandIndex({ low: 10, high: 10 })).toBe(0)
    expect(tempBandIndex({ low: 40, high: 40 })).toBe(1)
    expect(tempBandIndex({ low: 50, high: 50 })).toBe(2)
    expect(tempBandIndex({ low: 60, high: 60 })).toBe(3)
    expect(tempBandIndex({ low: 70, high: 70 })).toBe(4)
    expect(tempBandIndex({ low: 80, high: 80 })).toBe(5)
    expect(tempBandIndex({ low: 90, high: 90 })).toBe(6)
  })

  it('holds every boundary exactly', () => {
    expect(tempBandIndex({ low: 31, high: 31 })).toBe(0)
    expect(tempBandIndex({ low: 32, high: 32 })).toBe(1)
    expect(tempBandIndex({ low: 44, high: 44 })).toBe(1)
    expect(tempBandIndex({ low: 45, high: 45 })).toBe(2)
    expect(tempBandIndex({ low: 54, high: 54 })).toBe(2)
    expect(tempBandIndex({ low: 55, high: 55 })).toBe(3)
    expect(tempBandIndex({ low: 64, high: 64 })).toBe(3)
    expect(tempBandIndex({ low: 65, high: 65 })).toBe(4)
    expect(tempBandIndex({ low: 74, high: 74 })).toBe(4)
    expect(tempBandIndex({ low: 75, high: 75 })).toBe(5)
    expect(tempBandIndex({ low: 84, high: 84 })).toBe(5)
    expect(tempBandIndex({ low: 85, high: 85 })).toBe(6)
  })

  it('a 52-58 range lands in "55 to 64°F" and a 30-90 range lands there too', () => {
    // Midpoint 55 and midpoint 60 — the wide range is counted ONCE, in one band,
    // never in every band it overlaps.
    expect(TEMP_BANDS[tempBandIndex({ low: 52, high: 58 })]).toBe('55 to 64°F')
    expect(TEMP_BANDS[tempBandIndex({ low: 30, high: 90 })]).toBe('55 to 64°F')
  })

  it('inherits the formatter\'s half-degree tie rule rather than inventing one', () => {
    // bankersRound: .5 goes to the EVEN integer. Midpoint 44.5 -> 44 (band 1),
    // midpoint 45.5 -> 46 (band 2). Math.round would send both up.
    expect(tempBandIndex({ low: 44, high: 45 })).toBe(1)
    expect(tempBandIndex({ low: 45, high: 46 })).toBe(2)
    expect(tempBandIndex({ low: 54, high: 55 })).toBe(2)
  })
})

describe('wind bands: the ordinal midpoint, tie downward (FR-20)', () => {
  it('takes floor((min + max) / 2)', () => {
    expect(windBandIndex({ minIndex: 0, maxIndex: 2 })).toBe(1)
    expect(windBandIndex({ minIndex: 2, maxIndex: 2 })).toBe(2)
    expect(windBandIndex({ minIndex: 0, maxIndex: 8 })).toBe(4)
  })

  it('resolves a tie DOWNWARD, toward the calmer band', () => {
    // Calm + Mostly calm -> Calm. The formatter emits a de-duplicated set, so
    // one gusty hour weighs as much as an hour that lasted the outing, which
    // makes the high end the least representative end.
    expect(windBandIndex({ minIndex: 0, maxIndex: 1 })).toBe(0)
    expect(windBandIndex({ minIndex: 3, maxIndex: 4 })).toBe(3)
    expect(windBandIndex({ minIndex: 7, maxIndex: 8 })).toBe(7)
  })
})

describe('cloud bands ship and are tested, and are deliberately not charted (OQ-02)', () => {
  it('mirrors the OpenWeather tiers, midpoint-assigned', () => {
    expect(cloudBandIndex({ low: 0, high: 0 })).toBe(0)
    expect(cloudBandIndex({ low: 10, high: 10 })).toBe(0)
    expect(cloudBandIndex({ low: 11, high: 11 })).toBe(1)
    expect(cloudBandIndex({ low: 25, high: 25 })).toBe(1)
    expect(cloudBandIndex({ low: 26, high: 26 })).toBe(2)
    expect(cloudBandIndex({ low: 50, high: 50 })).toBe(2)
    expect(cloudBandIndex({ low: 51, high: 51 })).toBe(3)
    expect(cloudBandIndex({ low: 84, high: 84 })).toBe(3)
    expect(cloudBandIndex({ low: 85, high: 85 })).toBe(4)
    expect(cloudBandIndex({ low: 100, high: 100 })).toBe(4)
    expect(cloudBandIndex({ low: 0, high: 100 })).toBe(2)
    expect(CLOUD_BANDS.length).toBe(5)
  })

  it('is not in the payload, so charting it later is a component change', () => {
    const { stats } = build([{ comment: srBlock(60) }])
    expect(Object.keys(stats)).not.toContain('byCloudBand')
  })
})

// ── The attribution gate (FR-13) ────────────────────────────────────────────

describe('the coverage denominator is the ATTRIBUTION gate (FR-13)', () => {
  it('counts SnowRaven and RainCrow blocks alike', () => {
    const { stats } = build([
      { comment: srBlock(60) },
      { comment: rcBlock('Temperature: 60°F  Wind: Calm') },
    ])
    expect(stats.foundCount).toBe(2)
    expect(stats.readableCount).toBe(2)
  })

  it('a comment with weather LABELS and no app credit counts in NEITHER the found nor the unreadable count', () => {
    const { stats } = build([
      { comment: unattributed('Temperature: 60°F  Wind: Calm  Humidity: 50%') },
      { comment: 'A lovely morning.' },
      { comment: '' },
    ])
    expect(stats.foundCount).toBe(0)
    expect(stats.readableCount).toBe(0)
    expect(stats.unreadableCount).toBe(0)
    expect(stats.totalChecklists).toBe(3)
  })

  it('found === readable + unreadable, always', () => {
    const { stats } = build([
      { comment: srBlock(60) },
      { comment: rcBlock('Temperature: nope  Wind: nope', '🦅') },
      { comment: unattributed('Temperature: 60°F  Wind: Calm') },
      { comment: 'prose' },
    ])
    expect(stats.foundCount).toBe(2)
    expect(stats.readableCount).toBe(1)
    expect(stats.unreadableCount).toBe(1)
    expect(stats.foundCount).toBe(stats.readableCount + stats.unreadableCount)
  })

  it('the found count is NOT required to equal the complement of the looser label-based test', () => {
    // The Weather tab's backlog uses the looser `hasWeatherBlock`, which matches
    // an uncredited block. The two figures differ DELIBERATELY, and this is the
    // assertion that keeps a future "consistency fix" from quietly coupling
    // them. `docs/HELP.md` states the difference.
    const { stats } = build([
      { comment: unattributed('Temperature: 60°F  Wind: Calm  Humidity: 50%') },
      { comment: srBlock(60) },
    ])
    expect(stats.totalChecklists).toBe(2)
    expect(stats.foundCount).toBe(1)
    expect(stats.totalChecklists - stats.foundCount).toBe(1)
  })
})

// ── Denominators and sums (FR-21, FR-22, FR-23) ─────────────────────────────

describe('every distribution sums to its OWN denominator (FR-21)', () => {
  it('the three axes sum independently, and legitimately differ', () => {
    const { stats } = build([
      // A condition and a temperature and a wind.
      { comment: srBlock(60) },
      // A temperature and a wind, no condition (an unrecognized header glyph).
      { comment: rcBlock('Temperature: 60°F  Wind: Calm', '🦅') },
      // A condition and a temperature, no wind (an unrecognized Beaufort word).
      { comment: rcBlock('Temperature: 60°F  Wind: quite blowy') },
      // A condition only.
      { comment: rcBlock('Humidity: 50%') },
    ])
    expect(stats.readableCount).toBe(4)
    const sum = (rows: Array<{ checklists: number }>) => rows.reduce((n, r) => n + r.checklists, 0)
    expect(sum(stats.byCondition)).toBe(3)
    expect(sum(stats.byTempBand)).toBe(3)
    expect(sum(stats.byWindBand)).toBe(2)
    // The three really are different, which is what the section's standing
    // sentence is about.
    expect(new Set([sum(stats.byCondition), sum(stats.byWindBand)]).size).toBe(2)
  })

  it('the temperature sum equals the readable checklists carrying a temperature, which is midpoint banding\'s proof', () => {
    const specs = [50, 52, 58, 30, 90, 70, 86].map(t => ({ comment: srBlock(t) }))
    const { stats } = build(specs)
    const sum = stats.byTempBand.reduce((n, r) => n + r.checklists, 0)
    expect(sum).toBe(7)
    expect(sum).toBe(stats.readableCount)
  })

  it('day + night === the day/night denominator, by construction (FR-22)', () => {
    const { stats } = build([
      { comment: srBlock(60) },
      { comment: srBlock(60, 804, true) },
      { comment: srBlock(60, 804, true) },
      // No header at all, so no day/night field: excluded from the denominator.
      { comment: `Temperature: 60°F  Wind: Calm  Humidity: 50%  ${ATTRIBUTION}` },
    ])
    expect(stats.dayNight).toEqual({ day: 1, night: 2, denominator: 3 })
    expect(stats.dayNight.day + stats.dayNight.night).toBe(stats.dayNight.denominator)
    expect(stats.readableCount).toBe(4)
  })
})

describe('a band with zero checklists is kept, not dropped (FR-23)', () => {
  it('always renders all 11, all 7 and all 9 rows', () => {
    const { stats } = build([{ comment: srBlock(60) }])
    expect(stats.byCondition.length).toBe(11)
    expect(stats.byTempBand.length).toBe(7)
    expect(stats.byWindBand.length).toBe(9)
    expect(stats.byCondition.filter(r => r.checklists === 0).length).toBe(10)
    expect(tempRow(stats, 'Below 32°F').checklists).toBe(0)
  })

  it('each row carries its own index and key, so display order can be reordered freely', () => {
    const { stats } = build([{ comment: srBlock(60) }])
    stats.byCondition.forEach((r, i) => { expect(r.index).toBe(i); expect(r.key).toBe(CONDITION_EMOJI[i]) })
    stats.byTempBand.forEach((r, i) => { expect(r.index).toBe(i); expect(r.key).toBe(TEMP_BANDS[i]) })
    stats.byWindBand.forEach((r, i) => expect(r.index).toBe(i))
  })
})

// ── Species and duration (FR-24, FR-25, FR-26) ──────────────────────────────

describe('species and duration averages, and the floor that refuses them (FR-24, FR-25, FR-26)', () => {
  const speciesFor = (i: number) => Array.from({ length: 10 + i }, (_, k) => `Sp ${k}`)

  it('a band with eight checklists averages both figures', () => {
    let i = 0
    const { stats } = build(repeat(8, srBlock(60), () => speciesFor(i++)))
    const row = tempRow(stats, '55 to 64°F')
    expect(row.checklists).toBe(8)
    // speciesCount 10..17 -> mean 13.5
    expect(row.avgSpecies).toBeCloseTo(13.5, 6)
    expect(row.avgDurationMin).toBe(60)
    expect(row.durationCount).toBe(8)
  })

  it('a band with seven checklists shows its count and NO average, and still appears', () => {
    let i = 0
    const { stats } = build(repeat(7, srBlock(60), () => speciesFor(i++)))
    const row = tempRow(stats, '55 to 64°F')
    expect(row.checklists).toBe(7)
    expect(row.avgSpecies).toBeNull()
    expect(row.avgDurationMin).toBeNull()
    // The band is still in the payload — dropping it would make the
    // distribution itself lie.
    expect(stats.byTempBand.length).toBe(7)
  })

  it('the duration figure has its OWN, smaller denominator', () => {
    // Twelve checklists in the band, four of them with a recorded duration.
    let i = 0
    const { stats } = build(repeat(12, srBlock(60), () => speciesFor(i++), n => (n < 4 ? 30 : null)))
    const row = tempRow(stats, '55 to 64°F')
    expect(row.checklists).toBe(12)
    expect(row.durationCount).toBe(4)
    // The band averages SPECIES...
    expect(row.avgSpecies).not.toBeNull()
    // ...and refuses to average four durations inside it. This goes one step
    // past the letter of the band-count rule and squarely with its intent.
    expect(row.avgDurationMin).toBeNull()
  })

  it('the duration average uses only the checklists that have one', () => {
    let i = 0
    const { stats } = build(repeat(10, srBlock(60), () => speciesFor(i++), n => (n < 8 ? 45 : null)))
    const row = tempRow(stats, '55 to 64°F')
    expect(row.checklists).toBe(10)
    expect(row.durationCount).toBe(8)
    expect(row.avgDurationMin).toBe(45)
  })

  it('the same figures are computed on the condition axis', () => {
    let i = 0
    const { stats } = build(repeat(8, srBlock(60, 800), () => speciesFor(i++)))
    const row = condRow(stats, '☀️')
    expect(row.checklists).toBe(8)
    expect(row.avgSpecies).toBeCloseTo(13.5, 6)
    expect(row.avgDurationMin).toBe(60)
  })
})

// ── medianTempSpanF (OQ-04) ─────────────────────────────────────────────────

describe('the median temperature span, the stated mitigation for midpoint banding', () => {
  it('is the LOWER median, so it is a span that actually occurred', () => {
    const { stats } = build([
      { comment: rcBlock('Temperature: 50 - 52°F') },   // span 2
      { comment: rcBlock('Temperature: 50 - 54°F') },   // span 4
      { comment: rcBlock('Temperature: 50 - 56°F') },   // span 6
      { comment: rcBlock('Temperature: 50 - 60°F') },   // span 10
    ])
    // Four spans: 2, 4, 6, 10. An interpolating median would report 5, which is
    // a span no block has.
    expect(stats.medianTempSpanF).toBe(4)
  })

  it('is null when no readable block carries a temperature', () => {
    const { stats } = build([{ comment: rcBlock('Humidity: 50%') }])
    expect(stats.readableCount).toBe(1)
    expect(stats.medianTempSpanF).toBeNull()
  })

  it('is zero when every block records a single temperature', () => {
    const { stats } = build([{ comment: srBlock(60) }, { comment: srBlock(70) }])
    expect(stats.medianTempSpanF).toBe(0)
  })
})

// ── The per-species view (FR-28, NFR-02) ────────────────────────────────────

describe('the per-species tally counts CHECKLISTS, never observation rows (FR-28)', () => {
  it('a species with three rows on one checklist contributes 1', () => {
    const { stats } = build([{
      comment: srBlock(60),
      species: ['Dark-eyed Junco'],
      // A subspecies row and a re-listed row on the SAME checklist. Both
      // normalize to the same species.
      extraRows: ['Dark-eyed Junco (Oregon)', 'Dark-eyed Junco'],
    }])
    const i = stats.species.names.indexOf('Dark-eyed Junco')
    expect(i).toBeGreaterThanOrEqual(0)
    expect(stats.species.names.length).toBe(1)
    expect(stats.species.checklists[i]).toBe(1)
    expect(stats.species.byCondition[i].reduce((a, b) => a + b, 0)).toBe(1)
  })

  it('holds only species on at least one readable-block checklist', () => {
    const { stats } = build([
      { comment: srBlock(60), species: ['On A Block'] },
      { comment: 'no block here', species: ['Not On A Block'] },
      { comment: unattributed('Temperature: 60°F  Wind: Calm'), species: ['Uncredited Only'] },
    ])
    expect(stats.species.names).toEqual(['On A Block'])
  })

  it('is sorted, and every parallel array is permuted with it', () => {
    const { stats } = build([
      { comment: srBlock(60), species: ['Zebra Dove', 'American Crow', 'Mallard'] },
    ])
    expect(stats.species.names).toEqual(['American Crow', 'Mallard', 'Zebra Dove'])
    expect(stats.species.checklists).toEqual([1, 1, 1])
    expect(stats.species.byCondition.length).toBe(3)
    expect(stats.species.byTempBand.length).toBe(3)
  })

  it('ROW ALIGNMENT is a contract: the non-zero entry sits at the index whose key is the expected condition', () => {
    // Read through `byCondition[j].key`, never a hard-coded position, so a
    // future reorder of the band table fails here rather than silently
    // re-labelling every species chart.
    const { stats } = build([
      { comment: srBlock(60, 800), species: ['Sun Bird'] },      // ☀️
      { comment: srBlock(60, 500), species: ['Rain Bird'] },     // 🌧️
    ])
    for (const [name, glyph] of [['Sun Bird', '☀️'], ['Rain Bird', '🌧️']] as const) {
      const i = stats.species.names.indexOf(name)
      const row = stats.species.byCondition[i]
      const hits: string[] = []
      row.forEach((n, j) => { if (n > 0) hits.push(stats.byCondition[j].key) })
      expect(hits, name).toEqual([glyph])
    }
  })

  it('the temperature-band alignment holds the same way', () => {
    const { stats } = build([
      { comment: srBlock(40), species: ['Cold Bird'] },
      { comment: srBlock(80), species: ['Warm Bird'] },
    ])
    for (const [name, band] of [['Cold Bird', '32 to 44°F'], ['Warm Bird', '75 to 84°F']] as const) {
      const i = stats.species.names.indexOf(name)
      const hits: string[] = []
      stats.species.byTempBand[i].forEach((n, j) => { if (n > 0) hits.push(stats.byTempBand[j].key) })
      expect(hits, name).toEqual([band])
    }
  })

  it('a readable block with neither a condition nor a temperature still counts toward the species total', () => {
    // The readout states a species' count against `readableCount`, so a
    // readable checklist missing from the tally would make that sentence
    // understate.
    const { stats } = build([
      { comment: rcBlock('Wind: Calm', '🦅'), species: ['Wind Only Bird'] },
    ])
    const i = stats.species.names.indexOf('Wind Only Bird')
    expect(stats.readableCount).toBe(1)
    expect(stats.species.checklists[i]).toBe(1)
    expect(stats.species.byCondition[i].reduce((a, b) => a + b, 0)).toBe(0)
    expect(stats.species.byTempBand[i].reduce((a, b) => a + b, 0)).toBe(0)
  })

  it('the payload is bounded by the SPECIES count, not the row count (NFR-02)', () => {
    // The same species set at 1x and 4x observation rows. What must not grow is
    // the SHAPE: one entry per species, 11 + 7 + 1 numbers each.
    const names = ['A Bird', 'B Bird', 'C Bird']
    const one = build([{ comment: srBlock(60), species: names }]).stats
    const four = build([{
      comment: srBlock(60),
      species: names,
      extraRows: [...names, ...names, ...names],
    }]).stats
    expect(four.species.names).toEqual(one.species.names)
    expect(four.species.byCondition.length).toBe(one.species.byCondition.length)
    expect(four.species.byCondition[0].length).toBe(11)
    expect(four.species.byTempBand[0].length).toBe(7)
    // And the counts themselves are unchanged, because they are checklists.
    expect(four.species.checklists).toEqual(one.species.checklists)
  })
})

// ── The section state (FR-16, FR-17) ────────────────────────────────────────

describe('weatherSectionState is the ONE discriminator (FR-16, FR-17)', () => {
  const stateFor = (n: number) => {
    let i = 0
    return weatherSectionState(build(repeat(n, srBlock(60), () => [`Sp ${i++}`])).stats)
  }

  it('is absent at zero found blocks', () => {
    expect(weatherSectionState(build([{ comment: 'prose' }]).stats)).toBe('absent')
    expect(weatherSectionState(build([{ comment: unattributed('Temperature: 60°F  Wind: Calm') }]).stats)).toBe('absent')
  })

  it('is below-floor from one readable block up to one below the floor', () => {
    expect(stateFor(1)).toBe('below-floor')
    expect(stateFor(WEATHER_SECTION_MIN_READABLE - 1)).toBe('below-floor')
  })

  it('is full at the floor and above', () => {
    expect(stateFor(WEATHER_SECTION_MIN_READABLE)).toBe('full')
    expect(stateFor(WEATHER_SECTION_MIN_READABLE + 3)).toBe('full')
  })

  it('is below-floor, never absent, when blocks were FOUND but none could be read', () => {
    // Found is what decides absence; readability decides charting. Otherwise a
    // user with seven unreadable blocks would be told nothing at all.
    const { stats } = build([
      { comment: rcBlock('Temperature: nope  Wind: nope', '🦅') },
      { comment: rcBlock('Temperature: nope  Wind: nope', '🦅') },
    ])
    expect(stats.foundCount).toBe(2)
    expect(stats.readableCount).toBe(0)
    expect(stats.unreadableCount).toBe(2)
    expect(weatherSectionState(stats)).toBe('below-floor')
  })
})

// ── The zero-input bundle, and clone safety (FR-33, schema 4.2) ─────────────

describe('the zero-input shape, which EMPTY_STATS_BUNDLE depends on', () => {
  it('does not throw on empty input and returns the fully-shaped object', () => {
    const s = computeWeatherStats([], [])
    expect(s.totalChecklists).toBe(0)
    expect(s.foundCount).toBe(0)
    expect(s.readableCount).toBe(0)
    expect(s.unreadableCount).toBe(0)
    expect(s.medianTempSpanF).toBeNull()
    expect(s.byCondition.length).toBe(11)
    expect(s.byTempBand.length).toBe(7)
    expect(s.byWindBand.length).toBe(9)
    expect(s.dayNight).toEqual({ day: 0, night: 0, denominator: 0 })
    expect(s.species).toEqual({ names: [], checklists: [], byCondition: [], byTempBand: [] })
    expect(weatherSectionState(s)).toBe('absent')
  })

  it('is NEVER null, which is what keeps the worker alive for a user with no blocks', () => {
    // A null here would fail `isStatsBundle` on every reply for every such user,
    // permanently parking the tab on the main-thread fallback with every figure
    // correct and nothing red.
    expect(computeWeatherStats([], [])).not.toBeNull()
    expect(typeof computeWeatherStats([], [])).toBe('object')
  })

  it('survives a structured-clone round trip (FR-33)', () => {
    let i = 0
    const { stats } = build(repeat(9, srBlock(60), () => [`Sp ${i++}`]))
    const cloned = structuredClone(stats)
    expect(cloned).toEqual(stats)
    // No Map, no Set, no function anywhere in the payload.
    const json = JSON.stringify(stats)
    expect(JSON.parse(json)).toEqual(stats)
  })
})

// ── No ranked or predictive data ────────────────────────────────────────────

describe('the payload offers nothing to rank species by (FR-29)', () => {
  it('carries no ordering by count and no rate', () => {
    const { stats } = build([
      { comment: srBlock(60), species: ['Common Bird', 'Rare Bird'] },
      { comment: srBlock(60), species: ['Common Bird'] },
    ])
    // Sorted by NAME, not by count: "Common Bird" is on two checklists and
    // "Rare Bird" on one, and the order is alphabetical either way.
    expect(stats.species.names).toEqual(['Common Bird', 'Rare Bird'])
    // Nothing in the payload is a rate or a score.
    const keys = new Set<string>()
    const walk = (v: unknown) => {
      if (Array.isArray(v)) { v.forEach(walk); return }
      if (v && typeof v === 'object') {
        for (const k of Object.keys(v)) { keys.add(k); walk((v as Record<string, unknown>)[k]) }
      }
    }
    walk(stats)
    for (const bad of ['rate', 'score', 'rank', 'best', 'likelihood']) {
      expect([...keys].some(k => k.toLowerCase().includes(bad)), bad).toBe(false)
    }
  })
})
