#!/usr/bin/env python3
"""
Reference oracle for weatherFormatter.ts golden tests.

Run from the repo root (no venv required):
    python3 frontend/src/lib/weatherFormatter.golden.py

These functions are an exact copy of the relevant parts of
backend/formatters/weather.py (excluding get_timezone, which is not
needed here since we pass ZoneInfo objects directly). If the Python
formatter changes, update both this script and the TypeScript tests.
"""

import math
from datetime import datetime
from zoneinfo import ZoneInfo

BEAUFORT = [
    (1, "Calm"),
    (3, "Mostly calm"),
    (7, "Light breeze"),
    (12, "Gentle breeze"),
    (18, "Moderate breeze"),
    (24, "Fresh breeze"),
    (31, "Strong breeze"),
    (38, "Near gale"),
    (math.inf, "Gale"),
]

_BEAUFORT_ORDER = {label: i for i, (_, label) in enumerate(BEAUFORT)}

CARDINALS = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]

ATTRIBUTION = 'Weather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'


def wind_description(mph: float) -> str:
    for threshold, label in BEAUFORT:
        if mph <= threshold:
            return label
    return "Gale"


def cardinal(degrees: float) -> str:
    return CARDINALS[round(degrees / 45) % 8]


def condition_emoji(owm_id: int) -> str:
    if 200 <= owm_id <= 232: return "⛈️"
    if 300 <= owm_id <= 321: return "🌦️"
    if 500 <= owm_id <= 531: return "🌧️"
    if 600 <= owm_id <= 622: return "❄️"
    if 700 <= owm_id <= 781: return "🌫️"
    if owm_id == 800: return "☀️"
    if owm_id == 801: return "🌤️"
    if owm_id == 802: return "⛅"
    if owm_id == 803: return "🌥️"
    if owm_id == 804: return "☁️"
    return "🌡️"


def format_range(values: list, unit: str = "") -> str:
    rounded = [round(v) for v in values]
    lo, hi = min(rounded), max(rounded)
    if lo == hi:
        return f"{lo}{unit}"
    return f"{lo} - {hi}{unit}"


def format_local_time(unix_ts: int, tz: ZoneInfo) -> str:
    dt = datetime.fromtimestamp(unix_ts, tz=tz)
    hour = dt.strftime("%I").lstrip("0") or "12"
    return f"{hour}:{dt.strftime('%M%p').lower()}"


def format_weather(hourly_responses: list, tz: ZoneInfo) -> str:
    first = hourly_responses[0]["data"][0]
    temps = [r["data"][0]["temp"] for r in hourly_responses]
    humids = [r["data"][0]["humidity"] for r in hourly_responses]
    dews = [r["data"][0]["dew_point"] for r in hourly_responses]
    wind_speeds = [r["data"][0]["wind_speed"] for r in hourly_responses]
    wind_descs = sorted(
        dict.fromkeys(wind_description(w) for w in wind_speeds),
        key=lambda d: _BEAUFORT_ORDER.get(d, 999),
    )
    wind_str = " - ".join(wind_descs)
    owm_id = first["weather"][0]["id"]
    condition = first["weather"][0]["description"].capitalize()
    emoji = condition_emoji(owm_id)
    wind_dirs = list(dict.fromkeys(cardinal(r["data"][0]["wind_deg"]) for r in hourly_responses))
    wind_dir = " - ".join(wind_dirs)
    clouds_list = [r["data"][0]["clouds"] for r in hourly_responses]
    sunrise = format_local_time(first["sunrise"], tz)
    sunset = format_local_time(first["sunset"], tz)
    return (
        f"{emoji}\n{condition}\n"
        f"Temperature: {format_range(temps, '°F')}\n"
        f"Wind: {wind_str}\n"
        f"Wind Direction: {wind_dir}\n"
        f"Cloud Cover: {format_range(clouds_list, '%')}\n"
        f"Humidity: {format_range(humids, '%')}\n"
        f"Dew point: {format_range(dews, '°F')}\n"
        f"Sunrise: {sunrise}\n"
        f"Sunset: {sunset}\n"
        f"{ATTRIBUTION}"
    )


# ─── Test fixtures ────────────────────────────────────────────────────────────

TZ_NY = ZoneInfo("America/New_York")
TZ_UTC = ZoneInfo("UTC")

# Shared sunrise/sunset for non-production fixtures (UTC timezone)
SR = 1714494600   # 1714494600 UTC → 4:30pm UTC
SS = 1714545000   # 1714545000 UTC → 6:30am UTC (next UTC day wrap)

PRODUCTION = {"data": [{"temp": 54.3, "humidity": 89, "dew_point": 51.5,
    "wind_speed": 8.3, "wind_deg": 270, "clouds": 100,
    "weather": [{"id": 804, "description": "overcast clouds"}],
    "sunrise": 1714554480, "sunset": 1714603980}]}

CALM = {"data": [{"temp": 72.0, "humidity": 60, "dew_point": 55.0,
    "wind_speed": 0.5, "wind_deg": 0, "clouds": 20,
    "weather": [{"id": 800, "description": "clear sky"}],
    "sunrise": SR, "sunset": SS}]}

GALE = {"data": [{"temp": 45.0, "humidity": 80, "dew_point": 40.0,
    "wind_speed": 45.0, "wind_deg": 315, "clouds": 90,
    "weather": [{"id": 500, "description": "light rain"}],
    "sunrise": SR, "sunset": SS}]}

GENTLE_A = {"data": [{"temp": 60.0, "humidity": 70, "dew_point": 50.0,
    "wind_speed": 9.0, "wind_deg": 90, "clouds": 30,
    "weather": [{"id": 801, "description": "few clouds"}],
    "sunrise": SR, "sunset": SS}]}

GENTLE_B = {"data": [{"temp": 65.0, "humidity": 65, "dew_point": 48.0,
    "wind_speed": 11.0, "wind_deg": 180, "clouds": 40,
    "weather": [{"id": 801, "description": "few clouds"}],
    "sunrise": SR, "sunset": SS}]}

FRESH_FIRST = {"data": [{"temp": 60.0, "humidity": 70, "dew_point": 50.0,
    "wind_speed": 20.0, "wind_deg": 90, "clouds": 30,
    "weather": [{"id": 801, "description": "few clouds"}],
    "sunrise": SR, "sunset": SS}]}

LIGHT_SECOND = {"data": [{"temp": 65.0, "humidity": 65, "dew_point": 48.0,
    "wind_speed": 5.0, "wind_deg": 45, "clouds": 40,
    "weather": [{"id": 801, "description": "few clouds"}],
    "sunrise": SR, "sunset": SS}]}

W_A = {"data": [{"temp": 70.0, "humidity": 50, "dew_point": 45.0,
    "wind_speed": 8.0, "wind_deg": 268, "clouds": 0,
    "weather": [{"id": 800, "description": "clear sky"}],
    "sunrise": SR, "sunset": SS}]}

W_B = {"data": [{"temp": 72.0, "humidity": 48, "dew_point": 44.0,
    "wind_speed": 10.0, "wind_deg": 272, "clouds": 5,
    "weather": [{"id": 800, "description": "clear sky"}],
    "sunrise": SR, "sunset": SS}]}

SW_FIRST = {"data": [{"temp": 68.0, "humidity": 55, "dew_point": 47.0,
    "wind_speed": 8.0, "wind_deg": 225, "clouds": 10,
    "weather": [{"id": 800, "description": "clear sky"}],
    "sunrise": SR, "sunset": SS}]}

NE_SECOND = {"data": [{"temp": 70.0, "humidity": 52, "dew_point": 45.0,
    "wind_speed": 9.0, "wind_deg": 45, "clouds": 15,
    "weather": [{"id": 800, "description": "clear sky"}],
    "sunrise": SR, "sunset": SS}]}

EQUAL = {"data": [{"temp": 72.0, "humidity": 60, "dew_point": 55.0,
    "wind_speed": 8.0, "wind_deg": 0, "clouds": 50,
    "weather": [{"id": 802, "description": "scattered clouds"}],
    "sunrise": SR, "sunset": SS}]}

CAPS = {"data": [{"temp": 68.0, "humidity": 55, "dew_point": 47.0,
    "wind_speed": 8.0, "wind_deg": 90, "clouds": 75,
    "weather": [{"id": 803, "description": "BROKEN CLOUDS"}],
    "sunrise": SR, "sunset": SS}]}


def section(label: str, output: str) -> None:
    print(f"=== {label} ===")
    print(repr(output))
    print()


if __name__ == "__main__":
    section("production fixture (America/New_York)", format_weather([PRODUCTION], TZ_NY))
    section("calm wind single-hour (UTC)", format_weather([CALM], TZ_UTC))
    section("gale wind single-hour (UTC)", format_weather([GALE], TZ_UTC))
    section("multi-hour same beaufort (UTC)", format_weather([GENTLE_A, GENTLE_B], TZ_UTC))
    section("multi-hour different beaufort sorted (UTC)", format_weather([FRESH_FIRST, LIGHT_SECOND], TZ_UTC))
    section("multi-hour same direction dedup (UTC)", format_weather([W_A, W_B], TZ_UTC))
    section("multi-hour different directions insertion order (UTC)", format_weather([SW_FIRST, NE_SECOND], TZ_UTC))
    section("equal value range (UTC)", format_weather([EQUAL, EQUAL], TZ_UTC))
    section("capitalize mixed case (UTC)", format_weather([CAPS], TZ_UTC))

    print("=== format_local_time: noon ===")
    print(repr(format_local_time(1714494600, TZ_NY)))   # → 12:30pm

    print("=== format_local_time: midnight ===")
    print(repr(format_local_time(1714450500, TZ_NY)))   # → 12:15am

    print()
    print("=== bankersRound verification (Python round) ===")
    for n in [0.5, 1.5, 2.5, 3.5, 51.5, 54.3, 0.4, 1.6]:
        print(f"  round({n}) = {round(n)}")
